<?php  
	$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $englishs["$basename"]; 
 
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php  
					echo reciterHeaderNew($current); 
				?>  
				
			</div> 
	        <div class="row reciter-container">	  
			    <div class=" archive-playlist-title">
									<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
				</div>
				<div class="row btns-player-catagory">  
					<a href='#' class="btn  btn-success " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#playlist1'}); return false;"><i class="fa fa-book"></i> Part 1</a>	  
					<a href='#' class=" btn   " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#a'}); return false;"><i class="fa fa-book"></i> Part 2</a>
					
					<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#b'}); return false;"><i class="fa fa-book"></i> Part 3</a> 
					
					<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#c'}); return false;"><i class="fa fa-book"></i> Part 4</a>  
					
					<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#clear'}); return false;"><i class="fa fa-book"></i> Clear</a>
					 
					<script>
						$(function() {
						  $('.btn').click( function() {
							$(this).addClass('btn-success').siblings().removeClass('btn-success');
						  });
						});
					</script>
				</div> 
				
				<?php  include $path . '/player/player_code.php';     ?> 
			
				<div id="playlist_list"> 
					<ul id='clear'>  </ul>
					<ul id='playlist1'>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-11.11.11.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - 11.11.11 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-11.11.11.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-11.11.11.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-AChallengeForTheYouth.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - A Challenge For the Youth </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-AChallengeForTheYouth.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-AChallengeForTheYouth.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-AFriendInNeedIsAFriendIndeed.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - A Friend in Need Is A Friend Indeed </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-AFriendInNeedIsAFriendIndeed.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-AFriendInNeedIsAFriendIndeed.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-AGoodMuslim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - A Good Muslim </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-AGoodMuslim.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-AGoodMuslim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-AJourneyOfFaith.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - A Journey of Faith </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-AJourneyOfFaith.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-AJourneyOfFaith.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-AdviceForAMuslim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Advice For A Muslim </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-AdviceForAMuslim.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-AdviceForAMuslim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-AdviceToParentsAndTeachers.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Advice To Parents And Teachers </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-AdviceToParentsAndTeachers.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-AdviceToParentsAndTeachers.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-AreWeLosingFocus.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Are We Losing Focus </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-AreWeLosingFocus.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-AreWeLosingFocus.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-BeautyOfTheNobleQuraan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Beauty Of The Noble Qur'aan </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-BeautyOfTheNobleQuraan.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-BeautyOfTheNobleQuraan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-BeingSteadfastOnThePath.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Being Steadfast On The Path </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-BeingSteadfastOnThePath.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-BeingSteadfastOnThePath.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-BeingTheChangeYouWantAndNeed.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Being The Change You Want And Need </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-BeingTheChangeYouWantAndNeed.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-BeingTheChangeYouWantAndNeed.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-BlessingOfSalaah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Blessing Of Salaah </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-BlessingOfSalaah.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-BlessingOfSalaah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
					</ul>
					<ul id='a'>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-BusinessEttiquetes.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Business Ettiquetes </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-BusinessEttiquetes.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-BusinessEttiquetes.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-CharacterAndSocialConductOfAMuslim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Character and Social Conduct of a Muslim </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-CharacterAndSocialConductOfAMuslim.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-CharacterAndSocialConductOfAMuslim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ConnectionToTheYouth.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Connection to the Youth </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ConnectionToTheYouth.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ConnectionToTheYouth.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-CopingWithCalamities.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Coping With Calamities </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-CopingWithCalamities.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-CopingWithCalamities.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-CrisisOfTheMuslimUmmah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Crisis of The Muslim Ummah </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-CrisisOfTheMuslimUmmah.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-CrisisOfTheMuslimUmmah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-DeathYourTimeIsUp.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Death, Your Time is Up </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-DeathYourTimeIsUp.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-DeathYourTimeIsUp.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-DevelopingAnIslamicPersonality.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Developing An Islamic Personality </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-DevelopingAnIslamicPersonality.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-DevelopingAnIslamicPersonality.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-DeviationistTendenciesInIslamicBeliefsThoughtsPractices.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Deviationist Tendencies In Islamic Beliefs, Thoughts & Practices </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-DeviationistTendenciesInIslamicBeliefsThoughtsPractices.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-DeviationistTendenciesInIslamicBeliefsThoughtsPractices.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-DiversityThroughUnity.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Diversity Through Unity </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-DiversityThroughUnity.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-DiversityThroughUnity.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-EtiquetteOfTheWorkplace.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Etiquette Of The Workplace </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-EtiquetteOfTheWorkplace.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-EtiquetteOfTheWorkplace.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-EttiquetesOfSpeaking.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Ettiquetes of Speaking </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-EttiquetesOfSpeaking.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-EttiquetesOfSpeaking.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ExcellentExampleOfMuhammadpbuh.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Excellent Example of Muhammad (PBUH) </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ExcellentExampleOfMuhammadpbuh.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ExcellentExampleOfMuhammadpbuh.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-FocusOnThePleasureOfYourMaker.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Focus On The Pleasure of Your Maker </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-FocusOnThePleasureOfYourMaker.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-FocusOnThePleasureOfYourMaker.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-FriendsimportanceOfGoodCompany.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Friends (Importance of Good Company) </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-FriendsimportanceOfGoodCompany.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-FriendsimportanceOfGoodCompany.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-HarmsOfExcessBaggage.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Harms of Excess Baggage </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-HarmsOfExcessBaggage.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-HarmsOfExcessBaggage.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-HelpMeOutOfMyMess.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Help Me Out Of My Mess </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-HelpMeOutOfMyMess.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-HelpMeOutOfMyMess.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-IfTodayWasYourLastDay.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - If Today Was Your Last Day </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-IfTodayWasYourLastDay.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-IfTodayWasYourLastDay.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-InAllahsNameWeEatPrayAndLove.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - In Allah's Name We Eat, Pray and Love </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-InAllahsNameWeEatPrayAndLove.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-InAllahsNameWeEatPrayAndLove.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-InspireTheFuture.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Inspire The Future </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-InspireTheFuture.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-InspireTheFuture.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-IslamicGreetings.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Islamic Greetings </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-IslamicGreetings.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-IslamicGreetings.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode1Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 1 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode1Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode1Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode2Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 2 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode2Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode2Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode3Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 3 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode3Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode3Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode4Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 4 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode4Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode4Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode5Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 5 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode5Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode5Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode6Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 6 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode6Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode6Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode7Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 7 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode7Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode7Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode8Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 8 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode8Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode8Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode9Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 9 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode9Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode9Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode10Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 10 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode10Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode10Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode11Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 11 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode11Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode11Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode12Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 12 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode12Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode12Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode13Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 13 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode13Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode13Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode14Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 14 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode14Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode14Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode15Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 15 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode15Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode15Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode16Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 16 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode16Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode16Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode17Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 17 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode17Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode17Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode18Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 18 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode18Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode18Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode19Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 19 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode19Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode19Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode20Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 20 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode20Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode20Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode21Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 21 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode21Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode21Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode22Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 22 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode22Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode22Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode23Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 23 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode23Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode23Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode24Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 24 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode24Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode24Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode25Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 25 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode25Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode25Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode26Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 26 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode26Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode26Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-JewelsFromTheHolyQuranepisode27Of27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Jewels From The Holy Quran [Episode 27 of 27] </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode27Of27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-JewelsFromTheHolyQuranepisode27Of27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-KhatamDuaRamadan1434.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Khatam Dua Ramadan 1434 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-KhatamDuaRamadan1434.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-KhatamDuaRamadan1434.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-LessonsFromSurahAlKahf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Lessons From Surah Al Kahf </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-LessonsFromSurahAlKahf.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-LessonsFromSurahAlKahf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-LessonsFromTheLivesOfTheProphets.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Lessons from the Lives of the Prophets </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-LessonsFromTheLivesOfTheProphets.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-LessonsFromTheLivesOfTheProphets.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-LessonsOnMattersOfBelief.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Lessons On Matters Of Belief </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-LessonsOnMattersOfBelief.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-LessonsOnMattersOfBelief.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
					</ul>
					<ul id='b'>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-LifeOfTheLastMessenger-Day01.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Life of the Last Messenger - Day 01 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-LifeOfTheLastMessenger-Day01.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-LifeOfTheLastMessenger-Day01.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-LifeOfTheLastMessenger-Day02.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Life of the Last Messenger - Day 02 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-LifeOfTheLastMessenger-Day02.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-LifeOfTheLastMessenger-Day02.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-LifeOfTheLastMessenger-Day11.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Life of the Last Messenger - Day 11 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-LifeOfTheLastMessenger-Day11.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-LifeOfTheLastMessenger-Day11.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-MisconceptionsAboutIslam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Misconceptions About Islam </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-MisconceptionsAboutIslam.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-MisconceptionsAboutIslam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-NaturalDisastersInLightOfIslam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Natural Disasters in Light of Islam </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-NaturalDisastersInLightOfIslam.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-NaturalDisastersInLightOfIslam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-Parent-childRelationship.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Parent-Child Relationship </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-Parent-childRelationship.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-Parent-childRelationship.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-PreparingForRamadan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Preparing for Ramadan </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-PreparingForRamadan.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-PreparingForRamadan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-Pride-diseaseOfTheHeart.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Pride-Disease of the Heart </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-Pride-diseaseOfTheHeart.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-Pride-diseaseOfTheHeart.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-PurposeOfCreation.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Purpose Of Creation </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-PurposeOfCreation.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-PurposeOfCreation.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-RaisingTomorrowsLeadersToday.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Raising Tomorrow's Leaders Today </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-RaisingTomorrowsLeadersToday.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-RaisingTomorrowsLeadersToday.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day01.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 01 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day01.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day01.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day02.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 02 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day02.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day02.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day03.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 03 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day03.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day03.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day04.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 04 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day04.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day04.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day05.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 05 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day05.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day05.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day06.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 06 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day06.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day06.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day07.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 07 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day07.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day07.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day08.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 08 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day08.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day08.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day09.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 09 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day09.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day09.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day10.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 10 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day10.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day10.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day11.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 11 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day11.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day11.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day12.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 12 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day12.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day12.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day13.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 13 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day13.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day13.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day14.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 14 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day14.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day14.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day15.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 15 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day15.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day15.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day16.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 16 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day16.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day16.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day17.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 17 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day17.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day17.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day18.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 18 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day18.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day18.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day19.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 19 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day19.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day19.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day20.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 20 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day20.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day20.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day21.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 21 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day21.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day21.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day22.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 22 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day22.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day22.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day23.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 23 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day23.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day23.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day24.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 24 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day24.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day24.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day25.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 25 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day25.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day25.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day26.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 26 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day26.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day26.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 27 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day28.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 28 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day28.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day28.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReasonsOfRevelation-Day29.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Reasons of Revelation - Day 29 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day29.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReasonsOfRevelation-Day29.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ReligionAndWork.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Religion and Work </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ReligionAndWork.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ReligionAndWork.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-Sabr-TheVirtueOfPatience.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Sabr - The Virtue Of Patience </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-Sabr-TheVirtueOfPatience.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-Sabr-TheVirtueOfPatience.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-SeekingKnowledgeAndEducation.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Seeking Knowledge and Education </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-SeekingKnowledgeAndEducation.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-SeekingKnowledgeAndEducation.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-SocialNetworking-TheIslamicPerspective.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Social Networking - The Islamic Perspective </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-SocialNetworking-TheIslamicPerspective.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-SocialNetworking-TheIslamicPerspective.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-SomeInspirationAndLessonsFromAlQuran.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Some Inspiration And Lessons From Al Quran </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-SomeInspirationAndLessonsFromAlQuran.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-SomeInspirationAndLessonsFromAlQuran.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
					</ul>
					<ul id='c'>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day01.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 01 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day01.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day01.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day03.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 03 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day03.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day03.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day05.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 05 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day05.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day05.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day06.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 06 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day06.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day06.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day07.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 07 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day07.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day07.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day08.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 08 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day08.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day08.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day09.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 09 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day09.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day09.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day10.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 10 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day10.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day10.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 27 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day27.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day28.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 28 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day28.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day28.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StoriesOfTheProphets-Day29.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Stories of the Prophets - Day 29 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day29.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StoriesOfTheProphets-Day29.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-StrongHomeStrongCommunity.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Strong Home Strong Community </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-StrongHomeStrongCommunity.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-StrongHomeStrongCommunity.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-SurahFatihaTheMotherOfTheBook.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Surah Fatiha The Mother of The Book </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-SurahFatihaTheMotherOfTheBook.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-SurahFatihaTheMotherOfTheBook.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-SurahYusuf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Surah Yusuf </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-SurahYusuf.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-SurahYusuf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-SweetnessOfImaan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Sweetness Of Imaan </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-SweetnessOfImaan.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-SweetnessOfImaan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TafseerOfSurahAlFatiha.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Tafseer Of Surah Al Fatiha </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TafseerOfSurahAlFatiha.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TafseerOfSurahAlFatiha.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TafseerOfSurahTaha.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Tafseer Of Surah Taha </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TafseerOfSurahTaha.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TafseerOfSurahTaha.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TafseerSurahTaha.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Tafseer Surah Taha </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TafseerSurahTaha.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TafseerSurahTaha.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-Taqwa2012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Taqwa 2012 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-Taqwa2012.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-Taqwa2012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-Temptation.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Temptation </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-Temptation.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-Temptation.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheBeautyOfIslam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Beauty of Islam </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheBeautyOfIslam.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheBeautyOfIslam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheCreaturesOfTheAlmighty.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Creatures of the Almighty </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheCreaturesOfTheAlmighty.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheCreaturesOfTheAlmighty.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheDevilsPlan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Devil's Plan </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheDevilsPlan.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheDevilsPlan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheFortunateMuslimFamily.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Fortunate Muslim Family </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheFortunateMuslimFamily.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheFortunateMuslimFamily.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheImportanceOfSalah2012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Importance of Salah 2012 </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheImportanceOfSalah2012.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheImportanceOfSalah2012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-ThePureSoul.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Pure Soul </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-ThePureSoul.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-ThePureSoul.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheRoleOfMedia.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Role of Media </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheRoleOfMedia.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheRoleOfMedia.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheSeasonOfThankfulnessRepentanceAndAsking.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Season Of Thankfulness, Repentance and Asking </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheSeasonOfThankfulnessRepentanceAndAsking.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheSeasonOfThankfulnessRepentanceAndAsking.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheShadeOfDayOfJudgement.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Shade of Day of Judgement </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheShadeOfDayOfJudgement.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheShadeOfDayOfJudgement.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheTsOfMarriage.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Ts of Marriage </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheTsOfMarriage.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheTsOfMarriage.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-TheWrongMotivesOfLife.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - The Wrong Motives of Life </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-TheWrongMotivesOfLife.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-TheWrongMotivesOfLife.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-UnityAndBrotherhood.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Unity and Brotherhood </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-UnityAndBrotherhood.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-UnityAndBrotherhood.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-WhatDoIGainWithAllThisPain.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - What Do I Gain With All This Pain </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-WhatDoIGainWithAllThisPain.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-WhatDoIGainWithAllThisPain.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-WhatHaveWeAchievedInOurLife.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - What Have We Achieved in Our Life </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-WhatHaveWeAchievedInOurLife.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-WhatHaveWeAchievedInOurLife.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-WinTheBattleAgainstTemptation.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Win the Battle Against Temptation </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-WinTheBattleAgainstTemptation.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-WinTheBattleAgainstTemptation.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-YourChildYourJannah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Your Child, Your Jannah </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-YourChildYourJannah.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-YourChildYourJannah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuftiMenk//MuftiMenk-YourFriendIsAllahswt.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Mufti Menk - Your Friend is Allah (SWT) </a><a class='dlink' href=' https://archive.org/download/MuftiMenk/MuftiMenk-YourFriendIsAllahswt.mp3' data-dlink=' https://archive.org/download/MuftiMenk/MuftiMenk-YourFriendIsAllahswt.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
					</ul>
				</div>
			</div>
			<?php  include $path . '/pages/gallery.php';     ?>  	 	  	
		   <div class="row reciter-container" id="youtube-videos">	
					<script>
						var videosURL = ["Kx8PhADzvgY","eOKTcZyuCaM","sWFLF-CY-Eg","ADiTs-ZXuhw","hDDODs95Xj0","WK0aRjk1xZY"];
					</script>	 
					<?php  include $path . '/pages/videos.php';     ?>  	 	
 
					 
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>Ismail Musa Menk was born in Harare, Zimbabwe.<br>
					<br>
					He is a student of knowledge trying to disseminate the Deen in the current age.<br><br>

					Mufti Menk did his Initial studies in Harare, Zimbabwe. He attained a degree in Shariah Law from the University of Madinah Munawwarah . He went on to  specialize in Jurisprudence in Gujarat, India .<br><br>

					Mufti Menk is a broad minded, motivational speaker who has endeared himself to both Muslims and non Muslims.<br><br>

					He is the Head of the Fatwa Department of The Council of Islamic Scholars of Zimbabwe known as Majlisul Ulama Zimbabwe.<br><br>

					He is also one of the Muaththins and an Imaam at Masjid Al Falaah in Harare.<br><br>

					Mufti Menk has been on many speaking engagements and lecture tours around the globe.<br><br>

					He contributes regularly towards the Islamic content of various media networks and is an experienced social worker and counsellor.<br><br>

					He enjoys spending time with the underpriviledged, lending a helping hand and teaching them.<br><br>

					Each year, during the holy month of Ramadhaan , he spends time with a  far away community, disseminating the  teachings of Islam.<br><br>

					His work is all done solely for the Pleasure of the Almighty without any remuneration or financial rewards.<br><br>

					There are no copyrights, no charges, no royalties, no patents and no cost involved to invite him.<br><br>

					May Allah grant us all acceptance, protect Mufti Menk and facilitate his work in sowing the seeds of knowledge.<br><br>
					</p>
				</div>  	
			</div>
			
</div>			



<?php  include $path . '/pages/footer.php'; ?>
