export const ACTION_TYPE = {
    COMPLETE: 'COMPLETE',
    REJECTED: 'REJECTED'
}

export const RECITERS_ACTION_TYPES = {
    RECITERS_COMPLETE: 'RECITERS_COMPLETE',
    RECITERS_REJECTED: 'RECITERS_REJECTED'
}