<?php  
	$path = $_SERVER['DOCUMENT_ROOT']; 
	$section = 'reciters'; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $mujawwads["$basename"]; 
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeader($current); 
				?>  
				
			</div> 
			<div class="row reciter-container">	  
				    <div class=" archive-playlist-title">
										<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
					</div>  
					<div class="row btns-player-catagory">  
						<a href='#' class="btn  btn-success " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#playlist1'}); return false;"><i class="fa fa-book"></i> Part 1</a>	  
						<a href='#' class=" btn   " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#Part2'}); return false;"><i class="fa fa-book"></i> Part 2</a>
						
						<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#Part3'}); return false;"><i class="fa fa-book"></i> Part 3</a> 
						
						<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#Part4'}); return false;"><i class="fa fa-book"></i> Part 4</a> 
						
						<a href='#' class=" btn   " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#Part5'}); return false;"><i class="fa fa-book"></i> Part 5</a>
						
						<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#clear'}); return false;"><i class="fa fa-book"></i> Clear</a>
						 
						<script>
							$(function() {
							  $('.btn').click( function() {
								$(this).addClass('btn-success').siblings().removeClass('btn-success');
							  });
							});
						</script>
					</div> 
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->	
							<ul id='clear'>
							</ul>
							<ul id='playlist1'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//1-002-Shahat-Ensan1-22.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>1- 002 - SHAHAT - ENSAN 1-22 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/1-002-Shahat-Ensan1-22.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/1-002-Shahat-Ensan1-22.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//4-002-Shahat-Ebrahim31-44.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>4- 002 - SHAHAT- EBRAHIM 31-44 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/4-002-Shahat-Ebrahim31-44.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/4-002-Shahat-Ebrahim31-44.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//5-003-Shahat-Enfetar1-end.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>5- 003 - SHAHAT - ENFETAR 1-END </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/5-003-Shahat-Enfetar1-end.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/5-003-Shahat-Enfetar1-end.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//8-003-Shahat-Araf42-64.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>8- 003 - SHAHAT- ARAF 42-64 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/8-003-Shahat-Araf42-64.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/8-003-Shahat-Araf42-64.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//9-004-Shahat-Bagharea252-261.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>9- 004 - SHAHAT - BAGHARE (A) 252-261 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/9-004-Shahat-Bagharea252-261.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/9-004-Shahat-Bagharea252-261.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//12-004-Shahat-Loghman1-end.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>12- 004 - SHAHAT- LOGHMAN 1-end </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/12-004-Shahat-Loghman1-end.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/12-004-Shahat-Loghman1-end.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//13-005-Shahat-Baghareb252-261.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>13- 005 - SHAHAT - BAGHARE (B) 252-261 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/13-005-Shahat-Baghareb252-261.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/13-005-Shahat-Baghareb252-261.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//16-005-Shahat-Noor34-40.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>16- 005 - SHAHAT- NOOR 34-40 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/16-005-Shahat-Noor34-40.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/16-005-Shahat-Noor34-40.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//17-006-Shahat-Baghare267-281.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>17- 006 - SHAHAT - BAGHARE 267-281 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/17-006-Shahat-Baghare267-281.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/17-006-Shahat-Baghare267-281.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//20-006-Shahat-Yousof1-22.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>20- 006 - SHAHAT- YOUSOF 1-22 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/20-006-Shahat-Yousof1-22.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/20-006-Shahat-Yousof1-22.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//23-007-Shahat-Tahrim1-endZelzal.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>23- 007 - SHAHAT - TAHRIM 1-END & ZELZAL </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/23-007-Shahat-Tahrim1-endZelzal.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/23-007-Shahat-Tahrim1-endZelzal.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//24-007-Shahat-Ahzab38-48Nazeat26-endNasr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>24- 007 - SHAHAT- AHZAB 38-48 & NAZEAT 26-END & NASR </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/24-007-Shahat-Ahzab38-48Nazeat26-endNasr.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/24-007-Shahat-Ahzab38-48Nazeat26-endNasr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//27-008-Shahat-Tahrim1-8.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>27- 008 - SHAHAT - TAHRIM 1-8 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/27-008-Shahat-Tahrim1-8.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/27-008-Shahat-Tahrim1-8.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//28-008-Shahat-Asra1-15.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>28- 008 - SHAHAT- ASRA 1-15 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/28-008-Shahat-Asra1-15.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/28-008-Shahat-Asra1-15.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//31-009-Shahat-Tobe60-82.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>31- 009 - SHAHAT - TOBE 60-82 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/31-009-Shahat-Tobe60-82.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/31-009-Shahat-Tobe60-82.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//32-009-Shahat-Araf47-64.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>32- 009 - SHAHAT- ARAF 47-64 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/32-009-Shahat-Araf47-64.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/32-009-Shahat-Araf47-64.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//33-019-Shahat-Naml45-88.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>33- 019 - SHAHAT - NAML 45-88 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/33-019-Shahat-Naml45-88.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/33-019-Shahat-Naml45-88.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>	
							<ul id='Part2'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//35-010-Shahat-Haj18-38.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>35- 010 - SHAHAT - HAJ 18-38 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/35-010-Shahat-Haj18-38.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/35-010-Shahat-Haj18-38.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//37-010-Shahat-Shora1-17.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>37- 010 - SHAHAT - SHORA 1-17 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/37-010-Shahat-Shora1-17.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/37-010-Shahat-Shora1-17.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//38-010-Shahat-Anbiya83-end.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>38- 010 - SHAHAT- ANBIYA 83-END </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/38-010-Shahat-Anbiya83-end.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/38-010-Shahat-Anbiya83-end.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//41-011-Shahat-Haj23-38.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>41- 011 - SHAHAT - HAJ 23-38 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/41-011-Shahat-Haj23-38.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/41-011-Shahat-Haj23-38.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//43-011-Shahat-Baghare25-38.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>43- 011 - SHAHAT- BAGHARE 25-38 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/43-011-Shahat-Baghare25-38.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/43-011-Shahat-Baghare25-38.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//45-012-Shahat-Hojorat13-endEnsherahTinAlaghGhadrGhoraishKosar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>45- 012 - SHAHAT - HOJORAT13-END & ENSHERAH & TIN & ALAGH & GHADR & GHORAISH & KOSAR </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/45-012-Shahat-Hojorat13-endEnsherahTinAlaghGhadrGhoraishKosar.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/45-012-Shahat-Hojorat13-endEnsherahTinAlaghGhadrGhoraishKosar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//47-012-Shahat-Anbiya83-endHaj1-5.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>47- 012 - SHAHAT- ANBIYA 83-END & HAJ 1-5 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/47-012-Shahat-Anbiya83-endHaj1-5.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/47-012-Shahat-Anbiya83-endHaj1-5.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//50-013-Shahat-Zokhrof81-endNabaEnfetarGhoraishKosar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>50- 013 - SHAHAT - ZOKHROF 81-END & NABA & ENFETAR & GHORAISH & KOSAR </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/50-013-Shahat-Zokhrof81-endNabaEnfetarGhoraishKosar.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/50-013-Shahat-Zokhrof81-endNabaEnfetarGhoraishKosar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//51-013-Shahat-Anam54-80.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>51- 013 - SHAHAT- ANAM 54-80 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/51-013-Shahat-Anam54-80.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/51-013-Shahat-Anam54-80.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//54-014-Shahat-Shora1-22.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>54- 014 - SHAHAT - SHORA 1-22 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/54-014-Shahat-Shora1-22.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/54-014-Shahat-Shora1-22.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//55-014-Shahat-Al-emran52-76.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>55- 014 - SHAHAT- AL-EMRAN 52-76 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/55-014-Shahat-Al-emran52-76.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/55-014-Shahat-Al-emran52-76.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//58-015-Shahat-Shora23-end.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>58- 015 - SHAHAT - SHORA 23-END </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/58-015-Shahat-Shora23-end.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/58-015-Shahat-Shora23-end.mp3'><img src='media/data/dlink.png' alt = ''/></a></li> 
							</ul>	
							<ul id='Part3'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//59-015-Shahat-Al-emran12-20.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>59- 015 - SHAHAT- AL-EMRAN 12-20 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/59-015-Shahat-Al-emran12-20.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/59-015-Shahat-Al-emran12-20.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//62-016-Shahat-Taha1-46.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>62- 016 - SHAHAT - TAHA 1-46 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/62-016-Shahat-Taha1-46.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/62-016-Shahat-Taha1-46.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//63-016-Shahat-Baghare196-203.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>63- 016 - SHAHAT- BAGHARE 196-203 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/63-016-Shahat-Baghare196-203.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/63-016-Shahat-Baghare196-203.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//64-017-Shahat-Abas11-endTakvirEnfetar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>64- 017 - SHAHAT - ABAS 11-END & TAKVIR & ENFETAR </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/64-017-Shahat-Abas11-endTakvirEnfetar.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/64-017-Shahat-Abas11-endTakvirEnfetar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//68-018-Shahat-Naml15-44.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>68- 018 - SHAHAT - NAML 15-44 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/68-018-Shahat-Naml15-44.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/68-018-Shahat-Naml15-44.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//2-002-Shahat-Fath27-endNazeat26-33.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>2- 002 - SHAHAT - FATH 27-END & NAZEAT 26-33 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/2-002-Shahat-Fath27-endNazeat26-33.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/2-002-Shahat-Fath27-endNazeat26-33.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//3-002-Shahat-Jome9-endLailTinAlaghZelzalAsrHamd.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>3- 002 - SHAHAT - JOME 9-END & LAIL & TIN & ALAGH & ZELZAL & ASR & HAMD </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/3-002-Shahat-Jome9-endLailTinAlaghZelzalAsrHamd.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/3-002-Shahat-Jome9-endLailTinAlaghZelzalAsrHamd.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//6-003-Shahat-Forghan1-76.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>6- 003 - SHAHAT - FORGHAN 1-76 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/6-003-Shahat-Forghan1-76.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/6-003-Shahat-Forghan1-76.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//7-003-Shahat-Haj75-endMomenoon1-22.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>7- 003 - SHAHAT - HAJ 75-END & MOMENOON 1-22 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/7-003-Shahat-Haj75-endMomenoon1-22.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/7-003-Shahat-Haj75-endMomenoon1-22.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//10-004-Shahat-Foselat30-39.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>10- 004 - SHAHAT - FOSELAT 30-39 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/10-004-Shahat-Foselat30-39.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/10-004-Shahat-Foselat30-39.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Aal-Imran_studio_v33-56_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Aal-Imran_studio_v33-56_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Aal-Imran_studio_v33-56_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Aal-Imran_studio_v33-56_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Aal-Imran_v33-51_Shams_Duha_Inshirah_Teen_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Aal-Imran_v33-51_Shams_Duha_Inshirah_Teen_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Aal-Imran_v33-51_Shams_Duha_Inshirah_Teen_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Aal-Imran_v33-51_Shams_Duha_Inshirah_Teen_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//11-004-Shahat-Shora1-19.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>11- 004 - SHAHAT - SHORA 1-19 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/11-004-Shahat-Shora1-19.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/11-004-Shahat-Shora1-19.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Aal-imran_v96-148_naziat_haqqah_abuEl-elaMosque_1966_by.dr.kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Aal-Imran_v96-148_Naziat_Haqqah_Abu El-Ela Mosque_1966_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Aal-imran_v96-148_naziat_haqqah_abuEl-elaMosque_1966_by.dr.kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Aal-imran_v96-148_naziat_haqqah_abuEl-elaMosque_1966_by.dr.kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Ahzab_63-73_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ahzab_63-73_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ahzab_63-73_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ahzab_63-73_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//14-005-Shahat-GhesarzohaSharhTin.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>14- 005 - SHAHAT - GHESAR (ZOHA & SHARH & TIN) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/14-005-Shahat-GhesarzohaSharhTin.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/14-005-Shahat-GhesarzohaSharhTin.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Ahzab_Iraq_1957_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ahzab_Iraq_1957_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ahzab_Iraq_1957_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ahzab_Iraq_1957_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//ahzab-qiama_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ahzab-qiama_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/ahzab-qiama_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/ahzab-qiama_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Alaq_Qadr_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Alaq_Qadr_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Alaq_Qadr_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Alaq_Qadr_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Anam_v59-79_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Anam_v59-79_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Anam_v59-79_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Anam_v59-79_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Anfal_v23-47_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Anfal_v23-47_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Anfal_v23-47_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Anfal_v23-47_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//15-005-Shahat-Taha98-114.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>15- 005 - SHAHAT - TAHA 98-114 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/15-005-Shahat-Taha98-114.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/15-005-Shahat-Taha98-114.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Anfal_v_22-48_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Anfal_v_22-48_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Anfal_v_22-48_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Anfal_v_22-48_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Bahtimi_surah_Hajj_and_Ismael_surah_Zumar_73-75_Syria_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Bahtimi_surah_Hajj_and_Ismael_surah_Zumar_73-75_Syria_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Bahtimi_surah_Hajj_and_Ismael_surah_Zumar_73-75_Syria_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Bahtimi_surah_Hajj_and_Ismael_surah_Zumar_73-75_Syria_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Baqarah151-158_Shams1-15_Alaq1-191969_Alexandria_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Baqarah(151-158)_Shams(1-15)_'Alaq(1-19)1969_Alexandria_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Baqarah151-158_Shams1-15_Alaq1-191969_Alexandria_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Baqarah151-158_Shams1-15_Alaq1-191969_Alexandria_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//18-006-Shahat-Ghafer7-17.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>18- 006 - SHAHAT - GHAFER 7-17 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/18-006-Shahat-Ghafer7-17.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/18-006-Shahat-Ghafer7-17.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Baqarah_51-73_Iraq_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Baqarah_(51-73)_Iraq_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Baqarah_51-73_Iraq_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Baqarah_51-73_Iraq_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Baqarah_284-286_Aalemran_192-194_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Baqarah_(284-286)_Aalemran_(192-194)_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Baqarah_284-286_Aalemran_192-194_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Baqarah_284-286_Aalemran_192-194_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//boroj-qisar_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>boroj-qisar.wav </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/boroj-qisar_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/boroj-qisar_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Fajr_Balad_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fajr_Balad_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Fajr_Balad_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Fajr_Balad_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li> 
							</ul>	
							<ul id='Part4'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//19-019-Shahat-Nesa135-147.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>19- 019 - SHAHAT - NESA 135-147 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/19-019-Shahat-Nesa135-147.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/19-019-Shahat-Nesa135-147.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//fajr_balad_haqqah_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>fajr_balad_haqqah_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/fajr_balad_haqqah_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/fajr_balad_haqqah_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//fajr_balad_shams_alaq_Alex_1958_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>fajr_balad_shams_alaq_Alex_1958_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/fajr_balad_shams_alaq_Alex_1958_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/fajr_balad_shams_alaq_Alex_1958_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Furqan_58-77_Inshirah_Teen_Masjid_alAqsa_1959_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Furqan_58-77_Inshirah_Teen_Masjid_alAqsa_1959_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Furqan_58-77_Inshirah_Teen_Masjid_alAqsa_1959_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Furqan_58-77_Inshirah_Teen_Masjid_alAqsa_1959_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Furqan_61-77_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Furqan (Q.25 vv.61-77) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Furqan_61-77_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Furqan_61-77_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Furqan_61-77_Tariq_Shams_Fatiha_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Furqan_61-77_Tariq_Shams_Fatiha_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Furqan_61-77_Tariq_Shams_Fatiha_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Furqan_61-77_Tariq_Shams_Fatiha_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Ghashiyah_8-26_Zariat_1-30_Shams_1-8_1977_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ghashiyah_8-26_Zariat_1-30_Shams_1-8_1977_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ghashiyah_8-26_Zariat_1-30_Shams_1-8_1977_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ghashiyah_8-26_Zariat_1-30_Shams_1-8_1977_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hajj_1_36_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hajj_1_36_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hajj_1_36_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hajj_1_36_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hajj_13-29_beginning_verses_missing_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hajj_13-29_beginning_verses_missing_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hajj_13-29_beginning_verses_missing_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hajj_13-29_beginning_verses_missing_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//21-007-Shahat-Fater1-24.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>21- 007 - SHAHAT - FATER 1-24 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/21-007-Shahat-Fater1-24.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/21-007-Shahat-Fater1-24.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hud_25-57_Studio_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hud_25-57_Studio_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hud_25-57_Studio_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hud_25-57_Studio_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hud_26-73_USA_1977_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hud_26-73_USA_1977_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hud_26-73_USA_1977_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hud_26-73_USA_1977_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hujrat_1-10_Qaf_1-11_Masjid_al-Azhar_1955_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hujrat_1-10_Qaf_1-11_Masjid_al-Azhar_1955_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_1-10_Qaf_1-11_Masjid_al-Azhar_1955_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_1-10_Qaf_1-11_Masjid_al-Azhar_1955_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hujrat_13-18_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah al-Hujurat (Q.49 vv.13-18) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13-18_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13-18_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hujrat_13-18_Qaf_1-22_31-45_Haqqah_1-12_Naziat_26-33_Shams_Alexandria_1963_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hujrat_13-18_Qaf_1-22_31-45_Haqqah_1-12_Naziat_26-33_Shams_Alexandria_1963_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13-18_Qaf_1-22_31-45_Haqqah_1-12_Naziat_26-33_Shams_Alexandria_1963_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13-18_Qaf_1-22_31-45_Haqqah_1-12_Naziat_26-33_Shams_Alexandria_1963_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//22-007-Shahat-Ghamar49-endRahman1-30BaladKosarKaferoun.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>22- 007 - SHAHAT - GHAMAR 49-END & RAHMAN 1-30 & BALAD & KOSAR & KAFEROUN </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/22-007-Shahat-Ghamar49-endRahman1-30BaladKosarKaferoun.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/22-007-Shahat-Ghamar49-endRahman1-30BaladKosarKaferoun.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hujrat_13-18_Qaf_1-22_Haqqah_1-24_1950_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hujrat_13-18_Qaf_1-22_Haqqah_1-24_1950_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13-18_Qaf_1-22_Haqqah_1-24_1950_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13-18_Qaf_1-22_Haqqah_1-24_1950_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hujrat_13-18_Qaf_1-22_Haqqah_1-24_Naziat_26-33_Shams_1-8_Alexandria_1957_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hujrat_13-18_Qaf_1-22_Haqqah_1-24_Naziat_26-33_Shams_1-8_Alexandria_1957_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13-18_Qaf_1-22_Haqqah_1-24_Naziat_26-33_Shams_1-8_Alexandria_1957_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13-18_Qaf_1-22_Haqqah_1-24_Naziat_26-33_Shams_1-8_Alexandria_1957_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hujrat_13_18_Qaf_1-15_31-45_Tariq_Ghashiyah_8-26_Ikhlas_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hujrat_13_18_Qaf_1-15_31-45_Tariq_Ghashiyah_8-26_Ikhlas_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13_18_Qaf_1-15_31-45_Tariq_Ghashiyah_8-26_Ikhlas_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_13_18_Qaf_1-15_31-45_Tariq_Ghashiyah_8-26_Ikhlas_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Hujrat_Qaf_1-7_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hujrat_Qaf_1-7_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_Qaf_1-7_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Hujrat_Qaf_1-7_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//25-008-Shahat-Fath27-endHojorat1-18.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>25- 008 - SHAHAT - FATH 27-END & HOJORAT 1-18 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/25-008-Shahat-Fath27-endHojorat1-18.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/25-008-Shahat-Fath27-endHojorat1-18.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Ibrahim_12-41_Alexandria_1965_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim_12-41_Alexandria_1965_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ibrahim_12-41_Alexandria_1965_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ibrahim_12-41_Alexandria_1965_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Ibrahim_23-34_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim_23-34_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ibrahim_23-34_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ibrahim_23-34_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Ibrahim_23-41_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim_23-41_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ibrahim_23-41_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Ibrahim_23-41_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Isra_1-14_1978_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Isra_1-14_1978_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-14_1978_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-14_1978_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Isra_1-22_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Isra_1-22_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-22_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-22_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Isra_1-29_Qadr_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Isra_1-29_Qadr_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-29_Qadr_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-29_Qadr_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//26-008-Shahat-Kahf13-26.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>26- 008 - SHAHAT - KAHF 13-26 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/26-008-Shahat-Kahf13-26.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/26-008-Shahat-Kahf13-26.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Isra_1-36_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ISRA 1 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-36_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-36_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Isra_1-40_studio_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Isra_1-40_studio_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-40_studio_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_1-40_studio_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Isra_6-19_Farooq_Palace_with_introduction_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Isra_6-19_Farooq_Palace_with_introduction_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_6-19_Farooq_Palace_with_introduction_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_6-19_Farooq_Palace_with_introduction_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Isra_15-22_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Isra_15-22_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_15-22_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Isra_15-22_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li> 
							</ul>	
							<ul id='Part5'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Kahf_13-31_Alex_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÓæÑÉ ÇáßåÝ-ÇáÔíÎ ãÕØÝì </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-31_Alex_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-31_Alex_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Kahf_13-31_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Kahf_13-31_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-31_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-31_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Kahf_13-31_Duha_Inshirah_Teen_1-6_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Kahf_13-31_Duha_Inshirah_Teen_1-6_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-31_Duha_Inshirah_Teen_1-6_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-31_Duha_Inshirah_Teen_1-6_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//29-009-Shahat-Foselat30-47.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>29- 009 - SHAHAT - FOSELAT 30-47 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/29-009-Shahat-Foselat30-47.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/29-009-Shahat-Foselat30-47.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Kahf_13-31_Masjid_al-Azhar_with_introduction_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Kahf_13-31_Masjid_al-Azhar_with_introduction_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-31_Masjid_al-Azhar_with_introduction_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-31_Masjid_al-Azhar_with_introduction_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//kahf_13-32_Alaq_1-5_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>kahf_13-32_Alaq_1-5_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/kahf_13-32_Alaq_1-5_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/kahf_13-32_Alaq_1-5_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Kahf_13-34_Jamal_Naser_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Kahf_13-34_Jamal_Naser_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-34_Jamal_Naser_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-34_Jamal_Naser_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Kahf_13-35_Naziat_26-46_Azan_other_qassas_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Kahf_13-35_Naziat_26-46_Azan_other_qassas_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-35_Naziat_26-46_Azan_other_qassas_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_13-35_Naziat_26-46_Azan_other_qassas_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Kahf_17-34_Dimyat_City_1978_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Kahf_17-34_Dimyat_City_1978_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_17-34_Dimyat_City_1978_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_17-34_Dimyat_City_1978_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Kahf_23-38_107-110_Masjid_alAqsa_1957_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Kahf_23-38_107-110_Masjid_alAqsa_1957_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_23-38_107-110_Masjid_alAqsa_1957_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Kahf_23-38_107-110_Masjid_alAqsa_1957_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Luqman_1-34_bad_quality_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>áÞãÇä </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Luqman_1-34_bad_quality_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Luqman_1-34_bad_quality_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Maidah109-120_Rahma…ams_Duha_Inshirah_Fatihah_Baqarah_1-5_Alexandria_1964_low_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maidah(109-120)_Rahman(1-28)_Shams_Duha_Inshirah_Fatihah_Baqarah_1-5_Alexandria_1964_low_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Maidah109-120_Rahman…ams_Duha_Inshirah_Fatihah_Baqarah_1-5_Alexandria_1964_low_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Maidah109-120_Rahman…ams_Duha_Inshirah_Fatihah_Baqarah_1-5_Alexandria_1964_low_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Maryam_12-36_2nd_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maryam_12-36_2nd_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Maryam_12-36_2nd_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Maryam_12-36_2nd_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Maryam_12-36_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maryam_12-36_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Maryam_12-36_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Maryam_12-36_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//mustafa_ad_Duha_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah ad-Duha (Q.93) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/mustafa_ad_Duha_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/mustafa_ad_Duha_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//30-009-Shahat-Kahf13-31.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>30- 009 - SHAHAT - KAHF 13-31 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/30-009-Shahat-Kahf13-31.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/30-009-Shahat-Kahf13-31.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nahl_1-32_64-71_77-82_89_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nahl_1-32_64-71_77-82_89_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_1-32_64-71_77-82_89_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_1-32_64-71_77-82_89_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nahl_1-32_65-74_AbuAlaa_Masjid_1954_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nahl_1-32_65-74_AbuAlaa_Masjid_1954_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_1-32_65-74_AbuAlaa_Masjid_1954_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_1-32_65-74_AbuAlaa_Masjid_1954_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nahl_1-32_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáäÍá </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_1-32_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_1-32_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//34-010-Shahat-Ghaf37-endShams.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>34- 010 - SHAHAT - GHAF37-END & SHAMS </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/34-010-Shahat-Ghaf37-endShams.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/34-010-Shahat-Ghaf37-endShams.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nahl_111-128_Isra_1_studio_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nahl_111-128_Isra_1_studio_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_111-128_Isra_1_studio_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_111-128_Isra_1_studio_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nahl_113-128_studio_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nahl_113-128_studio_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_113-128_studio_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nahl_113-128_studio_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Najm_26-62_Qamar_1-18_Naziat_15-33_Turkey_1961_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáäÌã ÊÑßíÇ </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_26-62_Qamar_1-18_Naziat_15-33_Turkey_1961_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_26-62_Qamar_1-18_Naziat_15-33_Turkey_1961_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Najm_31-62_Qamar_1-15_Naziat_26-46_Tariq_Inshirah_Libya_1974_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Najm_31-62_Qamar_1-15_Naziat_26-46_Tariq_Inshirah_Libya_1974_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-15_Naziat_26-46_Tariq_Inshirah_Libya_1974_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-15_Naziat_26-46_Tariq_Inshirah_Libya_1974_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Najm_31-62_Qamar_1-16_54-55_Rahman_1-14_Aqsa_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Najm_31-62_Qamar_1-16_54-55_Rahman_1-14_Aqsa_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-16_54-55_Rahman_1-14_Aqsa_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-16_54-55_Rahman_1-14_Aqsa_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//36-010-Shahat-Kahf107-endShamsZohaZelzalTakasor.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>36- 010 - SHAHAT - KAHF 107-END & SHAMS & ZOHA & ZELZAL & TAKASOR </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/36-010-Shahat-Kahf107-endShamsZohaZelzalTakasor.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/36-010-Shahat-Kahf107-endShamsZohaZelzalTakasor.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Najm_31-62_Qamar_1-…an_1-27_Haqqah_1-24_Naziat_26-41_Shams_1-8_Dua_Syria_1957_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Najm_31-62_Qamar_1-16_54-55_Rahman_1-27_Haqqah_1-24_Naziat_26-41_Shams_1-8_Dua_Syria_1957_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-1…an_1-27_Haqqah_1-24_Naziat_26-41_Shams_1-8_Dua_Syria_1957_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-1…an_1-27_Haqqah_1-24_Naziat_26-41_Shams_1-8_Dua_Syria_1957_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Najm_31-62_Qamar_1-16_Rahman_1-11_Haqqah_1-12_low_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Najm_31-62_Qamar_1-16_Rahman_1-11_Haqqah_1-12_low_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-16_Rahman_1-11_Haqqah_1-12_low_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-16_Rahman_1-11_Haqqah_1-12_low_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Najm_31-62_Qamar_1-16_Shams_Ikhlas_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Najm_31-62_Qamar_1-16_Shams_Ikhlas_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-16_Shams_Ikhlas_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Najm_31-62_Qamar_1-16_Shams_Ikhlas_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Naml_15-42_Masjid_al-Umawi_1957_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Naml_15-42_Masjid_al-Umawi_1957_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naml_15-42_Masjid_al-Umawi_1957_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naml_15-42_Masjid_al-Umawi_1957_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Naml_15-44_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Naml_15-44_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naml_15-44_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naml_15-44_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Naziat_15-41_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Naziat_15-41_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naziat_15-41_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naziat_15-41_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Naziat_15-46_2nd_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Naziat_15-46_2nd_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naziat_15-46_2nd_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naziat_15-46_2nd_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Naziat_15-46_By.Dr.Kenawy.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Naziat_15-46_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naziat_15-46_By.Dr.Kenawy.MP3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naziat_15-46_By.Dr.Kenawy.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//39-19-006-Shahat-Ghamar49-endRahman1-34ghoraish.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>39- 19- 006 - SHAHAT - GHAMAR 49-END & RAHMAN 1-34&GHORAISH </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/39-19-006-Shahat-Ghamar49-endRahman1-34ghoraish.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/39-19-006-Shahat-Ghamar49-endRahman1-34ghoraish.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Naziat_15-46_Infitar_Masjid_Aqsa_1967_with_introduction_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Naziat_15-46_Infitar_Masjid_Aqsa_1967_with_introduction_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naziat_15-46_Infitar_Masjid_Aqsa_1967_with_introduction_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Naziat_15-46_Infitar_Masjid_Aqsa_1967_with_introduction_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nisa163-172_Gashiyah8-26_Duha_Inshirah_Tin_Alaq_Fatiha_Alexandria_1969_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nisa(163-172)_Gashiyah(8-26)_Duha_Inshirah_Tin_Alaq_Fatiha_Alexandria_1969_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa163-172_Gashiyah8-26_Duha_Inshirah_Tin_Alaq_Fatiha_Alexandria_1969_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa163-172_Gashiyah8-26_Duha_Inshirah_Tin_Alaq_Fatiha_Alexandria_1969_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nisa_64-85_1947_RoyalPalace_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nisa_64-85_1947_RoyalPalace_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa_64-85_1947_RoyalPalace_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa_64-85_1947_RoyalPalace_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//40-011-Shahat-Ghesarborouj11-endBaladZohaSharhTinGhoraish.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>40- 011 - SHAHAT - GHESAR (BOROUJ 11-END & BALAD & ZOHA & SHARH & TIN & GHORAISH) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/40-011-Shahat-Ghesarborouj11-endBaladZohaSharhTinGhoraish.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/40-011-Shahat-Ghesarborouj11-endBaladZohaSharhTinGhoraish.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nisa_64-87_1965_Bulaq_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nisa_64-87_1965_Bulaq_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa_64-87_1965_Bulaq_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa_64-87_1965_Bulaq_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nisa_64_87_Jamal_Abdul_Naser_death_Cairo_1970_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáÔíÎ ãÕØÝì ÇÓãÇÚíá </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa_64_87_Jamal_Abdul_Naser_death_Cairo_1970_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa_64_87_Jamal_Abdul_Naser_death_Cairo_1970_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Nisa_69_85_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nisa_69_85_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa_69_85_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Nisa_69_85_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Qaf_31-45_Haqqah_1-…46_Shams_1_Fajr_27-30_Balad_Shams_Alaq_1-5_Dua_Tanah_1978_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qaf_31-45_Haqqah_1-24_Naziat_26-46_Shams_1_Fajr_27-30_Balad_Shams_Alaq_1-5_Dua_Tanah_1978_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qaf_31-45_Haqqah_1-2…46_Shams_1_Fajr_27-30_Balad_Shams_Alaq_1-5_Dua_Tanah_1978_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qaf_31-45_Haqqah_1-2…46_Shams_1_Fajr_27-30_Balad_Shams_Alaq_1-5_Dua_Tanah_1978_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//42-011-Shahat-Maede20-47.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>42- 011 - SHAHAT - MAEDE 20-47 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/42-011-Shahat-Maede20-47.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/42-011-Shahat-Maede20-47.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Qamar_49-55_Rahman_1-28_Ghashiyah_AlAqsa_1967_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qamar_49-55_Rahman_1-28_Ghashiyah_AlAqsa_1967_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qamar_49-55_Rahman_1-28_Ghashiyah_AlAqsa_1967_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qamar_49-55_Rahman_1-28_Ghashiyah_AlAqsa_1967_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Qassas_3-25_Rahman_1-18_Dua_Lebanon_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇÎÑ Çáäãá æ ÇáÞÕÕ æ ÇáÑÍãä áÈä </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_3-25_Rahman_1-18_Dua_Lebanon_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_3-25_Rahman_1-18_Dua_Lebanon_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Qassas_3-28_Amin_Saeed_1958_Excellent_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qassas_3-28_Amin_Saeed_1958_Excellent_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_3-28_Amin_Saeed_1958_Excellent_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_3-28_Amin_Saeed_1958_Excellent_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Qassas_5-25_Tariq_Ikhlas_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qassas_5-25_Tariq_Ikhlas_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-25_Tariq_Ikhlas_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-25_Tariq_Ikhlas_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Qassas_5-28_Haqqah_1-24_Duha_Inshirah_Birth_Hasan_Anwar_1952_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qassas_5-28_Haqqah_1-24_Duha_Inshirah_Birth_Hasan_Anwar_1952_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-28_Haqqah_1-24_Duha_Inshirah_Birth_Hasan_Anwar_1952_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-28_Haqqah_1-24_Duha_Inshirah_Birth_Hasan_Anwar_1952_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Qassas_5-28_Libya_1974_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qassas_5-28_Libya_1974_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-28_Libya_1974_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-28_Libya_1974_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Qassas_5-28_Qadr_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáÞÕÕ - ÇáÞÏÑ </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-28_Qadr_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-28_Qadr_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//44-012-Shahat-Ghesarzelzal-nasHamdBaghare1-5.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>44- 012 - SHAHAT - GHESAR (ZELZAL-NAS & HAMD & BAGHARE 1-5) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/44-012-Shahat-Ghesarzelzal-nasHamdBaghare1-5.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/44-012-Shahat-Ghesarzelzal-nasHamdBaghare1-5.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Qassas_5-28_Shams_Baghdad_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qassas_5-28_Shams_Baghdad_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-28_Shams_Baghdad_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Qassas_5-28_Shams_Baghdad_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//46-012-Shahat-Maede111-end.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>46- 012 - SHAHAT - MAEDE 111-END </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/46-012-Shahat-Maede111-end.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/46-012-Shahat-Maede111-end.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Rad_1-14_Duha_Inshirah_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Rad_1-14_Duha_Inshirah_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Rad_1-14_Duha_Inshirah_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Rad_1-14_Duha_Inshirah_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Taha_83-123_Iran_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Øå ÇíÑÇä </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Taha_83-123_Iran_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Taha_83-123_Iran_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Taha_83-123_Iran_without_audience_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Taha_83-123_Iran_without_audience_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Taha_83-123_Iran_without_audience_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Taha_83-123_Iran_without_audience_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Yusuf_4-31_Masjid_Sultan_Abul-Ala_1965_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf_4-31_Masjid_Sultan_Abul-Ala_1965_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Yusuf_4-31_Masjid_Sultan_Abul-Ala_1965_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Yusuf_4-31_Masjid_Sultan_Abul-Ala_1965_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//Yusuf_7-22_By.Dr.Kenawy.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf_7-22_By.Dr.Kenawy </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/Yusuf_7-22_By.Dr.Kenawy.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/Yusuf_7-22_By.Dr.Kenawy.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//48-013-Shahat-GhesarzohaSharhTinAlaghGhadrBayenaZelzalAdiyat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>48- 013 - SHAHAT - GHESAR (ZOHA & SHARH & TIN & ALAGH & GHADR & BAYENA & ZELZAL & ADIYAT) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/48-013-Shahat-GhesarzohaSharhTinAlaghGhadrBayenaZelzalAdiyat.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/48-013-Shahat-GhesarzohaSharhTinAlaghGhadrBayenaZelzalAdiyat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//49-013-Shahat-Maede109-enda.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>49- 013 - SHAHAT - MAEDE 109-END (A) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/49-013-Shahat-Maede109-enda.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/49-013-Shahat-Maede109-enda.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//52-014-Shahat-Ghesargharea-nasHamdBaghare1-2.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>52- 014 - SHAHAT - GHESAR (GHAREA-NAS & HAMD & BAGHARE 1-2) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/52-014-Shahat-Ghesargharea-nasHamdBaghare1-2.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/52-014-Shahat-Ghesargharea-nasHamdBaghare1-2.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//53-014-Shahat-Maede109-endb.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>53- 014 - SHAHAT - MAEDE 109-END (B) </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/53-014-Shahat-Maede109-endb.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/53-014-Shahat-Maede109-endb.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//56-015-Shahat-Ghasas1-21.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>56- 015 - SHAHAT - GHASAS 1-21 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/56-015-Shahat-Ghasas1-21.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/56-015-Shahat-Ghasas1-21.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//57-015-Shahat-Maryam1-36.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>57- 015 - SHAHAT - MARYAM 1-36 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/57-015-Shahat-Maryam1-36.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/57-015-Shahat-Maryam1-36.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//60-016-Shahat-Ghasas1-25.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>60- 016 - SHAHAT - GHASAS 1-25 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/60-016-Shahat-Ghasas1-25.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/60-016-Shahat-Ghasas1-25.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//61-016-Shahat-Nahl125-endAsra1-17.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>61- 016 - SHAHAT - NAHL 125-END & ASRA 1-17 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/61-016-Shahat-Nahl125-endAsra1-17.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/61-016-Shahat-Nahl125-endAsra1-17.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//65-017-Shahat-Ghasas82-endEnfetarGhoraishKosar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>65- 017 - SHAHAT - GHASAS 82-END & ENFETAR & GHORAISH & KOSAR </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/65-017-Shahat-Ghasas82-endEnfetarGhoraishKosar.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/65-017-Shahat-Ghasas82-endEnfetarGhoraishKosar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//66-017-Shahat-Nesa1-19.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>66- 017 - SHAHAT - NESA 1-19 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/66-017-Shahat-Nesa1-19.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/66-017-Shahat-Nesa1-19.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/ShahatMohammedAnwarQuran2//67-018-Shahat-Ghalam49-endHagha16-endMaarej1-18.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>67- 018 - SHAHAT - GHALAM 49-END & HAGHA 16-END & MAAREJ 1-18 </a><a class='dlink' href=' https://archive.org/download/ShahatMohammedAnwarQuran2/67-018-Shahat-Ghalam49-endHagha16-endMaarej1-18.mp3' data-dlink=' https://archive.org/download/ShahatMohammedAnwarQuran2/67-018-Shahat-Ghalam49-endHagha16-endMaarej1-18.mp3'><img src='media/data/dlink.png' alt = ''/></a></li> 
							</ul> 
					</div>
			</div>
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>
			
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div>  	
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>Sheikh Qari Shahat Muhammad Anwar [RA] <br>
					Sheikh Qari Anwar Shahat<br>
					Sheikh Qari Mahmood Shahat<br><br>

					الزعيم القرآء القارئ الشيخ الشحات محمد انور رحمه الله<br>
					امير قرآء العالم القارئ الشيخ انور الشحات محمد انور<br>
					برنس القرآء القارئ الشيخ محمود الشحات محمد انور</p>
					
					<p><span >Shahat Muhammad Anwar is known to have played a major role in improving the technical and artistic aspects of Quran recitation and attracting a large number of the youth to the Holy Book.The Sheikh Mohamed Anwar Shehata is a Quran recitor from the Imam Rafi&icirc;i mosque; He was born on the 1st of July in 1950 in Kaffar Al Wazzir village, the centre of Mayit Ghamr in Addiqhaliya province. He was born in Egypt.</span><br  />
					<span >How he recites</span><br  />
					<span >His serene tone along with his mastery over the rules of music as well as his occasional use of Iranian melodies in his recitations are the main reasons of his popularity in Islamic world.</span><br  />
					<span >Although Mohammad Anwar is not believed to have an individual style, his unique innovations in reciting the Holy Quran have introduced him as an eminent Quran reciter.</span><br  />
					<span >Conclusion</span><br  />
					<span >Sheikh Shahat Mohammad Anwar is still remembered as one of the most influential Quran reciters whose sad demise in 2007 left the Islamic world in great mourning over his irreparable loss.</span><br  />
					<span >Influences</span><br  />
					<span >Following the great Quran reciters, Master Abdul-Baset, Mohammad Abdul-Samad, Mohammad Seddigh Menshawi and Mustafa Esmaeel, Mohammad Anwar is believed to be the most influential reciter. His uncle adopted him and taught him The Quran. He finished the learning of the latter at the age of 8.</span><br  />
					<span >By the age of ten, he went with his uncle to Kaffer Al Miqddam village where he learned about Tajwid thanks to Sheikh Ahmed Al Farraji. Then, he became a famous Quran recitor in the neighbouring villages like Al Wajh Al Bahri. He used to earn some money for his recitation (quarter of Junnayh).</span></p>
				</div>  	
			</div>
			 	

</div>

 		  		
		
<?php  include $path . '/pages/footer.php'; ?>
 


 
