<?php  
	$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div>  	 
		    <div class="row reciter-container">	  
				<div class=" archive-playlist-title">
									<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
				</div>
				<div class="row btns-player-catagory">  
					<a href='#' class="btn  btn-success " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#playlist1'}); return false;"><i class="fa fa-book"></i> Part 1</a>	  
					<a href='#' class=" btn   " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#Part2'}); return false;"><i class="fa fa-book"></i> Part 2</a>
					
					<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#Part3'}); return false;"><i class="fa fa-book"></i> Part 3</a> 
					 
					
					<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#clear'}); return false;"><i class="fa fa-book"></i> Clear</a>
					 
					<script>
						$(function() {
						  $('.btn').click( function() {
							$(this).addClass('btn-success').siblings().removeClass('btn-success');
						  });
						});
					</script>
				</div>
				<?php  include $path . '/player/player_code.php';     ?> 
			
				<div id="playlist_list">
				<!-- local playlist -->
					<ul id='clear'> 
					
					</ul>
					<ul id='playlist1'> 
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1431H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة الفاتحة (2010 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1431H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1431H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1428H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة الفاتحة (2007 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1428H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1428H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1430H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>[سورة الفاتحة (2009) [من صلاة الخسوف </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1430H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1430H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//002-Abdulwali_Al-Arkani_-_Surah_Al-Baqara.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة البقرة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/002-Abdulwali_Al-Arkani_-_Surah_Al-Baqara.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/002-Abdulwali_Al-Arkani_-_Surah_Al-Baqara.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//003-Abdulwali_Al-Arkani_-_Al-Imran.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة آل عمران </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/003-Abdulwali_Al-Arkani_-_Al-Imran.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/003-Abdulwali_Al-Arkani_-_Al-Imran.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//007-Abdulwali_Al-Arkani_-_Al-Araf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الأعراف </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/007-Abdulwali_Al-Arkani_-_Al-Araf.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/007-Abdulwali_Al-Arkani_-_Al-Araf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//008-Abdulwali_Al-Arkani_-_Al-Anfal_1431H.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الأنفال </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/008-Abdulwali_Al-Arkani_-_Al-Anfal_1431H.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/008-Abdulwali_Al-Arkani_-_Al-Anfal_1431H.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//012-Abdulwali_Al-Arkani_-_Yusuf.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة يوسف </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/012-Abdulwali_Al-Arkani_-_Yusuf.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/012-Abdulwali_Al-Arkani_-_Yusuf.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//014-Abdulwali_Al-Arkani_-_Ibrahim.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة إبراهيم </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/014-Abdulwali_Al-Arkani_-_Ibrahim.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/014-Abdulwali_Al-Arkani_-_Ibrahim.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
					</ul>
					<ul id='Part2'> 
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//015-Abdulwali_Al-Arkani_-_Al-Hijr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الحجر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/015-Abdulwali_Al-Arkani_-_Al-Hijr.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/015-Abdulwali_Al-Arkani_-_Al-Hijr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//016-Abdulwali_Al-Arkani_-_Surah_An-Nahl_1426H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة النحل </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/016-Abdulwali_Al-Arkani_-_Surah_An-Nahl_1426H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/016-Abdulwali_Al-Arkani_-_Surah_An-Nahl_1426H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//017-Abdulwali_Al-Arkani_-_Al-Isra.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الإسراء </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/017-Abdulwali_Al-Arkani_-_Al-Isra.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/017-Abdulwali_Al-Arkani_-_Al-Isra.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//019-Abdulwali_Al-Arkani_-_Surah_Maryam_1426H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة مريم </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/019-Abdulwali_Al-Arkani_-_Surah_Maryam_1426H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/019-Abdulwali_Al-Arkani_-_Surah_Maryam_1426H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//020-Abdulwali_Al-Arkani_-_Taha.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة طه </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/020-Abdulwali_Al-Arkani_-_Taha.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/020-Abdulwali_Al-Arkani_-_Taha.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//031-Abdulwali_Al-Arkani_-_Luqman_2008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة لقمان (2008 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_Luqman_2008.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_Luqman_2008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//032-Abdulwali_Al-Arkani_-_As-Sajdah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة السجدة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/032-Abdulwali_Al-Arkani_-_As-Sajdah.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/032-Abdulwali_Al-Arkani_-_As-Sajdah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//036-Abdulwali_Al-Arkani_-_Ya-Seen_2008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة يس (2008 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/036-Abdulwali_Al-Arkani_-_Ya-Seen_2008.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/036-Abdulwali_Al-Arkani_-_Ya-Seen_2008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//037-Abdulwali_Al-Arkani_-_As-Saffat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الصافات </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/037-Abdulwali_Al-Arkani_-_As-Saffat.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/037-Abdulwali_Al-Arkani_-_As-Saffat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//039-Abdulwali_Al-Arkani_-_Surah_Az-Zumar_2008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة الزمر (2008 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_Surah_Az-Zumar_2008.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_Surah_Az-Zumar_2008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//040-Abdulwali_Al-Arkani_-_Gafir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة غافر (2009 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/040-Abdulwali_Al-Arkani_-_Gafir.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/040-Abdulwali_Al-Arkani_-_Gafir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//044-Abdulwali_Al-Arkani_-_Ad-Dukhan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الدخان </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/044-Abdulwali_Al-Arkani_-_Ad-Dukhan.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/044-Abdulwali_Al-Arkani_-_Ad-Dukhan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//049-Abdulwali_Al-Arkani_-_Al-Hujurat_2011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة الحجرات (2011 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/049-Abdulwali_Al-Arkani_-_Al-Hujurat_2011.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/049-Abdulwali_Al-Arkani_-_Al-Hujurat_2011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//050-Abdulwali_Al-Arkani_-_Qaf_2011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة ق </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/050-Abdulwali_Al-Arkani_-_Qaf_2011.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/050-Abdulwali_Al-Arkani_-_Qaf_2011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//052-Abdulwali_Al-Arkani_-_At-Toor.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الطور </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/052-Abdulwali_Al-Arkani_-_At-Toor.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/052-Abdulwali_Al-Arkani_-_At-Toor.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//053-Abdulwali_Al-Arkani_-_An-Najm.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة النجم </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/053-Abdulwali_Al-Arkani_-_An-Najm.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/053-Abdulwali_Al-Arkani_-_An-Najm.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//055-Abdulwali_Al-Arkani_-_Ar-Rahman_2008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة الرحمن (2008 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/055-Abdulwali_Al-Arkani_-_Ar-Rahman_2008.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/055-Abdulwali_Al-Arkani_-_Ar-Rahman_2008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//056-Abdulwali_Al-Arkani_-_Al-Waqiah_2008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة الواقعة (2008 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/056-Abdulwali_Al-Arkani_-_Al-Waqiah_2008.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/056-Abdulwali_Al-Arkani_-_Al-Waqiah_2008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//056-Abdulwali_Al-Arkani_-_Al-Waqiah_2009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>[عبد الولي الأركاني - سورة الواقعة (2009) [من صلاة الخسوف </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/056-Abdulwali_Al-Arkani_-_Al-Waqiah_2009.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/056-Abdulwali_Al-Arkani_-_Al-Waqiah_2009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//075-Abdulwali_Al-Arkani_-_Al-Qiyamah_2011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة القيامة (2011 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Al-Qiyamah_2011.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Al-Qiyamah_2011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//000-Abdulwali_Al-Arkani_-_Athan_2011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - الأذان (2011 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/000-Abdulwali_Al-Arkani_-_Athan_2011.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/000-Abdulwali_Al-Arkani_-_Athan_2011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//078-Abdulwali_Al-Arkani_-_An-Nba_2009_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>[عبد الولي الأركاني - سورة النبأ (2009) [من صلاة الخسوف </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_An-Nba_2009_.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_An-Nba_2009_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//078-Abdulwali_Al-Arkani_-_An-Nba_2009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة النبأ (2009 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_An-Nba_2009.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_An-Nba_2009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//078-Abdulwali_Al-Arkani_-_An-Nba_2010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة النبأ (2010 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_An-Nba_2010.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_An-Nba_2010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//078-Abdulwali_Al-Arkani_-_An-Nba_2011.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة النبأ (2011 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_An-Nba_2011.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_An-Nba_2011.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//079-Abdulwali_Al-Arkani_-_An-Naziat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة النازعات </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/079-Abdulwali_Al-Arkani_-_An-Naziat.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/079-Abdulwali_Al-Arkani_-_An-Naziat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//080-Abdulwali_Al-Arkani_-_Abasa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة عبس </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/080-Abdulwali_Al-Arkani_-_Abasa.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/080-Abdulwali_Al-Arkani_-_Abasa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//081-Abdulwali_Al-Arkani_-_At-Takweer.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة التكوير </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/081-Abdulwali_Al-Arkani_-_At-Takweer.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/081-Abdulwali_Al-Arkani_-_At-Takweer.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//082-Abdulwali_Al-Arkani_-_Al-Infitar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الإنفطار </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/082-Abdulwali_Al-Arkani_-_Al-Infitar.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/082-Abdulwali_Al-Arkani_-_Al-Infitar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//088-Abdulwali_Al-Arkani_-_Al-Gashiah.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الغاشية </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/088-Abdulwali_Al-Arkani_-_Al-Gashiah.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/088-Abdulwali_Al-Arkani_-_Al-Gashiah.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//089-Abdulwali_Al-Arkani_-_Al-Fajr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الفجر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/089-Abdulwali_Al-Arkani_-_Al-Fajr.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/089-Abdulwali_Al-Arkani_-_Al-Fajr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//090-Abdulwali_Al-Arkani_-_Al-Balad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة البلد </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/090-Abdulwali_Al-Arkani_-_Al-Balad.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/090-Abdulwali_Al-Arkani_-_Al-Balad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//102-Abdulwali_Al-Arkani_-_At-Takathur.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة التكاثر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/102-Abdulwali_Al-Arkani_-_At-Takathur.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/102-Abdulwali_Al-Arkani_-_At-Takathur.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//112-Abdulwali_Al-Arkani_-_Al-Ikhlas.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة الإخلاص </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/112-Abdulwali_Al-Arkani_-_Al-Ikhlas.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/112-Abdulwali_Al-Arkani_-_Al-Ikhlas.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//000-Abdulwali_Al-Arkani_-_Athan_2008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - الأذان (2008 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/000-Abdulwali_Al-Arkani_-_Athan_2008.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/000-Abdulwali_Al-Arkani_-_Athan_2008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//101-Abdulwali_Al-Arkani_-_Al-Qariah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة القارعة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/101-Abdulwali_Al-Arkani_-_Al-Qariah.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/101-Abdulwali_Al-Arkani_-_Al-Qariah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//115-Abdulwali_Al-Arkani_-_Doa_2010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - دعاء تراويح (2010 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/115-Abdulwali_Al-Arkani_-_Doa_2010.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/115-Abdulwali_Al-Arkani_-_Doa_2010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//031-Abdulwali_Al-Arkani_-_Luqman_2007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة لقمان (2007 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_Luqman_2007.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_Luqman_2007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//036-Abdulwali_Al-Arkani_-_Ya-Seen_2007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة يس (2007 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/036-Abdulwali_Al-Arkani_-_Ya-Seen_2007.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/036-Abdulwali_Al-Arkani_-_Ya-Seen_2007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//055-Abdulwali_Al-Arkani_-_Ar-Rahman_2007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة الرحمن (2007 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/055-Abdulwali_Al-Arkani_-_Ar-Rahman_2007.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/055-Abdulwali_Al-Arkani_-_Ar-Rahman_2007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//056-Abdulwali_Al-Arkani_-_Al-Waqiah_2007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة الواقعة (2007 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/056-Abdulwali_Al-Arkani_-_Al-Waqiah_2007.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/056-Abdulwali_Al-Arkani_-_Al-Waqiah_2007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//039-Abdulwali_Al-Arkani_-_Surah_Az-Zumar_2007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>(عبد الولي الأركاني - سورة الزمر (2007 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_Surah_Az-Zumar_2007.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_Surah_Az-Zumar_2007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//034-Abdulwali_Al-Arkani_-_Saba.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>عبد الولي الأركاني - سورة سبأ </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/034-Abdulwali_Al-Arkani_-_Saba.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/034-Abdulwali_Al-Arkani_-_Saba.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//049-Abdulwali_Al-Arkani_-_Al-Hujurat_2010_from_Bahrain.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>[عبد الولي الأركاني - سورة الحجرات (2010) [من البحرين </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/049-Abdulwali_Al-Arkani_-_Al-Hujurat_2010_from_Bahrain.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/049-Abdulwali_Al-Arkani_-_Al-Hujurat_2010_from_Bahrain.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//051-Abdulwali_Al-arkani_-_Az-Zariyat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>[عبد الولي الأركاني - سورة الذاريات [16\9\1433هـ </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/051-Abdulwali_Al-arkani_-_Az-Zariyat.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/051-Abdulwali_Al-arkani_-_Az-Zariyat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//050-Abdulwali_Al-Arkani_-_Qaf_2012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>[عبد الولي الأركاني - سورة ق [15\9\1433هـ </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/050-Abdulwali_Al-Arkani_-_Qaf_2012.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/050-Abdulwali_Al-Arkani_-_Qaf_2012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//049-Abdulwali_Al-Arkani_-_Al-Hujurat_2012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>[عبد الولي الأركاني - سورة الحجرات [15\9\1433هـ </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/049-Abdulwali_Al-Arkani_-_Al-Hujurat_2012.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/049-Abdulwali_Al-Arkani_-_Al-Hujurat_2012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//052-Abdulwali_Al-Arkani_-_Surah_At-Toor_2012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>[عبد الولي الأركاني - سورة الطور [16\9\1433هـ </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/052-Abdulwali_Al-Arkani_-_Surah_At-Toor_2012.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/052-Abdulwali_Al-Arkani_-_Surah_At-Toor_2012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//021-Abdulwali_Al-Arkani_-_Surah_Al-Anbiya_1431H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anbiya' (The Prophets) الأنبياء </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/021-Abdulwali_Al-Arkani_-_Surah_Al-Anbiya_1431H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/021-Abdulwali_Al-Arkani_-_Surah_Al-Anbiya_1431H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//042-Abdulwali_Al-Arkani_-_Surah_Ash-Shura_1431H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shura (Council) الشورى </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/042-Abdulwali_Al-Arkani_-_Surah_Ash-Shura_1431H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/042-Abdulwali_Al-Arkani_-_Surah_Ash-Shura_1431H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//043-Abdulwali_Al-Arkani_-_Surah_Az-Zukhruf_1431H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zukhruf (Luxury) الزخرف </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/043-Abdulwali_Al-Arkani_-_Surah_Az-Zukhruf_1431H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/043-Abdulwali_Al-Arkani_-_Surah_Az-Zukhruf_1431H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//023-Abdulwali_Al-Arkani_-_Surah_Al-Muminoon_1431H.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mu'minoon (The Believers) المؤمنون </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/023-Abdulwali_Al-Arkani_-_Surah_Al-Muminoon_1431H.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/023-Abdulwali_Al-Arkani_-_Surah_Al-Muminoon_1431H.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//022-Abdulwali_Al-Arkani_-_Surah_Al-Hajj_1431H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hajj (The Pligrimage) الحج </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/022-Abdulwali_Al-Arkani_-_Surah_Al-Hajj_1431H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/022-Abdulwali_Al-Arkani_-_Surah_Al-Hajj_1431H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//002-Abdulwali_Al-Arkani_-_Ayat_Al-Kursi.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ayat Al-Kursi | آية الكرسي </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/002-Abdulwali_Al-Arkani_-_Ayat_Al-Kursi.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/002-Abdulwali_Al-Arkani_-_Ayat_Al-Kursi.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//018-Abdulwali_Al-Arkani_-_Surah_Al-Kahf_1429H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Kahf (The Cave) سورة الكهف </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/018-Abdulwali_Al-Arkani_-_Surah_Al-Kahf_1429H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/018-Abdulwali_Al-Arkani_-_Surah_Al-Kahf_1429H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//019-Abdulwali_Al-Arkani_-_Surah_Maryam_1429H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Maryam | سورة مريم </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/019-Abdulwali_Al-Arkani_-_Surah_Maryam_1429H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/019-Abdulwali_Al-Arkani_-_Surah_Maryam_1429H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1429H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Fatihah | سورة الفاتحة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1429H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_1429H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//039-Abdulwali_Al-Arkani_-_Surah_Az-Zumar_1430H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Az-Zumar (The Troops chapter) سورة الزمر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_Surah_Az-Zumar_1430H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_Surah_Az-Zumar_1430H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//009-Abdulwali_Al-Arkani_-_Surah_At-Taubah_1431H.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taubah (The Repentance) سورة التوبة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/009-Abdulwali_Al-Arkani_-_Surah_At-Taubah_1431H.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/009-Abdulwali_Al-Arkani_-_Surah_At-Taubah_1431H.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//021-Abdulwali_Al-Arkani_-_Surah_Al-Anbiya_1434H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Anbiya' (The Prophets chapter) سورة الأنبياء </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/021-Abdulwali_Al-Arkani_-_Surah_Al-Anbiya_1434H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/021-Abdulwali_Al-Arkani_-_Surah_Al-Anbiya_1434H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//048-Abdulwali_Al-Arkani_-_Surah_Al-Fath_H1434-09-15.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Fath (The Conquest chapter) سورة الفتح </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/048-Abdulwali_Al-Arkani_-_Surah_Al-Fath_H1434-09-15.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/048-Abdulwali_Al-Arkani_-_Surah_Al-Fath_H1434-09-15.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//031-Abdulwali_Al-Arkani_-_A_Clip_of_Surah_Luqman_H1434-09-14.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman | لقمان </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_A_Clip_of_Surah_Luqman_H1434-09-14.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_A_Clip_of_Surah_Luqman_H1434-09-14.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//031-Abdulwali_Al-Arkani_-_Last_Verses_of_Surah_Luqman_H1434-09-14.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman | لقمان </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_Last_Verses_of_Surah_Luqman_H1434-09-14.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_Last_Verses_of_Surah_Luqman_H1434-09-14.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//031-Abdulwali_Al-Arkani_-_Surah_Luqman_H1434-09-14.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman | لقمان </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_Surah_Luqman_H1434-09-14.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/031-Abdulwali_Al-Arkani_-_Surah_Luqman_H1434-09-14.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//048-Abdulwali_Al-Arkani_-_Last_Verses_of_Surah_Al-Fath_H1434-09-15.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Last of Surah Al-Fath (The Conquest chapter) آخر سورة الفتح </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/048-Abdulwali_Al-Arkani_-_Last_Verses_of_Surah_Al-Fath_H1434-09-15.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/048-Abdulwali_Al-Arkani_-_Last_Verses_of_Surah_Al-Fath_H1434-09-15.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//115-Abdulwali_Al-Arkani_-_Dua_Tahajjud_1430H.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Do'a (Supplication) دعاء </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/115-Abdulwali_Al-Arkani_-_Dua_Tahajjud_1430H.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/115-Abdulwali_Al-Arkani_-_Dua_Tahajjud_1430H.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_H1434-09-15.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Fatihah (The Opening chapter) سورة الفاتحة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_H1434-09-15.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/001-Abdulwali_Al-Arkani_-_Surah_Al-Fatihah_H1434-09-15.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//058-Abdulwali_Al-Arkani_-_Surah_Al-Mujadilah_H1434-09-21.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mujadilah (The Pleading Woman chapter) سورة المجادلة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/058-Abdulwali_Al-Arkani_-_Surah_Al-Mujadilah_H1434-09-21.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/058-Abdulwali_Al-Arkani_-_Surah_Al-Mujadilah_H1434-09-21.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//059-Abdulwali_Al-Arkani_-_Surah_Al-Hashr_H1434-09-22.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Hashr (The Exile chapter) سورة الحشر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/059-Abdulwali_Al-Arkani_-_Surah_Al-Hashr_H1434-09-22.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/059-Abdulwali_Al-Arkani_-_Surah_Al-Hashr_H1434-09-22.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//060-Abdulwali_Al-Arkani_-_Surah_Al-Mumtahinah_H1434-09-22.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mumtahinah (Examining Her chapter) سورة الممتحنة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/060-Abdulwali_Al-Arkani_-_Surah_Al-Mumtahinah_H1434-09-22.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/060-Abdulwali_Al-Arkani_-_Surah_Al-Mumtahinah_H1434-09-22.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//061-Abdulwali_Al-Arkani_-_Surah_As-Saff_H1434-09-23.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah As-Saff (The Ranks chapter) سورة الصف </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/061-Abdulwali_Al-Arkani_-_Surah_As-Saff_H1434-09-23.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/061-Abdulwali_Al-Arkani_-_Surah_As-Saff_H1434-09-23.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//062-Abdulwali_Al-Arkani_-_Surah_Al-Jumuah_H1434-09-23.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>062-Abdulwali_Al-Arkani_-_Surah_Al-Jumu'ah_H1434-09-23 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/062-Abdulwali_Al-Arkani_-_Surah_Al-Jumuah_H1434-09-23.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/062-Abdulwali_Al-Arkani_-_Surah_Al-Jumuah_H1434-09-23.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//063-Abdulwali_Al-Arkani_-_Surah_Al-Munafiqoon_H1434-09-23.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Munafiqoon (The Hypocrites chapter) سورة المنافقون </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/063-Abdulwali_Al-Arkani_-_Surah_Al-Munafiqoon_H1434-09-23.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/063-Abdulwali_Al-Arkani_-_Surah_Al-Munafiqoon_H1434-09-23.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//064-Abdulwali_Al-Arkani_-_Surah_At-Taghabun_H1434-09-24.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah At-Taghabun (The Haggling chapter) سورة التغابن </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/064-Abdulwali_Al-Arkani_-_Surah_At-Taghabun_H1434-09-24.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/064-Abdulwali_Al-Arkani_-_Surah_At-Taghabun_H1434-09-24.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//065-Abdulwali_Al-Arkani_-_Surah_At-Talaq_H1434-09-24.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah At-Talaq (The Divorce chapter) سورة الطلاق </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/065-Abdulwali_Al-Arkani_-_Surah_At-Talaq_H1434-09-24.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/065-Abdulwali_Al-Arkani_-_Surah_At-Talaq_H1434-09-24.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//066-Abdulwali_Al-Arkani_-_Surah_At-Tahreem_H1434-09-25.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah At-Tahreem (The Banning chapter) سورة التحريم </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/066-Abdulwali_Al-Arkani_-_Surah_At-Tahreem_H1434-09-25.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/066-Abdulwali_Al-Arkani_-_Surah_At-Tahreem_H1434-09-25.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//067-Abdulwali_Al-Arkani_-_Surah_Al-Mulk_H1434-09-25.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mulk (The Sovereignty chapter) سورة الملك </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/067-Abdulwali_Al-Arkani_-_Surah_Al-Mulk_H1434-09-25.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/067-Abdulwali_Al-Arkani_-_Surah_Al-Mulk_H1434-09-25.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//068-Abdulwali_Al-Arkani_-_Surah_Al-Qalam_H1434-09-25.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qalam (The Pen chapter) سورة القلم </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/068-Abdulwali_Al-Arkani_-_Surah_Al-Qalam_H1434-09-25.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/068-Abdulwali_Al-Arkani_-_Surah_Al-Qalam_H1434-09-25.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//069-Abdulwali_Al-Arkani_-_Surah_Al-Haqqah_H1434-09-26.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Haqqah (The Reality chapter) سورة الحاقة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/069-Abdulwali_Al-Arkani_-_Surah_Al-Haqqah_H1434-09-26.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/069-Abdulwali_Al-Arkani_-_Surah_Al-Haqqah_H1434-09-26.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//070-Abdulwali_Al-Arkani_-_Surah_Al-Maarij_H1434-09-26.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>070-Abdulwali_Al-Arkani_-_Surah_Al-Ma'arij_H1434-09-26 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/070-Abdulwali_Al-Arkani_-_Surah_Al-Maarij_H1434-09-26.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/070-Abdulwali_Al-Arkani_-_Surah_Al-Maarij_H1434-09-26.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//071-Abdulwali_Al-Arkani_-_Surah_Nooh_H1434-09-26.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Nooh (Noah chapter) سورة نوح </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/071-Abdulwali_Al-Arkani_-_Surah_Nooh_H1434-09-26.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/071-Abdulwali_Al-Arkani_-_Surah_Nooh_H1434-09-26.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//072-Abdulwali_Al-Arkani_-_Surah_Al-Jinn_H1434-09-27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Jinn (The Jinn chapter) سورة الجن </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/072-Abdulwali_Al-Arkani_-_Surah_Al-Jinn_H1434-09-27.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/072-Abdulwali_Al-Arkani_-_Surah_Al-Jinn_H1434-09-27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1434-09-17.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Muzzammil (The Enshrouded One chapter) سورة المزمل </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1434-09-17.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1434-09-17.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1434-09-27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Muzzammil (The Enshrouded One chapter) سورة المزمل </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1434-09-27.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1434-09-27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1434-09-17.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Muddaththir (The Cloaked One chapter) سورة المدثر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1434-09-17.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1434-09-17.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1434-09-27.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Muddaththir (The Cloaked One chapter) سورة المدثر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1434-09-27.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1434-09-27.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1434-09-17.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qiyamah (The Ressurection chapter) سورة القيامة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1434-09-17.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1434-09-17.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1434-09-28.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qiyamah (The Ressurection chapter) سورة القيامة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1434-09-28.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1434-09-28.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1434-09-28.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Insan (The Human chapter) سورة الإنسان </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1434-09-28.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1434-09-28.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//077-Abdulwali_Al-Arkani_-_Surah_Al-Murslat_H1434-09-28.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mursalat (The Emissaries chapter) سورة المرسلات </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/077-Abdulwali_Al-Arkani_-_Surah_Al-Murslat_H1434-09-28.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/077-Abdulwali_Al-Arkani_-_Surah_Al-Murslat_H1434-09-28.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//078-Abdulwali_Al-Arkani_-_Surah_An-Naba_H1434-09-29.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>078-Abdulwali_Al-Arkani_-_Surah_An-Naba'_H1434-09-29 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_Surah_An-Naba_H1434-09-29.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/078-Abdulwali_Al-Arkani_-_Surah_An-Naba_H1434-09-29.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//079-Abdulwali_Al-Arkani_-_Surah_An-Naziat_H1434-09-11.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>079-Abdulwali_Al-Arkani_-_Surah_An-Nazi'at_H1434-09-11 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/079-Abdulwali_Al-Arkani_-_Surah_An-Naziat_H1434-09-11.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/079-Abdulwali_Al-Arkani_-_Surah_An-Naziat_H1434-09-11.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//079-Abdulwali_Al-Arkani_-_Surah_An-Naziat_H1434-09-29.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>079-Abdulwali_Al-Arkani_-_Surah_An-Nazi'at_H1434-09-29 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/079-Abdulwali_Al-Arkani_-_Surah_An-Naziat_H1434-09-29.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/079-Abdulwali_Al-Arkani_-_Surah_An-Naziat_H1434-09-29.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//080-Abdulwali_Al-Arkani_-_Surah_Abasa_H1434-09-29.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>080-Abdulwali_Al-Arkani_-_Surah_'Abasa_H1434-09-29 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/080-Abdulwali_Al-Arkani_-_Surah_Abasa_H1434-09-29.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/080-Abdulwali_Al-Arkani_-_Surah_Abasa_H1434-09-29.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//081-Abdulwali_Al-Arkani_-_Surah_At-Takweer_H1434-09-29.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah At-Takweer (The Overthrowing) سورة التكوير </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/081-Abdulwali_Al-Arkani_-_Surah_At-Takweer_H1434-09-29.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/081-Abdulwali_Al-Arkani_-_Surah_At-Takweer_H1434-09-29.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//082-Abdulwali_Al-Arkani_-_Surah_Al-Infitar_H1434-09-08.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Infitar (The Cleaving chapter) سورة الإنفطار </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/082-Abdulwali_Al-Arkani_-_Surah_Al-Infitar_H1434-09-08.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/082-Abdulwali_Al-Arkani_-_Surah_Al-Infitar_H1434-09-08.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//082-Abdulwali_Al-Arkani_-_Surah_Al-Infitar_H1434-09-29.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Infitar (The Cleaving chapter) سورة الإنفطار </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/082-Abdulwali_Al-Arkani_-_Surah_Al-Infitar_H1434-09-29.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/082-Abdulwali_Al-Arkani_-_Surah_Al-Infitar_H1434-09-29.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//083-Abdulwali_Al-Arkani_-_Surah_Al-Mutaffifeen_H1434-09-29.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mutaffifeen (The Defrauding chapter) سورة المطففين </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/083-Abdulwali_Al-Arkani_-_Surah_Al-Mutaffifeen_H1434-09-29.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/083-Abdulwali_Al-Arkani_-_Surah_Al-Mutaffifeen_H1434-09-29.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//085-Abdulwali_Al-Arkani_-_Surah_Al-Borooj_H1434-09-09.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Boroj (The Mansions Of The Stars chapter) سورة البروج </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/085-Abdulwali_Al-Arkani_-_Surah_Al-Borooj_H1434-09-09.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/085-Abdulwali_Al-Arkani_-_Surah_Al-Borooj_H1434-09-09.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//086-Abdulwali_Al-Arkani_-_Surah_At-Tariq_H1434-09-09.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah At-Tariq (The Morning Star chapter) سورة الطارق </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/086-Abdulwali_Al-Arkani_-_Surah_At-Tariq_H1434-09-09.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/086-Abdulwali_Al-Arkani_-_Surah_At-Tariq_H1434-09-09.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//087-Abdulwali_Al-Arkani_-_Surah_Al-Ala_H1434-09-07.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>087-Abdulwali_Al-Arkani_-_Surah_Al-A'la_H1434-09-07 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/087-Abdulwali_Al-Arkani_-_Surah_Al-Ala_H1434-09-07.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/087-Abdulwali_Al-Arkani_-_Surah_Al-Ala_H1434-09-07.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//088-Abdulwali_Al-Arkani_-_Surah_Al-Ghashiyah_H1434-09-12.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Ghashiyah (The Overwhelming chapter) سورة الغاشية </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/088-Abdulwali_Al-Arkani_-_Surah_Al-Ghashiyah_H1434-09-12.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/088-Abdulwali_Al-Arkani_-_Surah_Al-Ghashiyah_H1434-09-12.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//095-Abdulwali_Al-Arkani_-_Surah_At-Teen_H1434-09-06.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah At-Teen (The Fig chapter) سورة التين </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/095-Abdulwali_Al-Arkani_-_Surah_At-Teen_H1434-09-06.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/095-Abdulwali_Al-Arkani_-_Surah_At-Teen_H1434-09-06.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//097-Abdulwali_Al-Arkani_-_Surah_Al-Qadr_H1434-09-06.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qadr (The Fate chapter) سورة القدر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/097-Abdulwali_Al-Arkani_-_Surah_Al-Qadr_H1434-09-06.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/097-Abdulwali_Al-Arkani_-_Surah_Al-Qadr_H1434-09-06.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//098-Abdulwali_Al-Arkani_-_Surah_Al-Baiyinah_H1434-09-12.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Baiyinah (The Evidence chapter) سورة البينة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/098-Abdulwali_Al-Arkani_-_Surah_Al-Baiyinah_H1434-09-12.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/098-Abdulwali_Al-Arkani_-_Surah_Al-Baiyinah_H1434-09-12.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//100-Abdulwali_Al-Arkani_-_Surah_Al-Adiyat_H1434-09-09.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>100-Abdulwali_Al-Arkani_-_Surah_Al-'Adiyat_H1434-09-09 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/100-Abdulwali_Al-Arkani_-_Surah_Al-Adiyat_H1434-09-09.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/100-Abdulwali_Al-Arkani_-_Surah_Al-Adiyat_H1434-09-09.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//101-Abdulwali_Al-Arkani_-_Surah_Al-Qariah_H1434-09-09.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>101-Abdulwali_Al-Arkani_-_Surah_Al-Qari'ah_H1434-09-09 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/101-Abdulwali_Al-Arkani_-_Surah_Al-Qariah_H1434-09-09.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/101-Abdulwali_Al-Arkani_-_Surah_Al-Qariah_H1434-09-09.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//104-Abdulwali_Al-Arkani_-_Surah_Al-Humaza_H1434-09-08.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Humazah (The Traducer chapter) سورة الهمزة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/104-Abdulwali_Al-Arkani_-_Surah_Al-Humaza_H1434-09-08.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/104-Abdulwali_Al-Arkani_-_Surah_Al-Humaza_H1434-09-08.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//105-Abdulwali_Al-Arkani_-_Surah_Al-Feel_H1434-09-08.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Feel (The Elephant chapter) سورة الفيل </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/105-Abdulwali_Al-Arkani_-_Surah_Al-Feel_H1434-09-08.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/105-Abdulwali_Al-Arkani_-_Surah_Al-Feel_H1434-09-08.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//109-Abdulwali_Al-Arkani_-_Surah_Al-Kafiroon_H1434-09-07.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Kafiroon (The Disbelievers chapter) سورة الكافرون </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/109-Abdulwali_Al-Arkani_-_Surah_Al-Kafiroon_H1434-09-07.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/109-Abdulwali_Al-Arkani_-_Surah_Al-Kafiroon_H1434-09-07.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
					</ul>
					<ul id='Part3'> 
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//099-Abdulwali_Al-Arkani_-_Surah_Az-Zalzalah_H1434-09-02.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Az-Zalzalah (The Earthquake chapter) سورة الزلزلة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/099-Abdulwali_Al-Arkani_-_Surah_Az-Zalzalah_H1434-09-02.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/099-Abdulwali_Al-Arkani_-_Surah_Az-Zalzalah_H1434-09-02.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//102-Abdulwali_Al-Arkani_-_Surah_At-Takathur_H1434-09-05.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah At-Takathur (Rivarly In World Increase chapter) سورة التكاثر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/102-Abdulwali_Al-Arkani_-_Surah_At-Takathur_H1434-09-05.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/102-Abdulwali_Al-Arkani_-_Surah_At-Takathur_H1434-09-05.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//112-Abdulwali_Al-Arkani_-_Surah_Al-Ikhlas_H1434-09-02.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Ikhlas (The Sincerity chapter) سورة الإخلاص </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/112-Abdulwali_Al-Arkani_-_Surah_Al-Ikhlas_H1434-09-02.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/112-Abdulwali_Al-Arkani_-_Surah_Al-Ikhlas_H1434-09-02.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//057-Abdulwali_Al-Arkani_-_Surah_Al-Hadeed_H1434.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Hadeed (The Iron chapter) سورة الحديد </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/057-Abdulwali_Al-Arkani_-_Surah_Al-Hadeed_H1434.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/057-Abdulwali_Al-Arkani_-_Surah_Al-Hadeed_H1434.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//022-Abdulwali_Al-Arkani_-_Surah_Al-Hajj_H1434.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Hajj (The Piligrimage chapter) سورة الحج </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/022-Abdulwali_Al-Arkani_-_Surah_Al-Hajj_H1434.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/022-Abdulwali_Al-Arkani_-_Surah_Al-Hajj_H1434.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//067-Abdulwali_Al-Arkani_-_Surah_Al-Mulk_H1427.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mulk (The Sovereignty chapter) سورة الملك </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/067-Abdulwali_Al-Arkani_-_Surah_Al-Mulk_H1427.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/067-Abdulwali_Al-Arkani_-_Surah_Al-Mulk_H1427.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//068-Abdulwali_Al-Arkani_-_Surah_Al-Qalam_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qalam (The Pen chapter) سورة القلم </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/068-Abdulwali_Al-Arkani_-_Surah_Al-Qalam_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/068-Abdulwali_Al-Arkani_-_Surah_Al-Qalam_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//069-Abdulwali_Al-Arkani_-_Surah_Al-Haqqah_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Haqqah (The Reality chapter) سورة الحآقة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/069-Abdulwali_Al-Arkani_-_Surah_Al-Haqqah_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/069-Abdulwali_Al-Arkani_-_Surah_Al-Haqqah_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//070-Abdulwali_Al-Arkani_-_Surah_Al-Maarij_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>070-Abdulwali_Al-Arkani_-_Surah_Al-Ma'arij_H1427 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/070-Abdulwali_Al-Arkani_-_Surah_Al-Maarij_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/070-Abdulwali_Al-Arkani_-_Surah_Al-Maarij_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//071-Abdulwali_Al-Arkani_-_Surah_Nooh_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nooh (Noah) نوح </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/071-Abdulwali_Al-Arkani_-_Surah_Nooh_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/071-Abdulwali_Al-Arkani_-_Surah_Nooh_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Muzzammil (The Enshrouded One chapter) سورة المزمل </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Muddaththir (The Cloaked One chapter) سورة المدثر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Sura Al-Qiyamah (The Resurrection chapter) سورة القيامة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Insan (The Human chapter) سورة الإنسان </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//077-Abdulwali_Al-Arkani_-_Surah_Al-Murslat_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mursalat (The Emissaries chapter) سورة المرسلات </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/077-Abdulwali_Al-Arkani_-_Surah_Al-Murslat_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/077-Abdulwali_Al-Arkani_-_Surah_Al-Murslat_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//067-Abdulwali_Al-Arkani_-_Surah_Al-Mulk_H1429.MP3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mulk (The Sovereignty chapter) سورة الملك </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/067-Abdulwali_Al-Arkani_-_Surah_Al-Mulk_H1429.MP3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/067-Abdulwali_Al-Arkani_-_Surah_Al-Mulk_H1429.MP3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//068-Abdulwali_Al-Arkani_-_Surah_Al-Qalam_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qalam (The Pen chapter) سورة القلم </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/068-Abdulwali_Al-Arkani_-_Surah_Al-Qalam_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/068-Abdulwali_Al-Arkani_-_Surah_Al-Qalam_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//069-Abdulwali_Al-Arkani_-_Surah_Al-Haqqah_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Haqqah (The Reality chapter) سورة الحآقة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/069-Abdulwali_Al-Arkani_-_Surah_Al-Haqqah_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/069-Abdulwali_Al-Arkani_-_Surah_Al-Haqqah_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//070-Abdulwali_Al-Arkani_-_Surah_Al-Maarij_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>070-Abdulwali_Al-Arkani_-_Surah_Al-Ma'arij_H1429 </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/070-Abdulwali_Al-Arkani_-_Surah_Al-Maarij_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/070-Abdulwali_Al-Arkani_-_Surah_Al-Maarij_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//071-Abdulwali_Al-Arkani_-_Surah_Nooh_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Nooh (Noah chapter) سورة نوح </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/071-Abdulwali_Al-Arkani_-_Surah_Nooh_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/071-Abdulwali_Al-Arkani_-_Surah_Nooh_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//072-Abdulwali_Al-Arkani_-_Surah_Al-Jinn_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Jinn (The Jinn chapter) سورة الجن </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/072-Abdulwali_Al-Arkani_-_Surah_Al-Jinn_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/072-Abdulwali_Al-Arkani_-_Surah_Al-Jinn_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Muzzammil (The Enshrouded One chapter) سورة المزمل </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/073-Abdulwali_Al-Arkani_-_Surah_Al-Muzzammil_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Muddaththir (The Cloaked One chapter) سورة المدثر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/074-Abdulwali_Al-Arkani_-_Surah_Al-Muddaththir_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Sura Al-Qiyamah (The Resurrection chapter) سورة القيامة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Insan (The Human chapter) سورة الإنسان </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//077-Abdulwali_Al-Arkani_-_Surah_Al-Murslat_H1429.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mursalat (The Emissaries chapter) سورة المرسلات </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/077-Abdulwali_Al-Arkani_-_Surah_Al-Murslat_H1429.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/077-Abdulwali_Al-Arkani_-_Surah_Al-Murslat_H1429.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//072-Abdulwali_Al-Arkani_-_Surah_Al-Jinn_H1427.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Jinn (The Jinn chapter) سورة الجن </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/072-Abdulwali_Al-Arkani_-_Surah_Al-Jinn_H1427.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/072-Abdulwali_Al-Arkani_-_Surah_Al-Jinn_H1427.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1428.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qiyamah (The Resurrection chapter) سورة القيامة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1428.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1428.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1432-07-23.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qiyamah (The Ressurection chapter) سورة القيامة </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1432-07-23.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/075-Abdulwali_Al-Arkani_-_Surah_Al-Qiyamah_H1432-07-23.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1432.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Insan (The Human chapter) سورة الإنسان </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1432.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/076-Abdulwali_Al-Arkani_-_Surah_Al-Insan_H1432.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//039-Abdulwali_Al-Arkani_-_a_clip_of_Surah_Az-Zumar_1430H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>A clip of Surah Az-Zumar | مقطع من سورة الزمر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_a_clip_of_Surah_Az-Zumar_1430H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_a_clip_of_Surah_Az-Zumar_1430H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
						<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abdulwali_Al-Arkani//039-Abdulwali_Al-Arkani_-_last_of_Surah_Az-Zumar_1430H.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Last of Surah Az-Zumar | أواخر سورة الزمر </a><a class='dlink' href=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_last_of_Surah_Az-Zumar_1430H.mp3' data-dlink=' https://archive.org/download/Abdulwali_Al-Arkani/039-Abdulwali_Al-Arkani_-_last_of_Surah_Az-Zumar_1430H.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
					</ul>
				</div>
						  
					 
			</div>	
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>  
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>Shaykh Abdul Wali Al Arkani who is also called « Abu Muad » in relation to one of his sons; was born in 1983 in the region of Mislafah in Mecca. He is a well-known Quran reciter and is currently the Imam of Khadem Al Haramein Al-Sharefein mosque in Jeddah, Saudi Arabia.	<br><br>

						Shaykh Al-Arkani learnt the Quran at the age of 14 first at the hand of his father, then other shaykhs and teachers in different mosques. He then moved to Mecca and was also the student of a number of prominent shaykh such as Shaykh Harun Dahir, the late Shaykh Muhammad Kabir, Shaykh Muhammad Idriss Abbass and others. He is also a friend of Shaykh Ahmed Bin Muhammad Al Shariff; the personal imam of the prince Nawaf Bin Abdul Aziz.<br><br>

						Moreover, he joined the Al Arqam Ibn Abu Al Arqam Institute in the Sacred Mosque (Masjid Al Haram) and graduated in 1997. He performed as an imam for the first time at the age of 13 at the mosque of Shaykh Muhammad Saleh Jamal in Meccah moving to other mosque within the same city before moving to Jeddah.<br><br>

						Given his popularity, Shaykh Al Arkani was invited to perform in different mosques within and outside Saudi Arabia for he was officially invited by the Governor of the Emirate of Ajman from the UAE to perform imamate next to the prominent reciter Mishary Rashid Alafasy.<br><br>

						At last, with his unique and eminent voice, there are audio and visual recordings of Shaykh Al Arkani’s recitations of the Quran available for his admirers. The recordings are also broadcasted in a number of Arab religious channels of Saudi Arabia, Abu Dhabi and Bahrain.</p>
						<p>هو الشيخ عبد الولي أمير حسين محمد الأركاني، وكنيته "أبو معاذ" نسبة إلى معاذ أحد ابنيه الاثنين، من قراء القرآن الكريم والأئمة السعوديين. ولد في العام 1403 هـ بمنطقة المسفلة التابعة لمكة المكرمة، خريج دار الأرقم بن أبي الرقم للحديث الشريف بمكة المكرمة ويعمل حاليا إماما لمسجد خادم الحرمين الشريفين بمدينة جدة بالمملكة العربية السعودية.
						<br><br>
						حفظ الشيخ الأركاني القرآن الكريم وهو في الرابعة عشرة من عمره وأتقن تلاوته وتجويده، وذلك عند عدد من مدرسيه منهم والده رحمه وعدد من الأساتذة والشيوخ ببعض المساجد. وقد قرأ على مشايخ كثيرين بمكة المكرمة من أبرزهم الشيخ هارون ظهير، والشيخ محمد كبير رحمه الله، وأجازه الشيخ محمد إدريس عباس بتان المدرس بالحرم المكي الشريف في رواية حفص عن عاصم من طريق الشاطبية، كما عرف الشيخ أحمد بن محمد الشريف الإمام الخاص لأمير نواف بن عبد العزيز، ولازمه ملازمة تامة. التحق بمعهد الأرقم بن أبي الأرقم بالحرم المكي وتخرج منه على يد فضيلة الشيخ الدكتور عبد الحميد شمس الحمداوي في العام 1418 هـ.<br><br>

						أهلته عذوبة صوته لتولي الإمامة في سن مبكرة (13 سنة) وكانت البداية من مسجد الشيخ محمد صالح جمال بحي الزاهر بمكة المكرمة، كما أم في مساجد أخرى متفرقة بالمدينة المقدسة قبل أن ينتقل إلى جدة ويعين هناك إمام لجامع معاذ بن جبل الذي ظل فيه سبع سنوات، وتلقى بعد ذلك الكثير من الدعوات من داخل السعودية وخارجها، وفي شعبان من العام 1428 هـ تلقى دعوة رسمية من حاكم إمارة عجمان بالإمارات العربية المتحدة لإمامة المصلين في الإمارة رفقة القارئ الكبير مشاري راشد العفاسي، ثم كلف في شوال الموالي بالإمامة من قبل مكتب الأمير عبد العزيز بن فهد بن عبد العزيز بجامع خادم الحرمين الشريفين الملك فهد بن عبد العزيز آل سعود بمدينة جدة.<br><br>

						صدرت للشيخ الأركاني عدد من التسجيلات الصوتية والمرئية منها تلاوة للمصحف المرتل ومقتطفات من قراءته في صلاة التراويح إلى جانب المواعظ والأدعية، وتذاع تلاواته في عدد من الإذاعات والقنوات الفضائية الإسلامية، منها إذاعة القرآن الكريم والقناة الأولى بالتلفزيون السعودي، وإذاعة القرآن الكريم بأبو ظبي بالإمارات العربية المتحدة، وإذاعة البحرين وقناة روائع الفضائية.</p>
				</div>  	
			</div>

		 


			
</div>
				  		
		
<?php  include $path . '/pages/footer.php'; ?>

