<?php  
		$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div>	
	        <div class="row reciter-container">	  
					   <div class=" archive-playlist-title">
											<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
						</div>
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='playlist1'> 
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//001.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>001- Al-Fatiha </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/001.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/001.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//002.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>002 - Al-Baqara </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/002.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/002.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//003.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>003 - Aal-E-Imran </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/003.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/003.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//004.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>004 - An-Nisa </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/004.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/004.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//005.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>005 - Al-Maeda </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/005.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/005.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//006.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>006 - Al-Anaam </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/006.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/006.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>007 - Al-Araf </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/007.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>008 - Al-Anfal </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/008.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>009 - At-Tawba </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/009.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>010 - Yunus </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/010.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>011 - Hud </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/011.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>012 - Yusuf </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/012.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//013.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>013 - Ar-Rad </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/013.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/013.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//014.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>014 - Ibrahim </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/014.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/014.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//015.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>015 - Al-Hijr </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/015.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/015.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//016.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>016 - An-Nahl </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/016.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/016.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//017.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>017 - Al-Isra </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/017.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/017.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//018.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>018 - Al-Kahf </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/018.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/018.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//019.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>019 - Maryam </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/019.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/019.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//020.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>020 - Ta-Ha </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/020.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/020.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//021.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>021 - Al-Anbiya </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/021.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/021.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//022.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>022 - Al-Hajj </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/022.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/022.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//023.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>023 - Al-Mumenoon </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/023.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/023.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//024.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>024 - An-Noor </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/024.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/024.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//025.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>025 - Al-Furqan </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/025.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/025.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//026.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>026 - Ash-Shuara </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/026.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/026.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//027.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>027 - An-Naml </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/027.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/027.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//028.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>028 - Al-Qasas </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/028.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/028.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//029.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>029 - Al-Ankaboot </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/029.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/029.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//030.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>030 - Ar-Room </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/030.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/030.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//031.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>031 - Luqman </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/031.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/031.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//032.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>032 - As-Sajda </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/032.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/032.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//033.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>033 - Al-Ahzab </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/033.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/033.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//034.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>034 - Saba </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/034.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/034.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//035.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>035 - Fatir </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/035.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/035.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//036.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>036 - Ya-Seen </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/036.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/036.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//037.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>037 - As-Saaffat </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/037.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/037.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//038.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>038 - Sad </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/038.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/038.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//039.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>039 - Az-Zumar </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/039.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/039.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//040.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>040 - Ghafir </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/040.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/040.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//041.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>041 - Fussilat </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/041.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/041.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//042.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>042 - Ash-Shura </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/042.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/042.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//043.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>043 - Az-Zukhruf </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/043.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/043.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//044.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>044 - Ad-Dukhan </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/044.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/044.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//045.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>045 - Al-Jathiya </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/045.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/045.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//046.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>046 - Al-Ahqaf </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/046.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/046.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//047.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>047 - Muhammad </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/047.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/047.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//048.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>048 - Al-Fath </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/048.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/048.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//049.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>049 - Al-Hujraat </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/049.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/049.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//050.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>050 - Qaf </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/050.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/050.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//051.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>051 - Adh-Dhariyat </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/051.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/051.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//053.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>053 - An-Najm </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/053.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/053.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//052.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>052 - At-Tur </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/052.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/052.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//055.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>055 - Ar-Rahman </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/055.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/055.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//054.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>054 - Al-Qamar </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/054.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/054.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//056.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>056 - Al-Waqia </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/056.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/056.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//057.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>057 - Al-Hadid </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/057.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/057.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//058.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>058 - Al-Mujadila </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/058.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/058.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//059.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>059 - Al-Hashr </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/059.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/059.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//060.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>060 - Al-Mumtahina </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/060.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/060.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//061.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>061 - As-Saff </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/061.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/061.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//063.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>063 - Al-Munafiqoon </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/063.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/063.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//062.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>062 - Al-Jumua </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/062.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/062.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//064.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>064 - At-Taghabun </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/064.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/064.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//066.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>066 - At-Tahrim </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/066.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/066.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//065.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>065 - At-Talaq </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/065.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/065.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//067.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>067 - Al-Mulk </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/067.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/067.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//068.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>068 - Al-Qalam </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/068.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/068.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//069.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>069 - Al-Haaqqa </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/069.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/069.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//070.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>070 - Al-Maarij </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/070.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/070.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//072.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>072 - Al-Jinn </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/072.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/072.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//071.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>071 - Nooh </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/071.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/071.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//074.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>074 - Al-Muddaththir </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/074.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/074.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//073.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>073 - Al-Muzzammil </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/073.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/073.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//076.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>076 - Al-Insan </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/076.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/076.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//075.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>075 - Al-Qiyama </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/075.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/075.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//078.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>078 - An-Naba </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/078.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/078.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//077.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>077 - Al-Mursalat </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/077.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/077.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//080.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>080 - Abasa </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/080.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/080.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//079.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>079 - An-Naziat </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/079.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/079.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//081.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>081 - At-Takwir </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/081.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/081.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//082.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>082 - Al-Infitar </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/082.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/082.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//083.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>083 - Al-Mutaffifin </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/083.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/083.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//084.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>084 - Al-Inshiqaq </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/084.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/084.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//085.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>085 - Al-Burooj </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/085.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/085.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//086.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>086 - At-Tariq </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/086.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/086.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//087.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>087 - Al-Ala </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/087.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/087.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//089.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>089 - Al-Fajr </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/089.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/089.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//088.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>088 - Al-Ghashiya </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/088.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/088.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//091.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>091 - Ash-Shams </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/091.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/091.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//090.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>090 - Al-Balad </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/090.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/090.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//092.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>092 - Al-Lail </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/092.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/092.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//094.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>094 - Al-Inshirah </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/094.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/094.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//093.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>093 - Ad-Dhuha </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/093.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/093.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//096.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>096 - Al-Alaq </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/096.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/096.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//095.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>095 - At-Tin </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/095.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/095.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//097.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>097 - Al-Qadr </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/097.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/097.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//098.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>098 - Al-Bayyina </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/098.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/098.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//099.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>099 - Az-Zalzala </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/099.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/099.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//101.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>101 - Al-Qaria </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/101.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/101.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//100.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>100 - Al-Adiyat </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/100.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/100.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//103.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>103 - Al-Asr </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/103.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/103.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//102.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>102 - At-Takathur </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/102.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/102.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//105.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>105 - Al-Fil </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/105.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/105.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//104.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>104 - Al-Humaza </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/104.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/104.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//107.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>107 - Al-Maun </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/107.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/107.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//106.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>106 - Quraish </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/106.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/106.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//108.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>108 - Al-Kauther </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/108.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/108.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//109.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>109 - Al-Kafiroon </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/109.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/109.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//111.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>111 - Al-Masadd </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/111.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/111.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//110.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>110 - An-Nasr </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/110.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/110.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//113.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>113 - Al-Falaq </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/113.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/113.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//112.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>112 - Al-Ikhlas </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/112.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/112.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Abu-Bakr//114.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>114 - An-Nas </a><a class='dlink' href=' https://archive.org/download/Abu-Bakr/114.mp3' data-dlink=' https://archive.org/download/Abu-Bakr/114.mp3'><img src='media/data/dlink.png' alt = ''/></a></li> 
							</ul>
						</div>
						  
					 
			</div>	 
					 
				  	 
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>   
					 
		    </div>  	 
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p ">Abu Bakr al Shatri, born Abu Bakr Ibn Mohamed Al Shatri in 1970 in Jeddah (Saudi Arabia), is&nbsp;<a href="http://www.assabile.com/quran/Saudi-Arabia" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">Saudi imam and Qur&rsquo;an reciter</a>.</p>

					<p ">bu Bakr Al Shatri grew up in Jeddah and graduated in&nbsp;<a href="http://www.assabile.com/quran/suwar" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">Holy Qur&rsquo;an</a>&nbsp;Studies from Cheikh Aymane Rochdi Suwaid in 1416 Hijri and then earned a master in accountancy four years later.</p>

					<p ">Abu Bakr Al Shatri has led prayers in many Saudi mosques like Al Rajihi, Said Ibn Jubair (Kandara), Abdullatif Jamil, Attakwa (Al Rawda), AChouiaibi (Assalama). He is currently the imam of Al Furkane Mosque in Hay Annassim, Jeddah.</p>

					<p  >Abu Bakr Al Shatri participated in numerous Islamic conferences and events in many Muslim countries like&nbsp;<a href="http://www.assabile.com/quran/Egypt" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">Egypt</a>, South Africa,&nbsp;<a href="http://www.assabile.com/quran/Kuwait" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">Kuwait</a>, and&nbsp;<a href="http://www.assabile.com/quran/Bahrain" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">Bahrain</a>.</p>

					<p >Abu Bakr Al Shatri is married and has four children. He is known as Abi Abdarrahmane.</p>

					<h3 >أبو بكر الشاطري.. خامة صوتية قوية و أسلوب متفرد !</h3>

					<p  >هو أبو بكر بن محمد الشاطري،&nbsp;<a href="http://ar.assabile.com/quran/Saudi-Arabia" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">قارئ و إمام سعودي</a>&nbsp;من مواليد سنة 1980م بجدة، يمتاز عن غيره من القراء بأسلوبه المتفرد في التلاوة والذي يُدخِل المنصتين إليه في جو من الخشوع والتدبر، عُرِف في الأوساط القرآنية بتوفره على خامة صوتية قوية وبضبطه لقواعد التجويد والترتيل، ويُعتبَر اليوم واحدا من&nbsp;<a href="http://ar.assabile.com/quran/top" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">أشهر القراء في العالمين العربي و الإسلامي</a>.</p>

					<p  ">نشأ أبو بكر الشاطري و ترعرع بجدة حيث حصل على الإجازة في&nbsp;<a href="http://ar.assabile.com/quran/suwar" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">القرآن الكريم</a>&nbsp;سنة ۱٤۱٦ه تحت إشراف الشيخ &quot;<a href="http://ar.assabile.com/ayman-swed-345/ayman-swed.htm" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">أيمن رشدي سويد</a>&quot; ثم بعدها على الماجستير في المحاسبة سنة ۱٤۲۰هـ، ليتفرغ بعد ذلك للعمل الدعوي من خلال الإمامة في المساجد وتلاوة القرآن في المناسبات واللقاءات الدينية.</p>

					<p ">سبق لأبي بكر الشاطري أن أمم في عدة مساجد منها: &quot;الراجحي&quot;، &quot;سعيد بن جبير&quot; (بكندرة)، &quot;عبد اللطيف جميل&quot;، &quot;التقوى&quot; (الروضة)، &quot;الشعيبي&quot; (السلامة). و هو حاليا إمام جامع &quot;الفرقان&quot; في حي النسيم بجدة.</p>

					<p >يشارك أبو بكر الشاطري في العديد من الندوات الإسلامية في&nbsp;<a href="http://ar.assabile.com/quran/Egypt" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">مصر</a>، جنوب إفريقيا،&nbsp;<a href="http://ar.assabile.com/quran/Kuwait" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">الكويت</a>،&nbsp;<a href="http://ar.assabile.com/quran/Bahrain" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; text-decoration: none; color: rgb(198, 102, 40);">البحرين</a>... الخ. حيث يحاول من خلالها التعريف بالإسلام عموما وبالقرآن الكريم على وجه الخصوص، كما يساهم في عدد من اللقاءات الدينية بتلاوة ما تيسر من الذكر الحكيم عساها تلين الأفئدة وتطمئن القلوب.</p>

					<p  >لأبي بكر الشاطري أربعة أبناء و هو ملقب بأبي عبد الرحمن. وقد قام بإصدار عدد من التسجيلات القرآنية بصوته المتميز أبرزها ختمتان للقرآن الكريم، صدرت الأولى سنة 1409هـ، وظهرت الثانية سنة 1428هـ، ولاقى الإصداران إقبالا واسعا حيث يتم بثهما على شاشات الفضائيات العربية والإذاعات الإسلامية وعلى شبكة الانترنيت.</p>
				
				</div>  	
			</div>

		</diV>
			 



			
		</div>
				  		
		
<?php  include $path . '/pages/footer.php'; ?>

