<?php  
	$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div>	
	        <div class="row reciter-container">	  
					   <div class=" archive-playlist-title">
											<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
						</div>
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='playlist1'>  
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//001.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fatihah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/001.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/001.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//002.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/002.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/002.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//003.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Imran </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/003.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/003.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//004.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nisa' </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/004.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/004.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//005.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'idah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/005.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/005.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//006.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-An'am </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/006.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/006.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'raf </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/007.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anfal </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/008.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taubah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/009.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yunus </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/010.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hood </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/011.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/012.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//013.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Ra'd </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/013.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/013.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//014.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/014.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/014.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//015.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hijr </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/015.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/015.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//016.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nahl </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/016.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/016.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//017.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Isra </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/017.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/017.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//018.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kahf </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/018.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/018.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//019.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maryam </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/019.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/019.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//020.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ta­Ha </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/020.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/020.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//021.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anbiya' </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/021.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/021.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//022.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hajj </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/022.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/022.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//023.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mu'minun </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/023.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/023.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//024.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nur </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/024.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/024.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//025.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Furqan </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/025.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/025.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//026.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shu'ara' </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/026.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/026.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//027.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naml </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/027.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/027.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//028.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qasas </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/028.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/028.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//029.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Ankabut </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/029.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/029.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//030.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar­Room </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/030.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/030.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//031.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/031.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/031.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//032.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As­Sajdah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/032.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/032.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//033.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al­Ahzab </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/033.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/033.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//034.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Saba' </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/034.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/034.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//035.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fatir </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/035.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/035.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//036.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ya­Sin </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/036.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/036.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//037.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saffat </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/037.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/037.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//038.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Sad </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/038.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/038.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//039.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zumar </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/039.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/039.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//040.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ghafir </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/040.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/040.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//041.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fussilat </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/041.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/041.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//042.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shura </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/042.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/042.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//043.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zukhruf </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/043.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/043.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//044.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Dukhan </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/044.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/044.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//045.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jathiya </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/045.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/045.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//046.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ahqaf </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/046.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/046.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//047.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Muhammad </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/047.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/047.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//048.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fath </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/048.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/048.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//049.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hujurat </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/049.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/049.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//050.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qaf </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/050.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/050.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//051.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zariyat </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/051.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/051.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//052.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tur </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/052.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/052.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//053.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Najm </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/053.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/053.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//054.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qamar </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/054.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/054.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//055.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Rahman </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/055.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/055.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//056.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Waqi'ah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/056.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/056.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//057.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hadid </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/057.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/057.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//058.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mujadilah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/058.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/058.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//059.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hashr </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/059.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/059.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//060.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mumtahinah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/060.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/060.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//061.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saff </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/061.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/061.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//062.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jumu'ah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/062.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/062.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//063.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Munafiqun </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/063.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/063.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//064.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taghabun </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/064.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/064.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//065.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Talaq </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/065.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/065.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//066.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tahrim </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/066.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/066.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//067.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mulk </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/067.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/067.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//068.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qalam </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/068.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/068.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//069.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Haqqah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/069.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/069.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//070.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'arij </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/070.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/070.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//071.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nooh </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/071.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/071.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//072.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jinn </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/072.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/072.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//073.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muzzammil </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/073.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/073.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//074.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muddaththir </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/074.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/074.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//075.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qiyamah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/075.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/075.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//076.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Insan </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/076.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/076.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//077.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mursalat </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/077.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/077.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//078.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naba' </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/078.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/078.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//079.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nazi'at </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/079.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/079.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//080.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>'Abasa </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/080.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/080.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//081.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takwir </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/081.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/081.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//082.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Infitar </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/082.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/082.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//083.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mutaffifin </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/083.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/083.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//084.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Inshiqaq </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/084.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/084.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//085.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Buruj </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/085.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/085.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//086.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tariq </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/086.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/086.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//087.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'la </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/087.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/087.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//088.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ghashiyah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/088.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/088.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//089.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fajr </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/089.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/089.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//090.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Balad </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/090.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/090.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//091.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shams </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/091.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/091.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//092.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Lail </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/092.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/092.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//093.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Duha </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/093.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/093.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//094.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Sharh </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/094.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/094.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//095.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tin </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/095.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/095.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//096.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Alaq </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/096.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/096.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//097.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qadr </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/097.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/097.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//098.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baiyinah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/098.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/098.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//099.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zalzalah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/099.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/099.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//100.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Adiyat </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/100.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/100.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//101.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qari'ah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/101.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/101.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//102.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takathur </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/102.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/102.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//103.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Asr </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/103.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/103.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//104.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Humazah </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/104.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/104.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//105.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fil </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/105.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/105.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//106.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Quraish </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/106.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/106.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//107.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'un </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/107.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/107.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//108.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kauthar </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/108.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/108.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//109.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kafirun </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/109.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/109.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//110.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nasr </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/110.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/110.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//111.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Masad </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/111.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/111.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//112.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ikhlas </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/112.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/112.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//113.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Falaq </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/113.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/113.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//114.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nas </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/114.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/114.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//117.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>117 كيف تحفظ القرآن ؟ </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/117.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/117.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//115-.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>115 الشيخ نور الدين محمد الوكيل - نعمة القرآن </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/115-.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/115-.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran//116.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>116 طرق ابداعيه لحفظ القران الكريم </a><a class='dlink' href=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/116.mp3' data-dlink=' https://archive.org/download/AhmedAlajmiTheCompleteHolyQuran/116.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
						</div>  
			</div>     
			
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>  
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>Ahmed Ali Al Ajmi is a Qur'an reciter from Khobar, an eastern Province of the Kingdom of Saudi Arabia. He was born February 24, 1968. <br><br>

					After graduating from Mohamed Ben Saud Islamic University, Ahmed Al Ajmi flew to Pakistan where he enrolled in Lahore Public University to prepare a Master and then a Doctorate in Qur’an Interpretation. His thesis was entitled “Minnat Al Aliy Al Kabir Fi Charh Toroq Attafsir” (a study of interpretation means).<br><br>

					Cheikh Ahmed Ajmi is one of the most outstanding reciters in the world. He first led prayers in 1984 (1404 Hijri) in Al Moghira Ben Chooba Mosque and then in the Great Mosque of Khobar in 1985. He was recruited as Imam to Al Amir Mohamed Ben Fahd Mosque in Khobar in 1992. Ahmed Al Ajmi is currently leading prayers Jeddah’s Holy Mosque.<br><br>

					Ahmed Al Ajmi is married and has six childrens : Abullah, Omar, Fatima, Mariem, Modi and Abdurahmane.<br><br>

					Ahmed Ajmi is living with his family in Alorqobia, Khobar (Saudi Arabia).</p>
					<p>هو أحمد بن علي بن محمد بن سليمان العجمي، قارئ و إمام سعودي من مواليد 24 فبراير 1968م في الخبر بالمملكة العربية السعودية.
					<br><br>
					تلقى أحمد العجمي تعليمه الابتدائي في مدرسة "المحمدية جنوب الخبر، انتقل بعدها إلى إعدادية "الزبير بن عوام" قبل الالتحاق بثانوية الخبر مدينة العمال.<br><br>

					حصل أحمد العجمي على إجازة في الشريعة من الجامعة الإسلامية "الإمام محمد بن سعود" قبل نيل شهادة عليا من جامعة "لاهور" بباكستان. و قد نال مؤخرا الدكتوراه في تحليل القرآن الكريم.<br><br>

					بدأ أحمد العجمي الصلاة سنة ۱٤۰٤ه في مسجد "المغيرة بن شعبة" بالثقبة، و بعد ذلك في مسجد الخبر سنة ۱٤۰۵ه، يليه مسجد "الأمير محمد بن فهد" في الحزام الذهبي سنة ۱٤۱۲ه، و بعده مسجد "الريان" و أخيرا مسجد "خادم الحرمين الشريفين" بجدة.<br><br>

					و أحمد العجمي متزوج و أب لستة أبناء: أربعة أولاد (عبد الله، عمر، موضي و عبد الرحمن) و بنتان (فاطمة و مريم).<br><br>

					عرف أحمد العجمي خاصة بصوته الجميل و تلاوته الرائعة التي أكسبته شهرة خاصة كمقرئ في العالم العربي و كإمام في جامع "الملك فهد" بجدة.<br><br>

					و قد أصدر العديد من التسجيلات لتلاواته القرآنية، هذا بالإضافة على بثها في العديد من القنوات الإذاعية و التلفزية.<br><br>

					و يقدم أحمد العجمي ندوات و برامج تلفزية تحيط بعدد مهم من المواضيع التي تخص الدين الإسلامي.و للإشارة، فأحمد العجمي منشد إسلامي، و قد سبق له أن أصدر أسطوانات مثل "ودعناك"، "أناشيد"...الخ.</p>
				</div>  	
			</div> 


			
</div>
				  		
		
<?php  include $path . '/pages/footer.php'; ?>

