<?php  
	$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div> 
	        <div class="row reciter-container">  
			    <div class=" archive-playlist-title">
					<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
				</div>
				<div class="row btns-player-catagory">  
					<a href='#' class="btn  btn-success " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#playlist1'}); return false;"><i class="fa fa-book"></i> Juz 1-5</a>	  
					<a href='#' class=" btn   " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#a'}); return false;"><i class="fa fa-book"></i> Juz 6-10</a>
					
					<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#b'}); return false;"><i class="fa fa-book"></i> Juz 11-15</a> 
					
					<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#c'}); return false;"><i class="fa fa-book"></i> Juz 16-20</a> 
					
					<a href='#' class=" btn   " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#d'}); return false;"><i class="fa fa-book"></i> Juz 21-25</a>
					
					<a href='#' class=" btn   " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#e'}); return false;"><i class="fa fa-book"></i> Juz 26-30</a>
					
					<a href='#' class=" btn  " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#clear'}); return false;"><i class="fa fa-book"></i> Clear</a>
					 
					<script>
						$(function() {
						  $('.btn').click( function() {
							$(this).addClass('btn-success').siblings().removeClass('btn-success');
						  });
						});
					</script>
				</div> 
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='clear'>  </ul>
							<ul id='playlist1'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//001.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fatiha  الفاتحة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/001.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/001.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//002.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah  البقرة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/002.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/002.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//003.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al Imran  آل عمران </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/003.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/003.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//004.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nisa  النساء </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/004.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/004.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
							<ul id='a'> 
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//005.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Maidah  المائدة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/005.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/005.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//006.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anam  الأنعام </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/006.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/006.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Araf  الأعراف </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/007.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anfal  الأنفال </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/008.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taubah  التوبة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/009.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							
							</ul>
							<ul id='b'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yunus  يونس </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/010.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hud  هود </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/011.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf  يوسف </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/012.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//013.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Rad  الرعد </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/013.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/013.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//014.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim  إبراهيم </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/014.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/014.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//015.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hijr  الحجر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/015.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/015.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//016.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nahl  النحل </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/016.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/016.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//017.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Isra  الإسراء </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/017.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/017.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//018.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kahf  الكهف </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/018.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/018.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							
							</ul>
							<ul id='c'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//019.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maryam  مريم </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/019.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/019.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//020.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ta-Ha  طه </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/020.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/020.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//021.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anbiya  الأنبياء </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/021.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/021.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//022.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hajj  الحج </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/022.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/022.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//023.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muminun  المؤمنون </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/023.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/023.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//024.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nur  النور </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/024.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/024.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//025.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Furqan  الفرقان </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/025.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/025.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//026.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shuara  الشعراء </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/026.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/026.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//027.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naml  النمل </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/027.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/027.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//028.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qasas  القصص </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/028.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/028.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//029.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ankabut  العنكبوت </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/029.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/029.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							
							</ul>
							<ul id='d'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//030.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Rum  الروم </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/030.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/030.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//031.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman  لقمان </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/031.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/031.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//032.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Sajdah  السجدة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/032.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/032.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//033.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ahzab  الأحزاب </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/033.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/033.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//034.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Saba  سبأ </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/034.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/034.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//035.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fatir  فاطر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/035.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/035.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//036.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ya-Sin  يس </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/036.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/036.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//037.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saffaat  الصافات </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/037.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/037.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//038.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Saad  ص </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/038.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/038.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//039.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zumar  الزمر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/039.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/039.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//040.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ghafir  غافر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/040.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/040.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//041.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fussilat  فصلت </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/041.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/041.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							
							</ul>
							<ul id='e'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//042.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shura  الشورى </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/042.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/042.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//043.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zukhruf  الزخرف </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/043.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/043.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//044.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Dukhan  الدخان </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/044.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/044.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//045.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jathiyah  الجاثية </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/045.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/045.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//046.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ahqaf  الأحقاف </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/046.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/046.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//047.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Muhammad  محمد </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/047.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/047.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//048.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fath  الفتح </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/048.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/048.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//049.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hujuraat  الحجرات </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/049.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/049.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//050.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qaf  ق </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/050.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/050.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//051.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Adh-Dhariyat  الذاريات </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/051.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/051.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//052.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tur  الطور </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/052.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/052.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//053.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Najm  النجم </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/053.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/053.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//054.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qamar  القمر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/054.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/054.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//055.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Rahman  الرحمن </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/055.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/055.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//056.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Waqiah  الواقعة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/056.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/056.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//057.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hadid  الحديد </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/057.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/057.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//058.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mujadilah  المجادلة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/058.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/058.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//059.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hashr  الحشر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/059.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/059.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//060.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mumtahana  الممتحنة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/060.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/060.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//061.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saff  الصف </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/061.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/061.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//062.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jumuah  الجمعة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/062.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/062.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//063.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Munafiqun  المنافقون </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/063.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/063.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//064.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taghabun  التغابن </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/064.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/064.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//065.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Talaaq  الطلاق </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/065.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/065.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//066.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tahrim  التحريم </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/066.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/066.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//067.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mulk  الملك </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/067.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/067.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//068.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qalam  القلم </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/068.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/068.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//069.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Haqqah  الحاقة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/069.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/069.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//070.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Maarij  المعارج </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/070.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/070.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//071.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nuh  نوح </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/071.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/071.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//072.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jinn  الجن </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/072.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/072.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//073.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muzzammil  المزمل </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/073.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/073.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//074.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muddathir  المدثر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/074.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/074.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//075.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qiyamah  القيامة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/075.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/075.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//076.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Insan  الإنسان </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/076.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/076.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//077.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mursalaat  المرسلات </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/077.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/077.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//078.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naba  النبأ </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/078.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/078.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//079.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naziaat  النازعات </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/079.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/079.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//080.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Abasa  عبس </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/080.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/080.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//081.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takwir  التكوير </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/081.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/081.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//082.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Infitaar  الانفطار </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/082.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/082.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//083.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mutaffifi  المطففين </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/083.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/083.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//084.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Inshiqaq  الانشقاق </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/084.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/084.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//085.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Buruj  البروج </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/085.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/085.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//086.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tariq  الطارق </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/086.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/086.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//087.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ala  الأعلى </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/087.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/087.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//088.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ghaashiya  الغاشية </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/088.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/088.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//089.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fajr  الفجر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/089.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/089.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//090.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Balad  البلد </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/090.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/090.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//091.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shams  الشمس </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/091.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/091.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//092.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Lail  الليل </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/092.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/092.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//093.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Duha  الضحى </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/093.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/093.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//094.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Sharh  الشرح </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/094.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/094.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//095.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tin  التين </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/095.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/095.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//096.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al Alaq  العلق </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/096.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/096.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//097.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qadr  القدر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/097.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/097.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//098.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baiyyinah  البينة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/098.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/098.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//099.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zalzalah  الزلزلة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/099.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/099.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//100.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Aadiyaat  العاديات </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/100.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/100.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//101.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qariah  القارعة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/101.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/101.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//102.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takaathur  التكاثر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/102.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/102.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//103.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Asr  العصر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/103.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/103.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//104.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Humazah  الهمزة </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/104.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/104.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//105.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fil  الفيل </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/105.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/105.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//106.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Quraish  قريش </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/106.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/106.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//107.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Maaun  الماعون </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/107.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/107.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//108.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kauthar  الكوثر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/108.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/108.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//109.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kaafirun  الكافرون </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/109.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/109.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//110.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nasr  النصر </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/110.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/110.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//111.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Masad  المسد </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/111.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/111.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//112.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ikhlaas  الإخلاص </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/112.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/112.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//113.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Falaq  الفلق </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/113.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/113.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/CompleteQuranRecitation//114.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naas  الناس </a><a class='dlink' href=' https://archive.org/download/CompleteQuranRecitation/114.mp3' data-dlink=' https://archive.org/download/CompleteQuranRecitation/114.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
						</div>  
			</div>	 
			<?php  include $path . '/pages/gallery.php';     ?>   
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>د. بندر بن عبد العزيز بليله<br />
				   - من مواليد مكة المكرمة عام 1395 هـ .<br />
				   - درس بها جميع المراحل الدراسية الإبتدائية والمتوسطة والثانوية والباكلريوس .<br />
				   - حصل على الماجستير في عام 1422 هـ في الفقه من كلية الشريعة والدراسات الإسلامية من جامعة أم القرى .<br />
				   - حصل على درجة الدكتوراه في الفقه من كلية الشريعة عام 1429هـ من الجامعة الإسلامية بالمدينة المنورة .<br />
				   - عمل مدرسًا للفقة بمعهد الحرم المكي الشريف بالقسم العالي .<br />
				   - يعمل حاليًا أستاذًا مساعدًا بجامعة الطائف .<br />
				   - وإمام وخطيب جامع الأميرة نوف بحي العزيزية بمكة المكرمة ، ثم جامع ابن باز .<br />
				   - صدر القرار بتعيينه إماماً للمسجد الحرام يوم الأحد 12/ 9/ 1434هـ</p>

					<p> - Dr. Bandar bin &#39;Abdul Azeez Baleela<br />
				   - Born in Makkah in 1395 AH.<br />
				   - Earned a Masters degree in 1422 AH in the Fiqh from the College of Sharia and Islamic Studies from the Umm al-Qura University.<br />
				   - Received a doctorate degree in Fiqh from the Faculty of Sharia in 1429 AH from the Islamic University of Madeenah.<br />
				   - Worked as a teacher of fiqh at the Institute of Haram al-Sharif higher section.<br />
				   - He is now an assistant professor at the University of Taif.<br />
				   - Served as imaam and khateeb of Masjid Ameera Nouf in the Aziziyah district in Makkah, and after that in Masjid Bin Baz.<br />
				   - Appointed as imaam of the Masjid al Haram on Sunday, 12/9/1434 AH.<br />
				   - Appointed as permanent of Masjid al Haram on Wednesday, 4/12/1434AH<br />
				   - Led first regular salaah in Masjid al Haram on 5/12/1434, for Maghrib</p>
				</div>  	
			</div>
 


			
</div>
				  		
		
<?php  include $path . '/pages/footer.php'; ?>

