<?php  
		$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	
	$videos = array("x5g3yzath9s","N8Ar5YIS9hk","Jra_arHGt5w","0cQ1Z4tqwns","xW7Q3owmbDg","5GxDNRemEGI");
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div>	
	        <div class="row reciter-container">	  
					   <div class=" archive-playlist-title">
											<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
						</div>
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='playlist1'> 
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//001Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fatihah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/001Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/001Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//002Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/002Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/002Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//003Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Imran </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/003Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/003Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//004Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nisa' </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/004Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/004Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//005Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'idah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/005Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/005Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//006Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-An'am </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/006Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/006Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//007Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'raf </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/007Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/007Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//008Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anfal </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/008Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/008Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//009Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taubah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/009Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/009Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//010Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yunus </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/010Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/010Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//011Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hood </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/011Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/011Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//012Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/012Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/012Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//013Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Ra'd </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/013Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/013Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//014Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/014Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/014Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//015Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hijr </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/015Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/015Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//016Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nahl </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/016Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/016Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//017Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Isra </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/017Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/017Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//018Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kahf </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/018Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/018Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//019Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maryam </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/019Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/019Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//020Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ta­Ha </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/020Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/020Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//021Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anbiya' </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/021Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/021Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//022Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hajj </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/022Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/022Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//023Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mu'minun </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/023Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/023Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//024Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nur </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/024Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/024Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//025Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Furqan </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/025Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/025Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//026Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shu'ara' </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/026Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/026Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//027Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naml </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/027Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/027Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//028Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qasas </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/028Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/028Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//029Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Ankabut </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/029Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/029Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//030Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar­Room </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/030Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/030Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//031Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/031Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/031Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//032Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As­Sajdah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/032Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/032Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//033Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al­Ahzab </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/033Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/033Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//034Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Saba' </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/034Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/034Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//035Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fatir </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/035Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/035Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//036Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ya­Sin </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/036Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/036Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//037Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saffat </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/037Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/037Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//038Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Sad </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/038Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/038Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//039Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zumar </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/039Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/039Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//040Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ghafir </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/040Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/040Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//041Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fussilat </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/041Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/041Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//042Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shura </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/042Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/042Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//043Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zukhruf </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/043Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/043Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//044Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Dukhan </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/044Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/044Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//045Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jathiya </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/045Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/045Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//046Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ahqaf </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/046Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/046Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//047Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Muhammad </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/047Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/047Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//048Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fath </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/048Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/048Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//049Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hujurat </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/049Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/049Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//050Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qaf </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/050Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/050Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//051Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zariyat </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/051Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/051Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//052Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tur </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/052Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/052Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//053Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Najm </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/053Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/053Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//054Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qamar </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/054Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/054Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//055Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Rahman </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/055Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/055Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//056Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Waqi'ah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/056Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/056Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//057Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hadid </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/057Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/057Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//058Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mujadilah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/058Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/058Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//059Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hashr </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/059Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/059Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//060Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mumtahinah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/060Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/060Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//061Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saff </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/061Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/061Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//062Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jumu'ah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/062Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/062Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//063Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Munafiqun </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/063Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/063Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//064Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taghabun </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/064Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/064Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//065Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Talaq </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/065Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/065Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//066Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tahrim </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/066Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/066Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//067Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mulk </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/067Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/067Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//068Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qalam </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/068Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/068Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//069Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Haqqah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/069Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/069Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//070Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'arij </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/070Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/070Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//071Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nooh </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/071Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/071Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//072Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jinn </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/072Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/072Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//073Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muzzammil </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/073Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/073Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//074Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muddaththir </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/074Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/074Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//075Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qiyamah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/075Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/075Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//076Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Insan </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/076Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/076Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//077Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mursalat </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/077Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/077Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//078Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naba' </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/078Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/078Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//079Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nazi'at </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/079Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/079Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//080Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>'Abasa </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/080Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/080Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//081Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takwir </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/081Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/081Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//082Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Infitar </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/082Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/082Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//083Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mutaffifin </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/083Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/083Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//084Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Inshiqaq </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/084Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/084Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//085Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Buruj </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/085Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/085Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//086Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tariq </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/086Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/086Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//087Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'la </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/087Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/087Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//088Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ghashiyah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/088Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/088Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//089Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fajr </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/089Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/089Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//090Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Balad </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/090Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/090Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//091Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shams </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/091Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/091Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//092Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Lail </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/092Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/092Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//093Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Duha </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/093Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/093Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//094Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Sharh </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/094Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/094Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//095Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tin </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/095Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/095Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//096Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Alaq </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/096Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/096Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//097Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qadr </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/097Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/097Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//098Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baiyinah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/098Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/098Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//099Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zalzalah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/099Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/099Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//100Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Adiyat </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/100Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/100Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//101Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qari'ah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/101Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/101Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//102Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takathur </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/102Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/102Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//103Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Asr </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/103Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/103Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//104Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Humazah </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/104Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/104Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//105Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fil </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/105Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/105Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//106Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Quraish </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/106Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/106Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//107Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'un </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/107Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/107Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//108Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kauthar </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/108Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/108Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//109Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kafirun </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/109Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/109Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//110Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nasr </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/110Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/110Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//111Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Masad </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/111Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/111Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//112Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ikhlas </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/112Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/112Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//113Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Falaq </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/113Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/113Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FaresAbbad_284//114Www.quranaudio.info.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nas </a><a class='dlink' href=' https://archive.org/download/FaresAbbad_284/114Www.quranaudio.info.mp3' data-dlink=' https://archive.org/download/FaresAbbad_284/114Www.quranaudio.info.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
						</div>  
			</div>  	
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>
			<div class="row reciter-container">	
					<?php
						foreach($videos as $video){
							echo '<div class="col-md-4 col-sm-6"><iframe width="100%" height="250" src="//www.youtube.com/embed/';
							echo $video;
							echo '?rel=0" frameborder="0" allowfullscreen></iframe> <a href="http://www.yt-mp3.com/watch?v=';
							echo $video;
							echo '"  onClick="return YoutubeMp3Script(this)" class="btn btn-danger btn-lg btn-block" role="button"><i class="fa fa-music"> Download Mp3</i></a> </div> '; 
						} 
					?>
			 
		    </div> 
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div>   
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة <strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>Fares Abbad is Yemeni Qur’an reciter. In 1425, Sheikh Fares Abdad was the imam of Sheikh Abderrazak Afifi Mosque, Riyadh, Saudi Arabia. source: assabile</p>
				</div>  	
			</div> 
			


</div> 


		 

<?php  include $path . '/pages/footer.php'; ?>		

				