<?php  
		$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div>	
	        <div class="row reciter-container">	  
					   <div class=" archive-playlist-title">
											<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
						</div>
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='playlist1'> 
								 <li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//001-AlFatihah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>001-AlFatihah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/001-AlFatihah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/001-AlFatihah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//002-AlBaqarah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>002-AlBaqarah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/002-AlBaqarah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/002-AlBaqarah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//003-Alimran.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>003-Alimran </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/003-Alimran.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/003-Alimran.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//004-AnNisa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>004-AnNisa </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/004-AnNisa.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/004-AnNisa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//005-AlMaidah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>005-AlMaidah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/005-AlMaidah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/005-AlMaidah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//006-AlAnam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>006-AlAnam </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/006-AlAnam.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/006-AlAnam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//007-AlAraf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>007-AlAraf </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/007-AlAraf.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/007-AlAraf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//008-AlAnfal.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>008-AlAnfal </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/008-AlAnfal.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/008-AlAnfal.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//009-AtTaubah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>009-AtTaubah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/009-AtTaubah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/009-AtTaubah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//010-Yunus.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>010-Yunus </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/010-Yunus.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/010-Yunus.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//011-Hud.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>011-Hud </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/011-Hud.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/011-Hud.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//012-Yusuf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>012-Yusuf </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/012-Yusuf.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/012-Yusuf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//013-ArRad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>013-ArRad </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/013-ArRad.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/013-ArRad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//014-Ibrahim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>014-Ibrahim </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/014-Ibrahim.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/014-Ibrahim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//015-AlHijr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>015-AlHijr </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/015-AlHijr.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/015-AlHijr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//016-AnNahl.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>016-AnNahl </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/016-AnNahl.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/016-AnNahl.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//017-AlIsra.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>017-AlIsra </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/017-AlIsra.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/017-AlIsra.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//018-AlKahf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>018-AlKahf </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/018-AlKahf.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/018-AlKahf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//019-Maryam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>019-Maryam </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/019-Maryam.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/019-Maryam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//020-TaHa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>020-TaHa </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/020-TaHa.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/020-TaHa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//021-AlAnbiya.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>021-AlAnbiya </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/021-AlAnbiya.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/021-AlAnbiya.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//022-AlHajj.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>022-AlHajj </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/022-AlHajj.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/022-AlHajj.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//023-AlMuminun.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>023-AlMuminun </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/023-AlMuminun.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/023-AlMuminun.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//024-_AnNur.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>024-_AnNur </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/024-_AnNur.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/024-_AnNur.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//025-AlFurqan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>025-AlFurqan </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/025-AlFurqan.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/025-AlFurqan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//026-AshShuara.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>026-AshShuara </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/026-AshShuara.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/026-AshShuara.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//027-AnNaml.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>027-AnNaml </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/027-AnNaml.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/027-AnNaml.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//028-AlQasas.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>028-AlQasas </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/028-AlQasas.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/028-AlQasas.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//029-AlAnkabut.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>029-AlAnkabut </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/029-AlAnkabut.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/029-AlAnkabut.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//030-ArRum.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>030-ArRum </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/030-ArRum.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/030-ArRum.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//031-Luqman.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>031-Luqman </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/031-Luqman.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/031-Luqman.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//032-AsSajdah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>032-AsSajdah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/032-AsSajdah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/032-AsSajdah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//033-AlAhzab.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>033-AlAhzab </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/033-AlAhzab.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/033-AlAhzab.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//034-Saba.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>034-Saba </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/034-Saba.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/034-Saba.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//035-Fatir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>035-Fatir </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/035-Fatir.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/035-Fatir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//036-YaSin.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>036-YaSin </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/036-YaSin.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/036-YaSin.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//037-AsSaffat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>037-AsSaffat </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/037-AsSaffat.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/037-AsSaffat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//038-Sad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>038-Sad </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/038-Sad.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/038-Sad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//039-AzZumar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>039-AzZumar </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/039-AzZumar.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/039-AzZumar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//040-Ghafir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>040-Ghafir </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/040-Ghafir.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/040-Ghafir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//041-Fussilat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>041-Fussilat </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/041-Fussilat.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/041-Fussilat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//042-AshShura.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>042-AshShura </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/042-AshShura.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/042-AshShura.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//043-AzZukhruf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>043-AzZukhruf </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/043-AzZukhruf.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/043-AzZukhruf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//044-AdDukhan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>044-AdDukhan </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/044-AdDukhan.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/044-AdDukhan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//045-AlJathiyah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>045-AlJathiyah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/045-AlJathiyah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/045-AlJathiyah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//046-AlAhqaf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>046-AlAhqaf </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/046-AlAhqaf.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/046-AlAhqaf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//047-Muhammad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>047-Muhammad </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/047-Muhammad.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/047-Muhammad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//048-AlFath.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>048-AlFath </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/048-AlFath.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/048-AlFath.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//049-AlHujurat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>049-AlHujurat </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/049-AlHujurat.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/049-AlHujurat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//050-Qaf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>050-Qaf </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/050-Qaf.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/050-Qaf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//051-AdhDhariyat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>051-AdhDhariyat </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/051-AdhDhariyat.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/051-AdhDhariyat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//052-AtTur.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>052-AtTur </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/052-AtTur.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/052-AtTur.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//053-AnNajm.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>053-AnNajm </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/053-AnNajm.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/053-AnNajm.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//054-Qamar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>054-Qamar </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/054-Qamar.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/054-Qamar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//055-ArRahman.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>055-ArRahman </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/055-ArRahman.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/055-ArRahman.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//056-AlWaqiah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>056-AlWaqiah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/056-AlWaqiah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/056-AlWaqiah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//057-AlHadid.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>057-AlHadid </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/057-AlHadid.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/057-AlHadid.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//058-AlMujadilah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>058-AlMujadilah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/058-AlMujadilah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/058-AlMujadilah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//059-AlHashr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>059-AlHashr </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/059-AlHashr.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/059-AlHashr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//060-AlMumtahanah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>060-AlMumtahanah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/060-AlMumtahanah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/060-AlMumtahanah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//061-AsSaff.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>061-AsSaff </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/061-AsSaff.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/061-AsSaff.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//062-AlJumuah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>062-AlJumuah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/062-AlJumuah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/062-AlJumuah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//063-AlMunafiqun.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>063-AlMunafiqun </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/063-AlMunafiqun.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/063-AlMunafiqun.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//064-AtTaghabun.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>064-AtTaghabun </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/064-AtTaghabun.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/064-AtTaghabun.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//065-AtTalaq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>065-AtTalaq </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/065-AtTalaq.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/065-AtTalaq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//066-AtTahrim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>066-AtTahrim </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/066-AtTahrim.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/066-AtTahrim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//067-AlMulk.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>067-AlMulk </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/067-AlMulk.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/067-AlMulk.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//068-AlQalam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>068-AlQalam </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/068-AlQalam.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/068-AlQalam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//069-AlHaqqah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>069-AlHaqqah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/069-AlHaqqah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/069-AlHaqqah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//070-AlMaarij.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>070-AlMaarij </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/070-AlMaarij.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/070-AlMaarij.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//071-Nuh.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>071-Nuh </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/071-Nuh.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/071-Nuh.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//072-AlJinn.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>072-AlJinn </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/072-AlJinn.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/072-AlJinn.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//073-AlMuzzammil.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>073-AlMuzzammil </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/073-AlMuzzammil.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/073-AlMuzzammil.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//074-AlMuddaththir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>074-AlMuddaththir </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/074-AlMuddaththir.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/074-AlMuddaththir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//075-AlQiyamah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>075-AlQiyamah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/075-AlQiyamah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/075-AlQiyamah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//076-_AlInsan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>076-_AlInsan </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/076-_AlInsan.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/076-_AlInsan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//077-AlMursalat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>077-AlMursalat </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/077-AlMursalat.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/077-AlMursalat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//078-AnNaba.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>078-AnNaba </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/078-AnNaba.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/078-AnNaba.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//079-AnNaziat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>079-AnNaziat </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/079-AnNaziat.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/079-AnNaziat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//080-Abasa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>080-Abasa </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/080-Abasa.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/080-Abasa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//081-AtTakwir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>081-AtTakwir </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/081-AtTakwir.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/081-AtTakwir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//082-AlInfitar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>082-AlInfitar </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/082-AlInfitar.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/082-AlInfitar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//083-AlMutaffifin.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>083-AlMutaffifin </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/083-AlMutaffifin.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/083-AlMutaffifin.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//084-AlInshiqaq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>084-AlInshiqaq </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/084-AlInshiqaq.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/084-AlInshiqaq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//085-AlBuruj.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>085-AlBuruj </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/085-AlBuruj.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/085-AlBuruj.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//086-AtTariq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>086-AtTariq </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/086-AtTariq.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/086-AtTariq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//087-AlAla.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>087-AlAla </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/087-AlAla.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/087-AlAla.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//088-AlGhashiyah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>088-AlGhashiyah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/088-AlGhashiyah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/088-AlGhashiyah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//089-AlFajr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>089-AlFajr </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/089-AlFajr.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/089-AlFajr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//090-AlBalad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>090-AlBalad </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/090-AlBalad.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/090-AlBalad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//091-AshShams.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>091-AshShams </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/091-AshShams.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/091-AshShams.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//092-AlLail.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>092-AlLail </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/092-AlLail.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/092-AlLail.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//093-AdDuha.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>093-AdDuha </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/093-AdDuha.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/093-AdDuha.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//094-AshSharh.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>094-AshSharh </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/094-AshSharh.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/094-AshSharh.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//095-AtTin.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>095-AtTin </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/095-AtTin.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/095-AtTin.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//096-AlAlaq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>096-AlAlaq </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/096-AlAlaq.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/096-AlAlaq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//097-AlQadr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>097-AlQadr </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/097-AlQadr.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/097-AlQadr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//098-AlBayyinah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>098-AlBayyinah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/098-AlBayyinah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/098-AlBayyinah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//099-AzZalzalah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>099-AzZalzalah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/099-AzZalzalah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/099-AzZalzalah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//100-AlAadiyat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>100-AlAadiyat </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/100-AlAadiyat.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/100-AlAadiyat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//101-AlQariah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>101-AlQariah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/101-AlQariah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/101-AlQariah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//102-AtTakathur.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>102-AtTakathur </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/102-AtTakathur.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/102-AtTakathur.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//103-AlAsr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>103-AlAsr </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/103-AlAsr.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/103-AlAsr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//104-AlHumazah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>104-AlHumazah </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/104-AlHumazah.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/104-AlHumazah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//105-AlFil.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>105-AlFil </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/105-AlFil.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/105-AlFil.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//106-Quraish.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>106-Quraish </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/106-Quraish.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/106-Quraish.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//107-AlMaun.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>107-AlMaun </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/107-AlMaun.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/107-AlMaun.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//108-AlKauthar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>108-AlKauthar </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/108-AlKauthar.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/108-AlKauthar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//109-AlKafirun.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>109-AlKafirun </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/109-AlKafirun.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/109-AlKafirun.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//110-AnNasr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>110-AnNasr </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/110-AnNasr.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/110-AnNasr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//111-AlMasad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>111-AlMasad </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/111-AlMasad.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/111-AlMasad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//SuretAlekhlas.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>suret alekhlas </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/SuretAlekhlas.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/SuretAlekhlas.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//SuretAlfalq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>suret alfalq </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/SuretAlfalq.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/SuretAlfalq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/FullQuranKareemSh.abdallahKamel//SuretAlnas.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>suret alnas </a><a class='dlink' href=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/SuretAlnas.mp3' data-dlink=' https://archive.org/download/FullQuranKareemSh.abdallahKamel/SuretAlnas.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
						</div>  
			</div>  
			<div class="row reciter-container">   
					<div class="col-md-4 col-sm-6"><iframe width="100%" height="250" src="//www.youtube.com/embed/BSqkkfZY9Vs?rel=0" frameborder="0" allowfullscreen></iframe>  
						<a href="" class="btn btn-primary btn-lg btn-block" role="button">Download Mp3</a>
					</div> 
					<div class="col-md-4 col-sm-6"><iframe width="100%" height="250" src="//www.youtube.com/embed/BB1HyIBHJVA?rel=0" frameborder="0" allowfullscreen></iframe>
						<a href="" class="btn btn-primary btn-lg btn-block" role="button">Download Mp3</a>
					</div> 
					<div class="col-md-4 col-sm-6"><iframe width="100%" height="250" src="//www.youtube.com/embed/EVBoRt9rGBM?rel=0" frameborder="0" allowfullscreen></iframe>
						<a href="" class="btn btn-primary btn-lg btn-block" role="button">Download Mp3</a>
					</div>  
					<div class="col-md-4 col-sm-6"><iframe width="100%" height="250" src="//www.youtube.com/embed/yARUQ_Ru3mk?rel=0" frameborder="0" allowfullscreen></iframe>
						<a href="" class="btn btn-primary btn-lg btn-block" role="button">Download Mp3</a>
					</div>	   
		    </div> 	
			<div class="row reciter-container">		 
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>  
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p >Kareem Sh. Abdallah Kamel is an Amazing Blind Reciter. Must listen!</p>
				</div>  	
			</div>

		</diV>
			 



			
		</div>
				  		
		
<?php  include $path . '/pages/footer.php'; ?>

