<?php  
	$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>   
			</div> 	
	        <div class="row reciter-container">	  
					   <div class="row btns-player-catagory">  
							<a href='#' class=" btn btn-success" role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#playlist1'}); return false;"><i class="fa fa-book"></i> Ramadan 2015 - Al Furqaan Education Centre Bradford, England </a> 
							<a href='#' class=" btn " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#ramadan-2012'}); return false;"><i class="fa fa-book"></i> Ramadan 2012 </a>
							
							 <a href='#' class=" btn " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#ramadan-2011'}); return false;"><i class="fa fa-book"></i> Ramadan 2011</a> 
							<a href='#' class=" btn " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#selected-surahs'}); return false;"><i class="fa fa-book"></i> Selected Surahs</a> 

							<a href='#' class=" btn " role="button" onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#mixed'}); return false;"><i class="fa fa-book"></i> Mixed Recitations</a>  

							<a href='#' class="btn btn-black" role="button"  onClick="api_loadPlaylist(hap_players[0],{hidden: false, id: '#clear'}); return false;"><i class="fa fa-bars"></i> Clear</a> 
						<script>
							$(function() {
							  $('.btn').click( function() {
								$(this).addClass('btn-success').siblings().removeClass('btn-success');
							  });
							});
						</script>
						</div> 
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
							<!-- local playlist --> 
							<ul id='ramadan-2011'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim//Saad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Saad </a><a class='dlink' href=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Saad.mp3' data-dlink=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Saad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim//Taha.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Taha </a><a class='dlink' href=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Taha.mp3' data-dlink=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Taha.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim//Al-Furqaan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Furqaan </a><a class='dlink' href=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Al-Furqaan.mp3' data-dlink=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Al-Furqaan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim//Al-Hujuraat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hujuraat </a><a class='dlink' href=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Al-Hujuraat.mp3' data-dlink=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Al-Hujuraat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim//Al-Ankaboot.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ankaboot </a><a class='dlink' href=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Al-Ankaboot.mp3' data-dlink=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Al-Ankaboot.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim//Al-Ahzaab.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ahzaab </a><a class='dlink' href=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Al-Ahzaab.mp3' data-dlink=' https://archive.org/download/Ramadhan2011MuhammadUthmanAlQasim/Al-Ahzaab.mp3'><img src='media/data/dlink.png' alt = ''/></a></li> 
							</ul>
							<ul id='ramadan-2012'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim//Al-Maaidah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Maaidah </a><a class='dlink' href=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Maaidah.mp3' data-dlink=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Maaidah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim//Al-Baqarah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah </a><a class='dlink' href=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Baqarah.mp3' data-dlink=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Baqarah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim//Al-Nisaa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Nisaa </a><a class='dlink' href=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Nisaa.mp3' data-dlink=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Nisaa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim//Al-Anfaal.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anfaal </a><a class='dlink' href=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Anfaal.mp3' data-dlink=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Anfaal.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim//Al-Anaam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anaam </a><a class='dlink' href=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Anaam.mp3' data-dlink=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Anaam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim//Yusuf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf </a><a class='dlink' href=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Yusuf.mp3' data-dlink=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Yusuf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim//Al-Nahl.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Nahl </a><a class='dlink' href=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Nahl.mp3' data-dlink=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Al-Nahl.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim//Muminoon.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Muminoon </a><a class='dlink' href=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Muminoon.mp3' data-dlink=' https://archive.org/download/Ramadhan2012-QariMUthmanAl-Qasim/Muminoon.mp3'><img src='media/data/dlink.png' alt = ''/></a></li> 
							</ul>
							<ul id='playlist1'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/AlFurqaanEducationCentreFacebook//Al-Furqaan Education Centre - Facebook.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah [190-202] </a><a class='dlink' href=' https://archive.org/download/AlFurqaanEducationCentreFacebook/Al-Furqaan Education Centre - Facebook.mp3' data-dlink=' https://archive.org/download/AlFurqaanEducationCentreFacebook/Al-Furqaan Education Centre - Facebook.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
							<ul id='clear'> 
							
							</ul>
							<ul id='mixed'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//(Surah Hashr) Green Lane Masjid.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qasim (Surah Hashr) Green Lane Masjid </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/(Surah Hashr) Green Lane Masjid.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/(Surah Hashr) Green Lane Masjid.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//[HQ] Qari Muhammad Uthman Al-Qasim - Zakariyya Masjid Bolton Dec 10-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>[HQ] Qari Muhammad Uthman Al-Qasim - Zakariyya Masjid Bolton Dec 10-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/[HQ] Qari Muhammad Uthman Al-Qasim - Zakariyya Masjid Bolton Dec 10-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/[HQ] Qari Muhammad Uthman Al-Qasim - Zakariyya Masjid Bolton Dec 10-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//FOSIS Conference Tahajjud Prayer from Masjid Doha .mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>FOSIS Conference Tahajjud Prayer from Masjid Doha </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/FOSIS Conference Tahajjud Prayer from Masjid Doha .mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/FOSIS Conference Tahajjud Prayer from Masjid Doha .mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Furqaan Centre 2013 - Day 10 - Qari Umar Muhammad .mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Furqaan Centre 2013 - Day 10 - Qari Umar Muhammad </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Furqaan Centre 2013 - Day 10 - Qari Umar Muhammad .mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Furqaan Centre 2013 - Day 10 - Qari Umar Muhammad .mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Furqaan from Taraweeh Prayer Ramadhan 2009 - Muham.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Furqaan from Taraweeh Prayer Ramadhan 2009 - Muham </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Furqaan from Taraweeh Prayer Ramadhan 2009 - Muham.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Furqaan from Taraweeh Prayer Ramadhan 2009 - Muham.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Imraan from Tahajjud Prayer- Muhammad Uthman Al-Qa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Imraan from Tahajjud Prayer- Muhammad Uthman Al-Qa </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Imraan from Tahajjud Prayer- Muhammad Uthman Al-Qa.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Imraan from Tahajjud Prayer- Muhammad Uthman Al-Qa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Kahf from Tahajjud Prayer - Muhammad Uthman Al-Qas (1).mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Kahf from Tahajjud Prayer - Muhammad Uthman Al-Qas </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Kahf from Tahajjud Prayer - Muhammad Uthman Al-Qas (1).mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Kahf from Tahajjud Prayer - Muhammad Uthman Al-Qas (1).mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Kahf from Tahajjud Prayer - Muhammad Uthman Al-Qas.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Kahf from Tahajjud Prayer - Muhammad Uthman Al-Qas </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Kahf from Tahajjud Prayer - Muhammad Uthman Al-Qas.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Kahf from Tahajjud Prayer - Muhammad Uthman Al-Qas.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Naba - Muhammad Uthman Al-Qasim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Naba - Muhammad Uthman Al-Qasim </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Naba - Muhammad Uthman Al-Qasim.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Naba - Muhammad Uthman Al-Qasim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Part 1 Al-Kahf from Tahajjud Prayer 02092010 - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Part 1 Al-Kahf from Tahajjud Prayer 02092010 - Muhammad Uthman Al-Qasim-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Part 1 Al-Kahf from Tahajjud Prayer 02092010 - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Part 1 Al-Kahf from Tahajjud Prayer 02092010 - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Part 1 Juz Amma from Taraweeh Prayer Ramadhan 2009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Part 1 Juz Amma from Taraweeh Prayer Ramadhan 2009 </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Part 1 Juz Amma from Taraweeh Prayer Ramadhan 2009.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Part 1 Juz Amma from Taraweeh Prayer Ramadhan 2009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Part 2 Juz Amma from Taraweeh Prayer Ramadhan 2009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Part 2 Juz Amma from Taraweeh Prayer Ramadhan 2009 </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Part 2 Juz Amma from Taraweeh Prayer Ramadhan 2009.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Part 2 Juz Amma from Taraweeh Prayer Ramadhan 2009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Part 2 of 3 - Surah Al-Furqaan - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Part 2 of 3 - Surah Al-Furqaan - Muhammad Uthman Al-Qasim-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Part 2 of 3 - Surah Al-Furqaan - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Part 2 of 3 - Surah Al-Furqaan - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Part 3 Juz Amma from Taraweeh Prayer Ramadhan 2009 (1).mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Part 3 Juz Amma from Taraweeh Prayer Ramadhan 2009 </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Part 3 Juz Amma from Taraweeh Prayer Ramadhan 2009 (1).mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Part 3 Juz Amma from Taraweeh Prayer Ramadhan 2009 (1).mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Part 3 Juz Amma from Taraweeh Prayer Ramadhan 2009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Part 3 Juz Amma from Taraweeh Prayer Ramadhan 2009 </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Part 3 Juz Amma from Taraweeh Prayer Ramadhan 2009.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Part 3 Juz Amma from Taraweeh Prayer Ramadhan 2009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Part 3 of 3 - Surah Al-Furqaan - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Part 3 of 3 - Surah Al-Furqaan - Muhammad Uthman Al-Qasim-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Part 3 of 3 - Surah Al-Furqaan - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Part 3 of 3 - Surah Al-Furqaan - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Qasim - Light of Guidance Seminar Opening Recitati.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qasim - Light of Guidance Seminar Opening Recitati </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Qasim - Light of Guidance Seminar Opening Recitati.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Qasim - Light of Guidance Seminar Opening Recitati.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Qasim (Makkah) Masjid Bilal.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qasim (Makkah) Masjid Bilal </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Qasim (Makkah) Masjid Bilal.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Qasim (Makkah) Masjid Bilal.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Recitation from Surah Al-Baqarah - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Recitation from Surah Al-Baqarah - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Recitation from Surah Al-Baqarah - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Recitation from Surah Al-Baqarah - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Recitation of The Holy Quraan from Surah Aal-Imraan (23-37) - Qari Muhammad Uthman Al-Qasim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Aal-Imraan (23-37) </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Recitation of The Holy Quraan from Surah Aal-Imraan (23-37) - Qari Muhammad Uthman Al-Qasim.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Recitation of The Holy Quraan from Surah Aal-Imraan (23-37) - Qari Muhammad Uthman Al-Qasim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Salah Al-Fajr 2010 - Muhammad Uthman Al-Qasim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Salah Al-Fajr 2010 </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Salah Al-Fajr 2010 - Muhammad Uthman Al-Qasim.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Salah Al-Fajr 2010 - Muhammad Uthman Al-Qasim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Sourate Al Mulk - Muhammad Uthman Al Qasim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Sourate Al Mulk </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Sourate Al Mulk - Muhammad Uthman Al Qasim.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Sourate Al Mulk - Muhammad Uthman Al Qasim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Surah Al-Furqaan - Muhammad Uthman Al-Qasim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Furqaan - Muhammad Uthman Al-Qasim </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Furqaan - Muhammad Uthman Al-Qasim.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Furqaan - Muhammad Uthman Al-Qasim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Surah Al-Mulk - Qari' Muhammad 'Uthman Al-Qasim - Steps to Allah Conference, London 2012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Mulk - Qari' Muhammad 'Uthman Al-Qasim - Steps to Allah Conference, London 2012 </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Mulk - Qari' Muhammad 'Uthman Al-Qasim - Steps to Allah Conference, London 2012.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Mulk - Qari' Muhammad 'Uthman Al-Qasim - Steps to Allah Conference, London 2012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Surah Al-Naba' - Qari' Muhammad 'Uthman Al-Qasim - Steps to Allah Conference, London 2012-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Naba' - Qari' Muhammad 'Uthman Al-Qasim - Steps to Allah Conference, London 2012-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Naba' - Qari' Muhammad 'Uthman Al-Qasim - Steps to Allah Conference, London 2012-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Naba' - Qari' Muhammad 'Uthman Al-Qasim - Steps to Allah Conference, London 2012-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Surah Al-Qiyaamah The End of Times Conference - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qiyaamah The End of Times Conference - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Qiyaamah The End of Times Conference - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Qiyaamah The End of Times Conference - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Surah Al-Qiyamah (Beautiful Recitation).mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Qiyamah (Beautiful Recitation) </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Qiyamah (Beautiful Recitation).mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Qiyamah (Beautiful Recitation).mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Surah Al-Zumar - Pearls of Wisdom Event, 3D Centre Bolton UK - Qari' Muhammad 'Uthman Al-Qasim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Al-Zumar - Pearls of Wisdom Event, 3D Centre Bolton UK - Qari' Muhammad 'Uthman Al-Qasim </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Zumar - Pearls of Wisdom Event, 3D Centre Bolton UK - Qari' Muhammad 'Uthman Al-Qasim.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Al-Zumar - Pearls of Wisdom Event, 3D Centre Bolton UK - Qari' Muhammad 'Uthman Al-Qasim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Surah Ibraheem from Rahma Quraan Tour UK - Glasgow - Qari Muhammad Uthman Al-Qasim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Ibraheem </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Ibraheem from Rahma Quraan Tour UK - Glasgow - Qari Muhammad Uthman Al-Qasim.mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Ibraheem from Rahma Quraan Tour UK - Glasgow - Qari Muhammad Uthman Al-Qasim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Surah Nuh - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Nuh - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Nuh - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Nuh - Qari' Muhammad 'Uthman Al-Qasim-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Surah Yusuf Taraweeh Prayer - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Surah Yusuf Taraweeh Prayer - Muhammad Uthman Al-Qasim-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Yusuf Taraweeh Prayer - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Surah Yusuf Taraweeh Prayer - Muhammad Uthman Al-Qasim-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Taraweeh Prayer at Al-Furqaan Centre 2013 - Day 8 Part 1 - Qari' Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Taraweeh Prayer at Al-Furqaan Centre 2013 - Day 8 Part 1 - Qari' Muhammad Uthman Al-Qasim-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Taraweeh Prayer at Al-Furqaan Centre 2013 - Day 8 Part 1 - Qari' Muhammad Uthman Al-Qasim-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Taraweeh Prayer at Al-Furqaan Centre 2013 - Day 8 Part 1 - Qari' Muhammad Uthman Al-Qasim-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/muhammad-uthman-al-qasim//Very Beautiful Recitation by Muhammad Uthmaan Al Qasem (Isha Salah 1425)-[www_flvto_com].mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Very Beautiful Recitation by Muhammad Uthmaan Al Qasem (Isha Salah 1425)-[www_flvto_com] </a><a class='dlink' href=' https://archive.org/download/muhammad-uthman-al-qasim/Very Beautiful Recitation by Muhammad Uthmaan Al Qasem (Isha Salah 1425)-[www_flvto_com].mp3' data-dlink=' https://archive.org/download/muhammad-uthman-al-qasim/Very Beautiful Recitation by Muhammad Uthmaan Al Qasem (Isha Salah 1425)-[www_flvto_com].mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
								
								
								
						    <ul id='selected-surahs'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//2-ma2idah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáãÇÆÏÉ </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/2-ma2idah.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/2-ma2idah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//3-Al-Nisaa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>3-Al-Nisaa </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/3-Al-Nisaa.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/3-Al-Nisaa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//3-hajj.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáÍÌ </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/3-hajj.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/3-hajj.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//4_furqan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáÝÑÞÇä </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/4_furqan.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/4_furqan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//4-Al-Ma'idah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>4-Al-Ma'idah </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/4-Al-Ma'idah.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/4-Al-Ma'idah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//5_ahzab.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáÃÍÒÇÈ </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/5_ahzab.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/5_ahzab.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//5_sajdah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáÓÌÏÉ </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/5_sajdah.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/5_sajdah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//6_mudatthir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáãÏËÑ </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/6_mudatthir.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/6_mudatthir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//7_insan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÇáÅäÓÇä </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/7_insan.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/7_insan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Aal_Imraan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Aal-Imraan 2010 </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Aal_Imraan.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Aal_Imraan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Al_Anaam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-An'aam </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al_Anaam.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al_Anaam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//al_anfaal.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>al_anfaal </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/al_anfaal.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/al_anfaal.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Al_Baqarah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah 2010 </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al_Baqarah.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al_Baqarah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//al_tawbah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>al_tawbah </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/al_tawbah.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/al_tawbah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Al-Baqarah-2007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah-2007 </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al-Baqarah-2007.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al-Baqarah-2007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Al-Qalam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qalam 2007 </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al-Qalam.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al-Qalam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Al-Zumer-Tareweeh.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Zumar 2007 </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al-Zumer-Tareweeh.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Al-Zumer-Tareweeh.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Ibraheem_202010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibraheem 2010 </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Ibraheem_202010.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Ibraheem_202010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//isha_ahzab.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>isha_ahzab </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/isha_ahzab.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/isha_ahzab.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Jmua_39_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>ÕáÇÉ ÇáãÛÑÈ ãä ãÓÌÏ ÇáÞØÇä </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Jmua_39_.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Jmua_39_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//surah naml.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>surah naml </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/surah naml.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/surah naml.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Yunus_202010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yunus 2010 </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Yunus_202010.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Yunus_202010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Yusuf_202009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf_202009 </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Yusuf_202009.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Yusuf_202009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//Yusuf_202010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf 2010 </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Yusuf_202010.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/Yusuf_202010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//1-aal_imran.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Âá ÚãÑÇä </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/1-aal_imran.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/1-aal_imran.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim//1-Al-Baqarah.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>1-Al-Baqarah </a><a class='dlink' href=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/1-Al-Baqarah.mp3' data-dlink=' https://archive.org/download/selected-surahs-muhammad-uthman-al-qasim/1-Al-Baqarah.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
						</div>  
		   </div>	 
            <div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>  
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
				 

 
			<div class="row reciter-container">
				<div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>  
				<div id="reciter-bio">
					<p>official website <a href="http://alqasimproductions.com">alqasimproductions.com</a></p>
					<p>Qari’ Muhammad Uthman Al-Qasim was born and raised in the United Kingdom where he completed his primary, secondary and higher education. He completed his memorisation of the Holy Qur’aan in a short period of two months at Jam’iyyah Al-Muhaafadhah ‘alal-Qur’aanil Kareem in Zarqaa’, Jordan, in 2004/1425AH.
					<br><br>
					Qari’ Uthman has led taraweeh prayers in the Holy Month of Ramadhaan since 1998 and continues to do so both within the UK and internationally, including Makkah, Kuwait and USA. His recordings are available worldwide. In 2007 Qari’ Uthman was appointed Imam of masjid Al-Qattaan in Makkah, where he led Taraweeh and Tahajjud prayers. In 2010 he undertook the position of Imam and Khateeb at the Muslim Community Centre in Surrey, London. Furthermore, Qari’ Uthman is often invited as a guest reciter for various Islamic events both nationally and internationally.<br><br>

					Qari’ Uthman has taught the recitation of the Qur’aan for over 15 years as well as Arabic Language, holding private and public classes through Islamic organisations for memorising the Qur’aan, studying Tajweed and ‘the art of recitation’. <br><br>

					Qari’ Uthman Al-Qasim is currently the director and lead instructor at Al Tibyan Institute, a specialist online institute for Tajweed, Qiraa’ah & Hifdh at www.LearnTheQuran.com.</p>
				</div>  	
			</div>
			
</div>


<?php  include $path . '/pages/footer.php'; ?>