<?php  
		$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div>	
	        <div class="row reciter-container">	  
					   <div class=" archive-playlist-title">
											<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
						</div>
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='playlist1'>  
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//001.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fatihah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/001.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/001.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hood </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/011.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taubah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/009.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//005.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'idah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/005.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/005.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//006.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-An'am </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/006.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/006.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'raf </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/007.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//003.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Imran </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/003.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/003.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//004.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nisa' </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/004.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/004.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/012.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yunus </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/010.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//016.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nahl </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/016.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/016.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//028.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qasas </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/028.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/028.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//024.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nur </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/024.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/024.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//018.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kahf </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/018.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/018.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//017.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Isra </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/017.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/017.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//033.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al­Ahzab </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/033.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/033.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//040.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ghafir </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/040.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/040.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//039.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zumar </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/039.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/039.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//026.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shu'ara' </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/026.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/026.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//022.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hajj </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/022.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/022.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//029.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Ankabut </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/029.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/029.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anfal </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/008.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//027.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naml </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/027.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/027.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//020.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ta­Ha </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/020.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/020.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//002.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/002.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/002.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//023.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mu'minun </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/023.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/023.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//034.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Saba' </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/034.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/034.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//021.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anbiya' </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/021.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/021.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//037.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saffat </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/037.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/037.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//041.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fussilat </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/041.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/041.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//025.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Furqan </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/025.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/025.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//042.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shura </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/042.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/042.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//013.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Ra'd </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/013.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/013.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//043.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zukhruf </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/043.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/043.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//038.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Sad </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/038.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/038.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//035.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fatir </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/035.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/035.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//019.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maryam </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/019.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/019.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//030.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar­Room </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/030.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/030.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//014.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/014.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/014.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//057.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hadid </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/057.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/057.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//036.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ya­Sin </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/036.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/036.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//048.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fath </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/048.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/048.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//015.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hijr </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/015.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/015.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//046.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ahqaf </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/046.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/046.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//047.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Muhammad </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/047.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/047.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//031.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/031.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/031.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//045.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jathiya </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/045.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/045.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//059.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hashr </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/059.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/059.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//058.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mujadilah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/058.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/058.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//050.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qaf </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/050.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/050.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//055.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Rahman </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/055.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/055.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//056.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Waqi'ah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/056.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/056.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//053.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Najm </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/053.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/053.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//060.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mumtahinah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/060.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/060.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//032.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As­Sajdah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/032.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/032.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//054.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qamar </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/054.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/054.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//049.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hujurat </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/049.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/049.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//065.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Talaq </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/065.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/065.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//044.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Dukhan </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/044.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/044.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//067.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mulk </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/067.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/067.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//068.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qalam </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/068.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/068.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//051.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zariyat </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/051.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/051.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//052.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tur </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/052.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/052.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//076.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Insan </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/076.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/076.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//072.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jinn </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/072.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/072.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//069.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Haqqah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/069.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/069.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//066.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tahrim </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/066.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/066.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//071.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nooh </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/071.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/071.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//074.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muddaththir </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/074.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/074.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//061.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saff </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/061.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/061.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//070.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'arij </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/070.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/070.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//083.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mutaffifin </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/083.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/083.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//063.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Munafiqun </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/063.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/063.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//079.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nazi'at </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/079.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/079.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//078.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naba' </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/078.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/078.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//077.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mursalat </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/077.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/077.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//064.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taghabun </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/064.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/064.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//073.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muzzammil </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/073.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/073.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//062.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jumu'ah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/062.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/062.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//081.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takwir </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/081.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/081.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//085.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Buruj </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/085.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/085.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//075.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qiyamah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/075.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/075.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//084.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Inshiqaq </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/084.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/084.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//098.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baiyinah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/098.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/098.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//080.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>'Abasa </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/080.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/080.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//089.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fajr </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/089.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/089.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//088.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ghashiyah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/088.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/088.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//082.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Infitar </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/082.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/082.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//090.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Balad </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/090.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/090.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//092.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Lail </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/092.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/092.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//087.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'la </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/087.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/087.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//100.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Adiyat </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/100.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/100.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//099.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zalzalah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/099.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/099.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//096.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Alaq </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/096.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/096.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//086.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tariq </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/086.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/086.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//095.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tin </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/095.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/095.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//091.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shams </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/091.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/091.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//093.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Duha </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/093.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/093.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//101.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qari'ah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/101.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/101.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//102.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takathur </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/102.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/102.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//104.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Humazah </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/104.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/104.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//105.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fil </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/105.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/105.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//107.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'un </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/107.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/107.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//094.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Sharh </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/094.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/094.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//097.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qadr </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/097.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/097.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//110.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nasr </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/110.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/110.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//114.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nas </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/114.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/114.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//111.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Masad </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/111.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/111.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//109.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kafirun </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/109.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/109.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//106.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Quraish </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/106.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/106.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//112.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ikhlas </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/112.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/112.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//113.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Falaq </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/113.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/113.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//103.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Asr </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/103.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/103.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/www.elahmad.com_73//108.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kauthar </a><a class='dlink' href=' https://archive.org/download/www.elahmad.com_73/108.mp3' data-dlink=' https://archive.org/download/www.elahmad.com_73/108.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
						</div>  
			</div> 
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>  
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>Muhammad- Muhammad Al Said Hussayn Jebril is known in the Islamic world as “Sheikh Jebril”. He got the B.A degree in Islamic Law at Al-Azhar University. He learned Koran by the age of 9. More that once, Sheikh Jebril won the Egyptian and international competitions of Koran recitation. He was named as Imam of the famous mosque Amr Ibn Al’Ass in Cairo in 1988. Every year, thousands of people rush to the mosque during Ramadan to attend the Tarawih prayers that are lead by him. Sheikh Muhammad Jebril is, also, a University professor in Jordan. He has plenty of complete recitations of Koran. He took part and organised several TV shows in lots of Arab channels around the Koranic theme. At last, Sheikh Jebril is especially admired for the quality of his “Dou’as Al Qunût” (Invocations during prayer).
					</p>
				</div>  	
			</div>
			
</div>			



<?php  include $path . '/pages/footer.php'; ?>