<?php  
		$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $mujawwads["$basename"]; 
	
	$videos = array("ENTY9pn3jSU","0v__3ICN5gk","qaOTwbvf2wU","boJSrR1c2JI","EsY-8ZHZjtw","I7WmoIFpWqo");
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div>	
	        <div class="row reciter-container">	  
					   <div class=" archive-playlist-title">
											<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
						</div>
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='playlist1'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//001.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fatihah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/001.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/001.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//002.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/002.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/002.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//003.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Imran </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/003.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/003.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//004.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nisa' </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/004.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/004.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//005.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'idah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/005.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/005.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//006.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-An'am </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/006.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/006.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'raf </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/007.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anfal </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/008.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taubah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/009.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yunus </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/010.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hood </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/011.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/012.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//013.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Ra'd </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/013.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/013.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//014.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/014.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/014.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//015.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hijr </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/015.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/015.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//016.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nahl </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/016.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/016.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//017.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Isra </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/017.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/017.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//018.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kahf </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/018.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/018.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//019.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maryam </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/019.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/019.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//020.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ta­Ha </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/020.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/020.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//021.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anbiya' </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/021.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/021.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//022.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hajj </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/022.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/022.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//023.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mu'minun </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/023.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/023.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//024.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nur </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/024.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/024.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//025.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Furqan </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/025.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/025.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//026.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shu'ara' </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/026.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/026.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//027.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naml </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/027.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/027.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//028.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qasas </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/028.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/028.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//029.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Ankabut </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/029.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/029.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//030.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar­Room </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/030.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/030.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//031.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/031.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/031.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//032.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As­Sajdah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/032.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/032.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//033.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al­Ahzab </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/033.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/033.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//034.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Saba' </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/034.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/034.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//035.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fatir </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/035.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/035.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//036.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ya­Sin </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/036.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/036.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//037.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saffat </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/037.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/037.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//038.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Sad </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/038.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/038.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//039.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zumar </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/039.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/039.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//040.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ghafir </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/040.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/040.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//041.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fussilat </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/041.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/041.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//042.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shura </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/042.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/042.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//043.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zukhruf </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/043.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/043.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//044.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Dukhan </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/044.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/044.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//045.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jathiya </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/045.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/045.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//046.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ahqaf </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/046.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/046.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//047.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Muhammad </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/047.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/047.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//048.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fath </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/048.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/048.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//049.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hujurat </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/049.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/049.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//050.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qaf </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/050.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/050.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//051.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zariyat </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/051.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/051.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//052.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tur </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/052.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/052.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//053.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Najm </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/053.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/053.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//054.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qamar </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/054.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/054.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//055.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Rahman </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/055.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/055.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//056.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Waqi'ah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/056.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/056.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//057.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hadid </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/057.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/057.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//058.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mujadilah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/058.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/058.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//059.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hashr </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/059.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/059.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//060.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mumtahinah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/060.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/060.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//061.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saff </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/061.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/061.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//062.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jumu'ah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/062.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/062.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//063.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Munafiqun </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/063.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/063.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//064.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taghabun </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/064.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/064.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//065.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Talaq </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/065.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/065.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//066.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tahrim </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/066.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/066.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//067.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mulk </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/067.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/067.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//068.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qalam </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/068.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/068.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//069.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Haqqah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/069.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/069.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//070.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'arij </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/070.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/070.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//071.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nooh </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/071.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/071.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//072.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jinn </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/072.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/072.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//073.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muzzammil </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/073.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/073.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//074.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muddaththir </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/074.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/074.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//075.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qiyamah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/075.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/075.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//076.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Insan </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/076.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/076.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//077.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mursalat </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/077.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/077.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//078.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naba' </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/078.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/078.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//079.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nazi'at </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/079.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/079.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//080.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>'Abasa </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/080.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/080.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//081.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takwir </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/081.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/081.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//082.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Infitar </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/082.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/082.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//083.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mutaffifin </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/083.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/083.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//084.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Inshiqaq </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/084.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/084.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//085.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Buruj </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/085.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/085.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//086.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tariq </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/086.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/086.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//087.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'la </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/087.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/087.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//088.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ghashiyah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/088.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/088.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//089.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fajr </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/089.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/089.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//090.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Balad </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/090.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/090.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//091.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shams </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/091.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/091.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//092.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Lail </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/092.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/092.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//093.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Duha </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/093.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/093.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//094.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Sharh </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/094.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/094.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//095.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tin </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/095.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/095.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//096.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Alaq </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/096.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/096.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//097.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qadr </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/097.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/097.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//098.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baiyinah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/098.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/098.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//099.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zalzalah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/099.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/099.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//100.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Adiyat </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/100.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/100.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//101.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qari'ah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/101.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/101.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//102.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takathur </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/102.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/102.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//103.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Asr </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/103.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/103.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//104.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Humazah </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/104.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/104.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//105.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fil </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/105.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/105.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//106.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Quraish </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/106.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/106.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//107.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'un </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/107.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/107.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//108.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kauthar </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/108.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/108.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//109.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kafirun </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/109.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/109.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//110.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nasr </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/110.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/110.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//111.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Masad </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/111.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/111.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//112.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ikhlas </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/112.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/112.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//113.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Falaq </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/113.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/113.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//114.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nas </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/114.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/114.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//115-.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>115 الشيخ نور الدين محمد الوكيل - نعمة القرآن </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/115-.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/115-.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//117.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>117 كيف تحفظ القرآن ؟ </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/117.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/117.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran//116.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>116 طرق ابداعيه لحفظ القران الكريم </a><a class='dlink' href=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/116.mp3' data-dlink=' https://archive.org/download/MuhammedSiddiqAl-minshawi-TheCompleteHolyQuran/116.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
						</div>  
			</div>	 	
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div> 
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">	
					<?php
						foreach($videos as $video){
							echo '<div class="col-md-4 col-sm-6"><iframe width="100%" height="250" src="//www.youtube.com/embed/';
							echo $video;
							echo '?rel=0" frameborder="0" allowfullscreen></iframe> <a href="http://www.yt-mp3.com/watch?v=';
							echo $video;
							echo '"  onClick="return YoutubeMp3Script(this)" class="btn btn-danger btn-lg btn-block" role="button"><i class="fa fa-music"> Download Mp3</i></a> </div> '; 
						} 
					?>
			 
		    </div>  
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة <strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>Muhammed Siddiq Al Minshawi is one of the top readers of the Quran, he was born in 1920 in the village 'Munsha'a' of Sohag Governorate. He is originary from an ancient prophecy verses family, he's father is the Sheikh Seddiq EL Minshawi and his brother is the Sheikh Mahmoud El Minshawi. <br><br>

					Sheikh Mohamed Siddiq El Minshawi completed the conservation of the Holy Quran in the age of 8.<br>

					Known for the beauty of his voice and his ability to transport through his recitations all deep meanings of Koranic words.

					Sheikh Mohamed Siddiq El Minshawi explained the full registration of the Holy Qur'an Choir, and has also made many recordings in the Al Aqsa Mosque, Kuwait, Syria and Libya.....<br><br> 

					Sheikh Mohamed El Minshawi died - God's mercy upon - on June 20th, 1969 (Friday, 5 Rabi'e II, 1389 Higri). source: assabile</p>
				</div>  	
			</div> 
			


</div> 


		 

<?php  include $path . '/pages/footer.php'; ?>		

				