<?php  
	$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"];  
	
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div>	
	        <div class="row reciter-container">	  
					   <div class=" archive-playlist-title">
											<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
						</div>
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='playlist1'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//001salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fatihah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/001salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/001salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//002salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/002salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/002salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//003salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Imran </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/003salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/003salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//004salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nisa' </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/004salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/004salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//005salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'idah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/005salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/005salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//006salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-An'am </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/006salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/006salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//007salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'raf </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/007salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/007salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//008salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anfal </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/008salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/008salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//009salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taubah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/009salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/009salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//010salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yunus </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/010salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/010salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//011salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hood </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/011salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/011salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//012salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/012salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/012salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//013salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Ra'd </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/013salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/013salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//014salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/014salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/014salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//015salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hijr </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/015salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/015salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//016salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nahl </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/016salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/016salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//017salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Isra </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/017salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/017salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//018salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kahf </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/018salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/018salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//019salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maryam </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/019salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/019salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//020salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ta­ha </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/020salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/020salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//021salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anbiya' </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/021salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/021salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//022salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hajj </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/022salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/022salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//023salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mu'minun </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/023salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/023salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//024salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nur </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/024salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/024salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//025salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Furqan </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/025salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/025salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//026salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shu'ara' </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/026salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/026salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//027salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naml </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/027salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/027salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//028salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qasas </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/028salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/028salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//029salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'ankabut </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/029salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/029salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//030salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar­room </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/030salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/030salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//031salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/031salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/031salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//032salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As­sajdah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/032salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/032salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//033salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al­ahzab </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/033salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/033salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//034salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Saba' </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/034salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/034salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//035salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fatir </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/035salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/035salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//036salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ya­sin </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/036salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/036salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//037salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saffat </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/037salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/037salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//038salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Sad </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/038salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/038salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//039salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zumar </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/039salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/039salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//040salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ghafir </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/040salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/040salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//041salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fussilat </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/041salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/041salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//042salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shura </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/042salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/042salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//043salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zukhruf </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/043salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/043salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//044salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Dukhan </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/044salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/044salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//045salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jathiya </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/045salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/045salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//046salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ahqaf </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/046salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/046salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//047salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Muhammad </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/047salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/047salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//048salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fath </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/048salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/048salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//049salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hujurat </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/049salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/049salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//050salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qaf </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/050salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/050salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//051salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zariyat </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/051salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/051salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//052salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tur </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/052salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/052salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//053salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Najm </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/053salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/053salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//054salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qamar </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/054salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/054salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//055salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Rahman </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/055salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/055salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//056salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Waqi'ah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/056salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/056salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//057salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hadid </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/057salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/057salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//058salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mujadilah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/058salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/058salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//059salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hashr </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/059salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/059salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//060salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mumtahinah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/060salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/060salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//061salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saff </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/061salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/061salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//062salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jumu'ah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/062salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/062salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//063salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Munafiqun </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/063salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/063salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//064salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taghabun </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/064salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/064salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//065salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Talaq </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/065salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/065salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//066salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tahrim </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/066salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/066salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//067salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mulk </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/067salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/067salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//068salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qalam </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/068salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/068salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//069salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Haqqah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/069salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/069salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//070salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'arij </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/070salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/070salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//071salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nooh </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/071salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/071salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//072salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jinn </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/072salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/072salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//073salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muzzammil </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/073salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/073salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//074salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muddaththir </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/074salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/074salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//075salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qiyamah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/075salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/075salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//076salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Insan </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/076salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/076salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//077salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mursalat </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/077salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/077salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//078salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naba' </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/078salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/078salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//079salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nazi'at </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/079salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/079salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//080salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>'abasa </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/080salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/080salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//081salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takwir </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/081salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/081salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//082salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Infitar </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/082salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/082salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//083salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mutaffifin </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/083salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/083salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//084salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Inshiqaq </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/084salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/084salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//085salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Buruj </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/085salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/085salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//086salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tariq </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/086salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/086salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//087salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'la </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/087salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/087salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//088salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ghashiyah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/088salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/088salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//089salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fajr </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/089salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/089salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//090salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Balad </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/090salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/090salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//091salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shams </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/091salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/091salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//092salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Lail </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/092salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/092salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//093salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Duha </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/093salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/093salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//094salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Sharh </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/094salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/094salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//095salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tin </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/095salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/095salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//096salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'alaq </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/096salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/096salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//097salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qadr </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/097salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/097salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//098salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baiyinah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/098salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/098salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//099salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zalzalah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/099salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/099salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//100salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'adiyat </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/100salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/100salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//101salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qari'ah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/101salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/101salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//102salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takathur </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/102salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/102salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//103salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'asr </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/103salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/103salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//104salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Humazah </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/104salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/104salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//105salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fil </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/105salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/105salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//106salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Quraish </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/106salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/106salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//107salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'un </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/107salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/107salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//108salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kauthar </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/108salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/108salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//109salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kafirun </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/109salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/109salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//110salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nasr </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/110salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/110salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//111salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Masad </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/111salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/111salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//112salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ikhlas </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/112salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/112salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//113salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Falaq </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/113salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/113salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/sunna4u.blogspot.com_salahBD//114salahAlBudair_www.tsagero.yn.lt_.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nas </a><a class='dlink' href=' https://archive.org/download/sunna4u.blogspot.com_salahBD/114salahAlBudair_www.tsagero.yn.lt_.mp3' data-dlink=' https://archive.org/download/sunna4u.blogspot.com_salahBD/114salahAlBudair_www.tsagero.yn.lt_.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
						</div>  
			</div>  	
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>  
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<?php echo $current["Salah"] ?>
					<p>Salah Bin Muhammad Al Budair (born Hofuf, 1970) was a former Imam of Al-Masjid al-Haram, and is a current Imam of the Grand mosque in Medina and a Judge of the High Court of Madina. He is considered as one of the most fascinating reciters of the Quran in world..	<br><br>

						Salah Al Budair was born in the region of Al-Ahsa, Saudi Arabia. He became an Imam when he was still 15 years old. In 1985 he led prayer alongside with his teacher, Shaykh Ahmed As-Salmy, who was the governor of Al-Ahsa Governorate.<br><br>
						He is graduated from Imam Muhammad ibn Saud Islamic University in bachelor degree in Islamic law. He also studied in Institute of Higher learning in magistracy. At the beginning, he had been appointed as an Imam in Dammam, after that he moved in Riyadh, thereafter in 2005 & 2006, he was appointed as the Imam of Al-Masjid al-Haram, and finally he became an permanent Imam and Khateeb of Al-Masjid al-Nabawi in Medina, aswell as being its Head and Deputy Chief.<br><br>

						Salah al Budair is from Banu Tamin tribe. He is the eldest son of his family. He has a younger brother, Sheikh Nabeel. The brothers' voices are different but the style of the holy Quran recitation is similar. Currently he lives in Medina.<br><br>
						source: wikipedia
					    </p>
						<p> </p>
				</div>  	
			</div>    

 </div>
  
		
<?php  include $path . '/pages/footer.php'; ?>

