<?php  
		$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div>	
	        <div class="row reciter-container">	  
					   <div class=" archive-playlist-title">
											<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
						</div>
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='playlist1'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//001.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fatihah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/001.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/001.mp3'><img src='media/data/dlink.png' alt = ''/></a></li> 
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//002.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baqarah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/002.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/002.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//003.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Imran </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/003.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/003.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//004.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nisa' </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/004.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/004.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//005.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'idah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/005.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/005.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//006.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-An'am </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/006.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/006.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//007.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'raf </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/007.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/007.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//008.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anfal </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/008.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/008.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//009.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taubah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/009.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/009.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//010.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yunus </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/010.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/010.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//011.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Hood </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/011.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/011.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//012.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Yusuf </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/012.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/012.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//013.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Ra'd </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/013.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/013.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//014.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ibrahim </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/014.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/014.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//015.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hijr </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/015.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/015.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//016.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nahl </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/016.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/016.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//017.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Isra </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/017.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/017.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//018.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kahf </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/018.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/018.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//019.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Maryam </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/019.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/019.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//020.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ta­Ha </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/020.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/020.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//021.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Anbiya' </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/021.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/021.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//022.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hajj </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/022.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/022.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//023.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mu'minun </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/023.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/023.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//024.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nur </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/024.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/024.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//025.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Furqan </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/025.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/025.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//026.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shu'ara' </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/026.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/026.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//027.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naml </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/027.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/027.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//028.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qasas </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/028.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/028.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//029.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Ankabut </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/029.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/029.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//030.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar­Room </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/030.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/030.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//031.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Luqman </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/031.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/031.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//032.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As­Sajdah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/032.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/032.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//033.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al­Ahzab </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/033.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/033.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//034.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Saba' </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/034.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/034.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//035.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fatir </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/035.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/035.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//036.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ya­Sin </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/036.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/036.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//037.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saffat </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/037.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/037.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//038.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Sad </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/038.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/038.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//039.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zumar </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/039.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/039.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//040.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ghafir </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/040.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/040.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//041.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Fussilat </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/041.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/041.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//042.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shura </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/042.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/042.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//043.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zukhruf </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/043.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/043.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//044.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Dukhan </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/044.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/044.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//045.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jathiya </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/045.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/045.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//046.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ahqaf </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/046.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/046.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//047.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Muhammad </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/047.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/047.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//048.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fath </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/048.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/048.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//049.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hujurat </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/049.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/049.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//050.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Qaf </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/050.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/050.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//051.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zariyat </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/051.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/051.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//052.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tur </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/052.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/052.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//053.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Najm </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/053.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/053.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//054.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qamar </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/054.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/054.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//055.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ar-Rahman </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/055.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/055.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//056.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Waqi'ah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/056.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/056.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//057.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hadid </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/057.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/057.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//058.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mujadilah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/058.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/058.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//059.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Hashr </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/059.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/059.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//060.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mumtahinah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/060.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/060.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//061.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>As-Saff </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/061.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/061.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//062.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jumu'ah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/062.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/062.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//063.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Munafiqun </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/063.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/063.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//064.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Taghabun </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/064.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/064.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//065.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Talaq </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/065.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/065.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//066.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tahrim </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/066.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/066.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//067.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mulk </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/067.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/067.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//068.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qalam </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/068.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/068.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//069.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Haqqah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/069.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/069.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//070.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'arij </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/070.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/070.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//071.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Nooh </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/071.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/071.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//072.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Jinn </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/072.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/072.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//073.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muzzammil </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/073.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/073.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//074.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Muddaththir </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/074.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/074.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//075.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qiyamah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/075.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/075.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//076.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Insan </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/076.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/076.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//077.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mursalat </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/077.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/077.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//078.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Naba' </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/078.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/078.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//079.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nazi'at </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/079.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/079.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//080.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>'Abasa </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/080.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/080.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//081.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takwir </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/081.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/081.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//082.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Infitar </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/082.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/082.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//083.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Mutaffifin </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/083.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/083.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//084.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Inshiqaq </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/084.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/084.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//085.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Buruj </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/085.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/085.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//086.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tariq </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/086.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/086.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//087.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-A'la </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/087.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/087.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//088.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ghashiyah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/088.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/088.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//089.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fajr </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/089.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/089.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//090.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Balad </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/090.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/090.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//091.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Shams </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/091.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/091.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//092.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Lail </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/092.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/092.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//093.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ad-Duha </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/093.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/093.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//094.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Ash-Sharh </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/094.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/094.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//095.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Tin </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/095.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/095.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//096.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Alaq </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/096.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/096.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//097.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qadr </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/097.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/097.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//098.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Baiyinah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/098.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/098.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//099.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Az-Zalzalah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/099.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/099.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//100.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Adiyat </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/100.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/100.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//101.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Qari'ah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/101.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/101.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//102.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>At-Takathur </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/102.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/102.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//103.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-'Asr </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/103.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/103.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//104.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Humazah </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/104.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/104.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//105.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Fil </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/105.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/105.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//106.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Quraish </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/106.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/106.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//107.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ma'un </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/107.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/107.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//108.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kauthar </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/108.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/108.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//109.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Kafirun </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/109.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/109.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//110.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nasr </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/110.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/110.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//111.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Masad </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/111.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/111.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//112.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Ikhlas </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/112.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/112.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//113.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>Al-Falaq </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/113.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/113.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Saud-Al-Shuraim//114.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>An-Nas </a><a class='dlink' href=' https://archive.org/download/Saud-Al-Shuraim/114.mp3' data-dlink=' https://archive.org/download/Saud-Al-Shuraim/114.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
							</ul>
						</div>  
			</div> 
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>  
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة</strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>Saud ibn Ibrahim ibn Muhammad al-Shuraim (Arabic: سعود بن ابراهيم بن محمد الشريم،, born in January 19, 1964) is one of the Imams and khateeb of the Grand Mosque (Masjid al-Haram) in Mecca. He holds a doctorate (Ph.D) and is a Professor of Sharia and Islamic studies at the Umm al-Qura University in Mecca, and was recently appointed as a Dean and "Specialist Professor in Fiqh" at the University.[1]<br>
					<br>
					He is also known as a researcher in fiqh, a judge, and a writer who has composed many books on aqeedah, fiqh, and Arabic poetry.<br><br>

					Shuraim leads the Taraweeh prayers during Ramadan in Mecca since 1991. He also led the Salat Al Mayyit (funeral prayer) for late Crown Prince Nayef bin Abdulaziz on 17 June 2012 after maghrib (sunset) prayer. King Abdullah of Saudi Arabia and the royal families were present at this funeral. His voice has been widely recorded and is internationally distributed by various mediums.
					</p>
				</div>  	
			</div>
			
</div>			



<?php  include $path . '/pages/footer.php'; ?>