<?php  
	$path = $_SERVER['DOCUMENT_ROOT'];
	$section = "reciters"; 
	include $path. '/pages/header.php';
	include $path . '/pages/navbar.php'; 
	
	$basename = substr(strtolower(basename($_SERVER['PHP_SELF'])),0,strlen(basename($_SERVER['PHP_SELF']))-4); 
	$current = $reciters["$basename"]; 
	$ClassName =  $current["name"] ;
	$ClassName = str_replace(' ', '', $ClassName); 
	    
?>  
<div class="container">
			<div class="row reciter-container">
				<?php 
					echo reciterHeaderNew($current,$user->logged_in);  
				?>  
				
			</div> 	
	        <div class="row reciter-container">	  
					   <div class=" archive-playlist-title">
											<p class="reciters">The Complete Holy Quran | القرآن الكريم</p> 
						</div>
						<?php  include $path . '/player/player_code.php';     ?> 
					
						<div id="playlist_list">
						<!-- local playlist -->
							<ul id='playlist1'>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//001-Al-fatiha.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>001-Al-Fatihah </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/001-Al-fatiha.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/001-Al-fatiha.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//002-Al-baqara.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>002 - Al-Baqara </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/002-Al-baqara.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/002-Al-baqara.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//004-An-nisa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>004 - An-Nisa </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/004-An-nisa.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/004-An-nisa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//005-Al-maeda.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>005 - Al-Maeda </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/005-Al-maeda.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/005-Al-maeda.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//006-Al-anaam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>006 - Al-An'aam </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/006-Al-anaam.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/006-Al-anaam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//003-Aal-e-imran.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>003 - Aal-e-Imran </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/003-Aal-e-imran.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/003-Aal-e-imran.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//007-Al-araf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>007 - Al-A'raf </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/007-Al-araf.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/007-Al-araf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//008-Al-anfal.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>008 - Al-Anfal </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/008-Al-anfal.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/008-Al-anfal.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//009-At-tawba.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>009 - At-Tawba </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/009-At-tawba.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/009-At-tawba.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//010-Yunus.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>010 - Yunus </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/010-Yunus.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/010-Yunus.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//011-Hud.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>011 - Hud </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/011-Hud.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/011-Hud.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//012-Yusuf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>012 - Yusuf </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/012-Yusuf.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/012-Yusuf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//013-Ar-rad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>013 - Ar-Ra'd </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/013-Ar-rad.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/013-Ar-rad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//014-Ibrahim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>014 - Ibrahim </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/014-Ibrahim.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/014-Ibrahim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//015-Al-hijr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>015 - Al-Hijr </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/015-Al-hijr.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/015-Al-hijr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//016-An-nahl.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>016 - An-Nahl </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/016-An-nahl.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/016-An-nahl.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//017-Al-isra.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>017 - Al-Isra </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/017-Al-isra.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/017-Al-isra.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//018-Al-kahf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>018 - Al-Kahf </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/018-Al-kahf.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/018-Al-kahf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//019-Maryam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>019 - Maryam </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/019-Maryam.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/019-Maryam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//021-Al-anbiya.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>021 - Al-Anbiya </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/021-Al-anbiya.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/021-Al-anbiya.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//022-Al-hajj.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>022 - Al-Hajj </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/022-Al-hajj.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/022-Al-hajj.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//023-Al-mumenoon.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>023 - Al-Mumenoon </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/023-Al-mumenoon.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/023-Al-mumenoon.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//024-An-noor.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>024 - An-Noor </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/024-An-noor.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/024-An-noor.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//025-Al-furqan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>025 - Al-Furqan </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/025-Al-furqan.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/025-Al-furqan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//026-Ash-shuara.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>026 - Ash-Shuara </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/026-Ash-shuara.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/026-Ash-shuara.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//027-An-naml.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>027 - An-Naml </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/027-An-naml.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/027-An-naml.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//028-Al-qasas.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>028 - Al-Qasas </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/028-Al-qasas.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/028-Al-qasas.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//029-Al-ankaboot.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>029 - Al-Ankaboot </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/029-Al-ankaboot.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/029-Al-ankaboot.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//030-Ar-room.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>030 - Ar-Room </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/030-Ar-room.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/030-Ar-room.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//031-Luqman.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>031 - Luqman </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/031-Luqman.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/031-Luqman.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//020-Taha.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>020 - Taha </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/020-Taha.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/020-Taha.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//032-As-sajda.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>032 - As-Sajda </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/032-As-sajda.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/032-As-sajda.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//033-Al-ahzab.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>033 - Al-Ahzab </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/033-Al-ahzab.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/033-Al-ahzab.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//034-Saba.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>034 - Saba </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/034-Saba.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/034-Saba.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//035-Fatir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>035 - Fatir </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/035-Fatir.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/035-Fatir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//036-Ya-seen.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>036 - Ya-seen </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/036-Ya-seen.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/036-Ya-seen.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//037-As-saaffat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>037 - As-Saaffat </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/037-As-saaffat.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/037-As-saaffat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//038-Sad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>038 - Sad </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/038-Sad.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/038-Sad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//039-Az-zumar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>039 - Az-Zumar </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/039-Az-zumar.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/039-Az-zumar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//040-Ghafir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>040 - Ghafir </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/040-Ghafir.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/040-Ghafir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//041-Fussilat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>041 - Fussilat </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/041-Fussilat.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/041-Fussilat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//042-Ash-shura.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>042 - Ash-Shura </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/042-Ash-shura.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/042-Ash-shura.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//043-Az-zukhruf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>043 - Az-Zukhruf </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/043-Az-zukhruf.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/043-Az-zukhruf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//044-Ad-dukhan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>044 - Ad-Dukhan </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/044-Ad-dukhan.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/044-Ad-dukhan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//045-Al-jathiya.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>045 - Al-Jathiya </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/045-Al-jathiya.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/045-Al-jathiya.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//046-Al-ahqaf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>046 - Al-Ahqaf </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/046-Al-ahqaf.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/046-Al-ahqaf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//047-Muhammad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>047 - Muhammad </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/047-Muhammad.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/047-Muhammad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//048-Al-fath.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>048 - Al-Fath </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/048-Al-fath.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/048-Al-fath.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//049-Al-hujraat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>049 - Al-Hujraat </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/049-Al-hujraat.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/049-Al-hujraat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//050-Qaf.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>050 - Qaf </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/050-Qaf.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/050-Qaf.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//051-Adh-dhariyat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>051 - Adh-Dhariyat </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/051-Adh-dhariyat.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/051-Adh-dhariyat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//052-At-tur.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>052 - At-Tur </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/052-At-tur.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/052-At-tur.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//053-An-najm.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>053 - An-Najm </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/053-An-najm.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/053-An-najm.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//054-Al-qamar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>054 - Al-Qamar </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/054-Al-qamar.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/054-Al-qamar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//055-Ar-rahman.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>055 - Ar-Rahman </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/055-Ar-rahman.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/055-Ar-rahman.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//056-Al-waqia.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>056 - Al-Waqi'a </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/056-Al-waqia.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/056-Al-waqia.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//057-Al-hadid.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>057 - Al-Hadid </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/057-Al-hadid.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/057-Al-hadid.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//058-Al-mujadala.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>058 - Al-Mujadala </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/058-Al-mujadala.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/058-Al-mujadala.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//059-Al-hashr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>059 - Al-Hashr </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/059-Al-hashr.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/059-Al-hashr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//060-Al-mumtahana.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>060 - Al-Mumtahana </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/060-Al-mumtahana.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/060-Al-mumtahana.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//061-As-saff.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>061 - As-Saff </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/061-As-saff.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/061-As-saff.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//062-Al-jumua.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>062 - Al-Jumu'a </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/062-Al-jumua.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/062-Al-jumua.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//063-Al-munafiqoon.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>063 - Al-Munafiqoon </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/063-Al-munafiqoon.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/063-Al-munafiqoon.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//064-At-taghabun.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>064 - At-Taghabun </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/064-At-taghabun.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/064-At-taghabun.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//065-At-talaq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>065 - At-Talaq </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/065-At-talaq.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/065-At-talaq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//066-At-tahrim.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>066 - At-Tahrim </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/066-At-tahrim.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/066-At-tahrim.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//067-Al-mulk.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>067 - Al-Mulk </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/067-Al-mulk.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/067-Al-mulk.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//068-Al-qalam.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>068 - Al-Qalam </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/068-Al-qalam.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/068-Al-qalam.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//069-Al-haaqqa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>069 - Al-Haaqqa </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/069-Al-haaqqa.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/069-Al-haaqqa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//070-Al-maarij.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>070 - Al-Maarij </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/070-Al-maarij.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/070-Al-maarij.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//071-Nooh.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>071 - Nooh </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/071-Nooh.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/071-Nooh.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//072-Al-jinn.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>072 - Al-Jinn </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/072-Al-jinn.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/072-Al-jinn.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//073-Al-muzzammil.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>073 - Al-Muzzammil </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/073-Al-muzzammil.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/073-Al-muzzammil.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//074-Al-muddaththir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>074 - Al-Muddaththir </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/074-Al-muddaththir.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/074-Al-muddaththir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//075-Al-qiyama.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>075 - Al-Qiyama </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/075-Al-qiyama.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/075-Al-qiyama.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//076-Al-insan.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>076 - Al-Insan </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/076-Al-insan.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/076-Al-insan.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//077-Al-mursalat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>077 - Al-Mursalat </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/077-Al-mursalat.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/077-Al-mursalat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//078-An-naba.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>078 - An-Naba </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/078-An-naba.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/078-An-naba.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//079-An-naziat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>079 - An-Nazi'at </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/079-An-naziat.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/079-An-naziat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//080-Abasa.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>080 - Abasa </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/080-Abasa.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/080-Abasa.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//081-At-takwir.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>081 - At-Takwir </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/081-At-takwir.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/081-At-takwir.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//082-Al-infitar.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>082 - Al-Infitar </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/082-Al-infitar.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/082-Al-infitar.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//083-Al-mutaffifin.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>083 - Al-Mutaffifin </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/083-Al-mutaffifin.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/083-Al-mutaffifin.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//084-Al-inshiqaq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>084 - Al-Inshiqaq </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/084-Al-inshiqaq.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/084-Al-inshiqaq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//085-Al-burooj.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>085 - Al-Burooj </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/085-Al-burooj.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/085-Al-burooj.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//086-At-tariq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>086 - At-Tariq </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/086-At-tariq.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/086-At-tariq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//087-Al-ala.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>087 - Al-A'la </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/087-Al-ala.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/087-Al-ala.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//088-Al-ghashiya.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>088 - Al-Ghashiya </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/088-Al-ghashiya.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/088-Al-ghashiya.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//089-Al-fajr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>089 - Al-Fajr </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/089-Al-fajr.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/089-Al-fajr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//090-Al-balad.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>090 - Al-Balad </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/090-Al-balad.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/090-Al-balad.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//091-Ash-shams.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>091 - Ash-Shams </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/091-Ash-shams.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/091-Ash-shams.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//092-Al-layl.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>092 - Al-Layl </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/092-Al-layl.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/092-Al-layl.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//093-Ad-dhuha.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>093 - Ad-Dhuha </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/093-Ad-dhuha.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/093-Ad-dhuha.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//094-As-sharh.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>094 - As-Sharh </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/094-As-sharh.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/094-As-sharh.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//095-At-tin.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>095 - At-Tin </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/095-At-tin.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/095-At-tin.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//096-Al-alaq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>096 - Al-'alaq </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/096-Al-alaq.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/096-Al-alaq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//097-Al-qadr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>097 - Al-Qadr </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/097-Al-qadr.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/097-Al-qadr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//098-Al-bayyina.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>098 - Al-Bayyina </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/098-Al-bayyina.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/098-Al-bayyina.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//099-Az-zalzala.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>099 - Az-Zalzala </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/099-Az-zalzala.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/099-Az-zalzala.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//100-Al-adiyat.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>100 - Al-'adiyat </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/100-Al-adiyat.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/100-Al-adiyat.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//101-Al-qaria.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>101 - Al-Qari'a </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/101-Al-qaria.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/101-Al-qaria.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//102-At-takathur.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>102 - At-Takathur </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/102-At-takathur.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/102-At-takathur.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//103-Al-asr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>103 - Al-Asr </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/103-Al-asr.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/103-Al-asr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//104-Al-humaza.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>104 - Al-Humaza </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/104-Al-humaza.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/104-Al-humaza.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//105-Al-fil.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>105 - Al-Fil </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/105-Al-fil.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/105-Al-fil.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//106-Quraish.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>106 - Quraish </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/106-Quraish.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/106-Quraish.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//107-Al-maun.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>107 - Al-Ma'un </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/107-Al-maun.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/107-Al-maun.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//108-Al-kauther.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>108 - Al-Kauther </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/108-Al-kauther.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/108-Al-kauther.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//109-Al-kafiroon.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>109 - Al-Kafiroon </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/109-Al-kafiroon.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/109-Al-kafiroon.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//110-An-nasr.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>110 - An-Nasr </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/110-An-nasr.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/110-An-nasr.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//111-Al-masadd.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>111 - Al-Masadd </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/111-Al-masadd.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/111-Al-masadd.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//112-Al-ikhlas.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>112 - Al-Ikhlas </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/112-Al-ikhlas.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/112-Al-ikhlas.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//113-Al-falaq.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>113 - Al-Falaq </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/113-Al-falaq.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/113-Al-falaq.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								<li class= 'playlistItem' data-type='local' data-mp3='https://archive.org/download/Yasser-AlDosari//114-An-nas.mp3' data-ogg='' data-download><a class='playlistNonSelected' href='#'>114 - An-Nas </a><a class='dlink' href=' https://archive.org/download/Yasser-AlDosari/114-An-nas.mp3' data-dlink=' https://archive.org/download/Yasser-AlDosari/114-An-nas.mp3'><img src='media/data/dlink.png' alt = ''/></a></li>
								
							</ul>
						</div>  
			</div>  
					
					 
		    </div> 	
			<div class="row reciter-container">		
					<br> 			
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Quran Reciters Pages Unit -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:100%;height:90px"
						 data-ad-client="ca-pub-9126659759556489"
						 data-ad-slot="5287989599"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>    
		    </div>  
			<div class="row reciter-container">	
				<?php 
					echo getGallery($current); 
				?>  
			  
		    </div> 
			<div class="row reciter-container">
			    <div class="col-md-12 archive-playlist-title">
						<h1 class="reciters"><strong>Biography | سيرة </strong>  </h1>
				</div>
				<div id="reciter-bio">
					<p>Newly appointed Imam of Masjid Al Haram <br>Qur'an Full by Shaykh Yasser Al Dosari in high quality
						القرآن كامل بصوت الشيخ ياسر الدوسري بجودة عالية جدا
					</p>
					<p><strong>Academic Qualifications:</strong></p>

					<p>&nbsp;</p>

					<p>&bull; Bachelor of Sharia, Imam Muhammad Ibn Saud Islamic University</p>

					<p>&bull; Master in Holy Quran and its Sciences</p>

					<p>&bull; Master of Juristic principles of Competition (Sabk) and Jeala (a specific amount of money obtained for achieving a specific work), High Institute of Judicature, Imam Muhammad Ibn Saud Islamic University, in progress.</p>

					<p>&nbsp;</p>

					<p><strong>Marital Status:</strong>&nbsp;Married and have three children (boy and two daughters)</p>

					<p>&nbsp;</p>

					<p><strong>Positions:</strong></p>

					<p>&nbsp;</p>

					<p>&bull; Secretary General of Prince Sultan Association for Memorizing the Holy Quran, Air Defense Forces;</p>

					<p>&bull; Member of Saudi Juristic and Scientific Association;</p>

					<p>&bull; Member of Saudi Scientific Association for the Noble Quran and its Sciences;</p>

					<p>&bull; Member of Saudi Association for Da&rsquo;wa Studies;</p>

					<p>&bull; Imam of Eldikhel Mosque and Supervisor of its activities, Riyadh;</p>

					<p>&bull; Member of European Committee of International Islamic Youth Seminar; and</p>

					<p>&bull; Member of Charitable Organization in Kharj&nbsp;Quraa&rsquo; (Reciters) Whom Read on Them</p>

					<p>&bull; Shiekh Bakri Al-Trabishi (the highest Sanad (list of citations for successive narrators reaching back to the original narrator) in the world)</p>

					<p>&bull; Shiekh Ibrahim Al-Akhdar (Madina&rsquo;s Shiekh Quraa&rsquo; (Head of reciters), in progress</p>

					<p>&bull; Shiekh Mohammed Tamim Alzobi (member of the Noble Quran Revising Committee of King Fahd Complex), in progress</p>

					<p>&bull; Shiekh Mahmoud Ibn Omar Sokar (reciter of the Noble Quran ten recitations)</p>

					<p>&bull; Shiekh Ahmed Khalil Shahen (reciter of the Noble Quran ten recitations)</p>

					<p>&bull; Shiekh Sad Sonbl (reciter of the Noble Quran ten recitations)</p>

					<p>&bull; Shiekh Abdullah Al-gar Allah (authorized with the Noble Quran ten recitations on the hands of the following Shiekhs: Al-samanody, Al-zayat, Al-akhdar, Abdul-rafeh Radwan, Alzobi, Karim Rageh, Al-Hozaifi, Al-Tarabishi, Abo-Alhassan Al-kordi and Abdul-Hakim Khater)</p> 
					<p>8. Annual participation in arbitration of the local competition of the Noble Quran, under supervision of the Ministry of Defense. In addition, he participates in arbitration of Prince Sultan International Competition for Memorizing the Noble Quran for soldiers </p> 
				</div>  	
			</div> 
 

</div>
			 
 

<?php  include $path . '/pages/footer.php'; ?>


